"""
Django settings for EcommerceProject project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file():
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        return {}
    values = {}
    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        values[key] = value
        os.environ[key] = value
    return values


_ENV_VALUES = _load_env_file()


def _env(key, default=''):
    value = _ENV_VALUES.get(key)
    if value is None:
        value = os.environ.get(key, default)
    return value or default


# Render detection vars (used early for ALLOWED_HOSTS, CSRF, sqlite guard, etc.)
RENDER_EXTERNAL_HOSTNAME = _env('RENDER_EXTERNAL_HOSTNAME')
render_disk_path = _env('RENDER_DISK_PATH', '')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _env('SECRET_KEY', 'django-insecure-_73#1@hjsxhlmfx4+&85s10a(cyb9i*q7-28$_zpjz5vm&+0ek')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env('DEBUG', 'True').lower() in ('true', '1', 'yes')

# ALLOWED_HOSTS: always support local development even if .env has production values
# (e.g. ALLOWED_HOSTS from Render .env section)
_allowed = _env('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = []
for h in _allowed.split(','):
    h = h.strip()
    if not h:
        continue
    # Strip scheme if someone put full URL by mistake (e.g. https://...)
    if '://' in h:
        h = urlparse(h).hostname or h
    ALLOWED_HOSTS.append(h)

if DEBUG:
    # Ensure local runserver works (127.0.0.1:8000, localhost, etc.)
    for local in ['localhost', '127.0.0.1', '0.0.0.0']:
        if local not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(local)

# Remove duplicates while preserving order
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))

# Render specific: add the service hostname if provided.
# Render automatski injektuje RENDER_EXTERNAL_HOSTNAME za svaki Web Service.
# Nema potrebe da ga ručno postavljaš (Render to radi sam).
# Kod ga koristi da doda u ALLOWED_HOSTS.
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# CSRF trusted origins - important for Render + local dev
CSRF_TRUSTED_ORIGINS = []

# From environment (recommended)
csrf_origins = _env('CSRF_TRUSTED_ORIGINS', '')
if csrf_origins:
    CSRF_TRUSTED_ORIGINS.extend(
        [origin.strip() for origin in csrf_origins.split(',') if origin.strip()]
    )

# Auto-trust Render domains (very important!)
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# Always trust all .onrender.com subdomains when on Render
# This makes it work even if RENDER_EXTERNAL_HOSTNAME is not set yet
if _env('RENDER_EXTERNAL_HOSTNAME') or _env('RENDER', '') or render_disk_path:
    if 'https://*.onrender.com' not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append('https://*.onrender.com')

# Always allow common local development origins when DEBUG=True
if DEBUG:
    for origin in ['http://localhost', 'http://127.0.0.1', 'http://localhost:8000', 'http://127.0.0.1:8000']:
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)

# Remove duplicates
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

# Always trust *.onrender.com (makes it work reliably on Render without manual setup every time)
if 'https://*.onrender.com' not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append('https://*.onrender.com')

# Behind Render/Cloudflare HTTPS proxy Django must trust X-Forwarded-Proto (also with DEBUG=True).
if RENDER_EXTERNAL_HOSTNAME or _env('RENDER', ''):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Production security settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'EcommerceApp.apps.EcommerceappConfig',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise for static files (must be right after SecurityMiddleware)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'EcommerceApp.middleware.site_prep_lock.SitePrepLockMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EcommerceProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'EcommerceApp' / 'template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'EcommerceApp.context_processors.nav_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'EcommerceProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use PostgreSQL on Render (via DATABASE_URL), fallback to SQLite for local dev
database_url = _env('DATABASE_URL')
if database_url:
    DATABASES = {
        'default': dj_database_url.config(
            default=database_url,
            conn_max_age=600,
            ssl_require=True,  # Render Postgres requires SSL
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 60,
            },
        }
    }

# Prevent use of SQLite on actual Render production deploys.
# We only enforce this when DEBUG=False AND we see Render-specific env vars
# (RENDER_DISK_PATH or RENDER_EXTERNAL_HOSTNAME). This way local `runserver`
# can still use SQLite comfortably.
if (not DEBUG
        and 'sqlite3' in DATABASES['default']['ENGINE']
        and (_env('RENDER_DISK_PATH') or _env('RENDER_EXTERNAL_HOSTNAME'))):
    raise RuntimeError(
        "Production on Render MUST use PostgreSQL via DATABASE_URL. "
        "SQLite gets wiped on every deploy and is not allowed when DEBUG=False."
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = _env('STATIC_URL', '/static/')
if not STATIC_URL.startswith('/'):
    STATIC_URL = '/' + STATIC_URL.lstrip('/')
STATICFILES_DIRS = [
    BASE_DIR / 'EcommerceApp' / 'static',
]

# WhiteNoise for efficient static file serving in production
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_MAX_AGE = 31536000
MEDIA_CACHE_MAX_AGE = int(_env('MEDIA_CACHE_MAX_AGE', '31536000'))
WHITENOISE_SKIP_COMPRESS_EXTENSIONS = ('jpg', 'jpeg', 'png', 'gif', 'webp', 'avif', 'svg', 'ico')

# Media files
# Local dev: ./media/
# On Render: use attached Disk (set RENDER_DISK_PATH in environment variables)
MEDIA_URL = _env('MEDIA_URL', '/media/')
if not MEDIA_URL.startswith('/'):
    MEDIA_URL = '/' + MEDIA_URL.lstrip('/')
if render_disk_path:
    MEDIA_ROOT = Path(render_disk_path) / 'media'
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# Ensure media directory and common subdirectories exist (important for disk on Render)
# This runs safely even if the disk is not yet mounted.
try:
    MEDIA_ROOT.mkdir(parents=True, exist_ok=True)
    for sub in ['products', 'products/variations', 'site', 'banners', 'popups', 'upsell', 'brands']:
        (MEDIA_ROOT / sub).mkdir(parents=True, exist_ok=True)
except (PermissionError, OSError):
    # On Render the disk may not be mounted yet, or in local dev without write perms.
    # Ignore silently; first upload will try to create dirs.
    if render_disk_path and not os.path.exists(render_disk_path):
        print(f"WARNING: RENDER_DISK_PATH={render_disk_path} is set but the directory does not exist yet. "
              "Attach the disk in Render and redeploy.")
    pass

# Email — ProtonMail SMTP (EMAIL_APP_PASSWORD ili EMAIL_HOST_PASSWORD = SMTP token)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = _env('EMAIL_HOST', 'smtp.protonmail.ch')
EMAIL_PORT = int(_env('EMAIL_PORT', '587'))
EMAIL_USE_TLS = _env('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_USE_SSL = _env('EMAIL_USE_SSL', 'false').lower() == 'true'
EMAIL_HOST_USER = _env('EMAIL_HOST_USER', 'narudzbe@opremazaribolov.ba')
EMAIL_HOST_PASSWORD = (
    _env('EMAIL_APP_PASSWORD') or _env('EMAIL_HOST_PASSWORD')
).replace(' ', '')
DEFAULT_FROM_EMAIL = _env('DEFAULT_FROM_EMAIL', 'narudzbe@opremazaribolov.ba')
SERVER_EMAIL = DEFAULT_FROM_EMAIL
ORDER_NOTIFICATION_EMAIL = _env(
    'ORDER_NOTIFICATION_EMAIL',
    'narudzbe@opremazaribolov.ba',
).strip().lower()
EMAIL_TIMEOUT = int(_env('EMAIL_TIMEOUT', '30'))
SITE_URL = _env('SITE_URL', 'https://www.opremazaribolov.ba').rstrip('/')
STORE_PHONE = _env('STORE_PHONE', '')
STORE_EMAIL = _env('STORE_EMAIL', 'narudzbe@opremazaribolov.ba')

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'account'
LOGOUT_REDIRECT_URL = 'home'

# Sync prema Loyalty Programu na Renderu (loyaltyprogram-jsg5.onrender.com)
SYNC_REMOTE_URL = _env('SYNC_REMOTE_URL', '').rstrip('/')
SYNC_API_KEY = _env('SYNC_API_KEY', '')
SYNC_TIMEOUT = int(_env('SYNC_TIMEOUT', '15'))
# Sync je omogućen ako su URL i KEY postavljeni.
# Render automatski postavlja neke varijable (npr. RENDER_EXTERNAL_HOSTNAME).
# Ako želiš, možeš postaviti RENDER=true u environment za custom logiku.
SYNC_ENABLED = bool(SYNC_REMOTE_URL and SYNC_API_KEY)

# Odoo import (XML-RPC, API ključ kao lozinka)
ODOO_URL = _env('ODOO_URL', '').rstrip('/')
ODOO_DB = _env('ODOO_DB', '')
ODOO_USERNAME = _env('ODOO_USERNAME', '')
ODOO_API_KEY = _env('ODOO_API_KEY', '')

# Cloudflare Turnstile (https://developers.cloudflare.com/turnstile/)
TURNSTILE_SITE_KEY = _env('TURNSTILE_SITE_KEY', '')
TURNSTILE_SECRET_KEY = _env('TURNSTILE_SECRET_KEY', '')

# Zaštita sajta dok je u pripremi (SITE_PREP_ENABLED=false kad završiš lansiranje)
SITE_PREP_PASSWORD = _env('SITE_PREP_PASSWORD', 'OpremaZaribolov2026')
_site_prep_env = _env('SITE_PREP_ENABLED', '').lower()
if _site_prep_env in ('false', '0', 'no'):
    SITE_PREP_ENABLED = False
elif _site_prep_env in ('true', '1', 'yes'):
    SITE_PREP_ENABLED = True
else:
    SITE_PREP_ENABLED = bool(SITE_PREP_PASSWORD)
SITE_PREP_SESSION_KEY = 'site_prep_unlocked'