"""
Django settings for EcommerceProject project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file():
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        return {}
    values = {}
    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        values[key] = value
        os.environ[key] = value
    return values


_ENV_VALUES = _load_env_file()


def _env(key, default=''):
    value = _ENV_VALUES.get(key)
    if value is None:
        value = os.environ.get(key, default)
    return value or default


# Render detection vars (used early for ALLOWED_HOSTS, CSRF, sqlite guard, etc.)
RENDER_EXTERNAL_HOSTNAME = _env('RENDER_EXTERNAL_HOSTNAME')
render_disk_path = _env('RENDER_DISK_PATH', '')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _env('SECRET_KEY', 'django-insecure-_73#1@hjsxhlmfx4+&85s10a(cyb9i*q7-28$_zpjz5vm&+0ek')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env('DEBUG', 'True').lower() in ('true', '1', 'yes')

# Brzi in-memory cache (meni, SiteSettings, brendovi, home sekcije)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'ozb-site-cache',
        'TIMEOUT': 180,
        'OPTIONS': {'MAX_ENTRIES': 4000},
    }
}

# ALLOWED_HOSTS: env + production domains + Render hostname
# (DisallowedHost / “Invalid HTTP_HOST” ako custom domain nije na listi)
def _normalize_allowed_host(h: str) -> str:
    """Django: subdomain wildcard je '.example.com', ne '*.example.com'."""
    h = (h or '').strip()
    if not h:
        return ''
    if '://' in h:
        h = urlparse(h).hostname or h
    h = h.strip()
    # Render / Cloudflare često stavlja *.onrender.com — pretvori u .onrender.com
    if h.startswith('*.'):
        h = h[1:]  # *.onrender.com → .onrender.com
    return h


_allowed = _env('ALLOWED_HOSTS', 'localhost,127.0.0.1,192.168.1.103')
ALLOWED_HOSTS = []
for h in _allowed.split(','):
    h = _normalize_allowed_host(h)
    if h:
        ALLOWED_HOSTS.append(h)
# Lokalna mreža (dev telefon / LAN) — ne smije biti jedini host u produkciji
if '192.168.1.103' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('192.168.1.103')

# Produkcijski domeni (uvijek — da Cloudflare → Render ne padne na host grešku)
for _prod_host in (
    'opremazaribolov.ba',
    'www.opremazaribolov.ba',
    'media.opremazaribolov.ba',
):
    if _prod_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_prod_host)

# Host iz SITE_URL env (ako je drugačiji custom domain)
_site_url_early = _env('SITE_URL', 'https://www.opremazaribolov.ba')
_site_host = urlparse(_site_url_early).hostname if _site_url_early else None
if _site_host and _site_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_site_host)

if DEBUG:
    # Ensure local runserver works (127.0.0.1:8000, localhost, etc.)
    for local in ['localhost', '127.0.0.1', '0.0.0.0']:
        if local not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(local)

# Render specific: add the service hostname if provided.
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    # npr. ecommercerepository.onrender.com
    if RENDER_EXTERNAL_HOSTNAME.endswith('.onrender.com'):
        ALLOWED_HOSTS.append('.onrender.com')

# Remove duplicates while preserving order
ALLOWED_HOSTS = list(dict.fromkeys([h for h in ALLOWED_HOSTS if h]))

# CSRF trusted origins - important for Render + local dev
CSRF_TRUSTED_ORIGINS = []

# From environment (recommended)
csrf_origins = _env('CSRF_TRUSTED_ORIGINS', '')
if csrf_origins:
    CSRF_TRUSTED_ORIGINS.extend(
        [origin.strip() for origin in csrf_origins.split(',') if origin.strip()]
    )

# Auto-trust Render domains (very important!)
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# Always trust all .onrender.com subdomains when on Render
if _env('RENDER_EXTERNAL_HOSTNAME') or _env('RENDER', '') or render_disk_path:
    if 'https://*.onrender.com' not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append('https://*.onrender.com')

# Produkcijski CSRF (Cloudflare custom domain)
for _origin in (
    'https://opremazaribolov.ba',
    'https://www.opremazaribolov.ba',
):
    if _origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_origin)
if _site_host:
    _site_origin = f'https://{_site_host}'
    if _site_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_site_origin)

# Always allow common local development origins when DEBUG=True
if DEBUG:
    for origin in ['http://localhost', 'http://127.0.0.1', 'http://localhost:8000', 'http://127.0.0.1:8000']:
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)

# Remove duplicates
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

# Always trust *.onrender.com (makes it work reliably on Render without manual setup every time)
if 'https://*.onrender.com' not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append('https://*.onrender.com')

# Behind Render/Cloudflare HTTPS proxy Django must trust X-Forwarded-Proto.
# Without this, request.is_secure() is False, Secure cookies se ne šalju nazad
# i korisnik se na sljedećem kliku opet vidi kao odjavljen.
if (not DEBUG) or RENDER_EXTERNAL_HOSTNAME or _env('RENDER', ''):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14
# Login ostaje preko cookie domain + SECURE_PROXY_SSL_HEADER.
# True ovdje piše django_session na SVAKI request (heartbeat/ponuda/chat)
# i na 0.5 CPU + 1 worker pravi delay i CPU spike.
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Production security settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    # Isti login na opremazaribolov.ba i www.opremazaribolov.ba
    _cookie_domain = _env('SESSION_COOKIE_DOMAIN', '')
    if not _cookie_domain and _site_host and _site_host.endswith('opremazaribolov.ba'):
        _cookie_domain = '.opremazaribolov.ba'
    if _cookie_domain:
        SESSION_COOKIE_DOMAIN = _cookie_domain
        CSRF_COOKIE_DOMAIN = _cookie_domain


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'EcommerceApp.apps.EcommerceappConfig',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Gzip samo HTML — JSON pollovi su sitni, gzip jede CPU
    'EcommerceApp.middleware.gzip_html.HtmlGZipMiddleware',
    # WhiteNoise for static files (must be right after SecurityMiddleware)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'EcommerceApp.middleware.live_visitor.LiveVisitorMiddleware',
    'EcommerceApp.middleware.site_prep_lock.SitePrepLockMiddleware',
    'EcommerceApp.middleware.meta_page_view.MetaPageViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EcommerceProject.urls'

_TEMPLATE_LOADERS = [
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
]
# Produkcija: keširani template loader (brži render, isti HTML)
if not DEBUG:
    _TEMPLATE_LOADERS = [
        ('django.template.loaders.cached.Loader', _TEMPLATE_LOADERS),
    ]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'EcommerceApp' / 'template'],
        'APP_DIRS': False if not DEBUG else True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'EcommerceApp.context_processors.nav_categories',
                'EcommerceApp.context_processors.meta_pixel',
                'EcommerceApp.site_version.site_version',
            ],
            **({} if DEBUG else {'loaders': _TEMPLATE_LOADERS}),
        },
    },
]
# Kad loaders nisu u OPTIONS (DEBUG), APP_DIRS=True; kad loaders jesu, APP_DIRS mora False
if not DEBUG:
    TEMPLATES[0]['OPTIONS']['loaders'] = _TEMPLATE_LOADERS

WSGI_APPLICATION = 'EcommerceProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use PostgreSQL on Render (via DATABASE_URL), fallback to SQLite for local dev
database_url = _env('DATABASE_URL')
if database_url:
    DATABASES = {
        'default': dj_database_url.config(
            default=database_url,
            conn_max_age=600,
            ssl_require=True,  # Render Postgres requires SSL
            conn_health_checks=True,
        )
    }
    # Ne drži request zauvijek ako Postgres ne odgovara (inače cijeli sajt “visi”)
    _db_opts = dict(DATABASES['default'].get('OPTIONS') or {})
    _db_opts.setdefault('connect_timeout', 10)
    DATABASES['default']['OPTIONS'] = _db_opts
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            # IMMEDIATE + timeout: izbjegava DEFERRED deadlock ("database is locked"
            # odmah) kad više requestova radi update_or_create / atomic (live tracking,
            # korpa, heartbeat, staff poll).
            'OPTIONS': {
                'timeout': 30,
                'transaction_mode': 'IMMEDIATE',
            },
            'CONN_MAX_AGE': 0,
        }
    }

# Prevent use of SQLite on actual Render production deploys.
# We only enforce this when DEBUG=False AND we see Render-specific env vars
# (RENDER_DISK_PATH or RENDER_EXTERNAL_HOSTNAME). This way local `runserver`
# can still use SQLite comfortably.
if (not DEBUG
        and 'sqlite3' in DATABASES['default']['ENGINE']
        and (_env('RENDER_DISK_PATH') or _env('RENDER_EXTERNAL_HOSTNAME'))):
    raise RuntimeError(
        "Production on Render MUST use PostgreSQL via DATABASE_URL. "
        "SQLite gets wiped on every deploy and is not allowed when DEBUG=False."
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Bulk admin akcije (npr. tagovi na mnogo podkategorija) šalju puno POST polja
DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000

TIME_ZONE = 'Europe/Sarajevo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = _env('STATIC_URL', '/static/')
if not STATIC_URL.startswith('/'):
    STATIC_URL = '/' + STATIC_URL.lstrip('/')
STATICFILES_DIRS = [
    BASE_DIR / 'EcommerceApp' / 'static',
]

# WhiteNoise for efficient static file serving in production
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_MAX_AGE = 31536000
MEDIA_CACHE_MAX_AGE = int(_env('MEDIA_CACHE_MAX_AGE', '31536000'))
WHITENOISE_SKIP_COMPRESS_EXTENSIONS = ('jpg', 'jpeg', 'png', 'gif', 'webp', 'avif', 'svg', 'ico')

# Media files
# Local / Render disk (fallback) OR Cloudflare R2 when R2_* env vars are set.
# R2 = S3-compatible object storage + Cloudflare CDN (brže od Render diska).
MEDIA_URL = _env('MEDIA_URL', '/media/')
if render_disk_path:
    MEDIA_ROOT = Path(render_disk_path) / 'media'
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# —— Cloudflare R2 (opcionalno; kad je upaljeno, upload ide na R2 umjesto diska) ——
R2_ACCOUNT_ID = _env('R2_ACCOUNT_ID', '').strip()
R2_ACCESS_KEY_ID = _env('R2_ACCESS_KEY_ID', '').strip()
R2_SECRET_ACCESS_KEY = _env('R2_SECRET_ACCESS_KEY', '').strip()
R2_BUCKET_NAME = _env('R2_BUCKET_NAME', '').strip()
# Javni URL: custom domen (preporučeno) npr. media.opremazaribolov.ba
# ili R2 public bucket URL (*.r2.dev)
R2_CUSTOM_DOMAIN = _env('R2_CUSTOM_DOMAIN', '').strip()  # host ili full https://...
R2_PUBLIC_BASE_URL = _env('R2_PUBLIC_BASE_URL', '').strip().rstrip('/')  # full https://...
R2_LOCATION = _env('R2_LOCATION', '').strip().strip('/')  # opcionalni prefix u bucketu

USE_R2_MEDIA = bool(
    R2_ACCOUNT_ID and R2_ACCESS_KEY_ID and R2_SECRET_ACCESS_KEY and R2_BUCKET_NAME
)


def _normalize_media_host(value: str) -> str:
    value = (value or '').strip()
    if not value:
        return ''
    if '://' in value:
        return (urlparse(value).netloc or value).split('/')[0]
    return value.split('/')[0]


if USE_R2_MEDIA:
    # Endpoint:
    #  - standard: https://<ACCOUNT_ID>.r2.cloudflarestorage.com
    #  - EU jurisdiction bucket: https://<ACCOUNT_ID>.eu.r2.cloudflarestorage.com
    #  - ili puni URL preko R2_ENDPOINT_URL
    _r2_jurisdiction = _env('R2_JURISDICTION', '').strip().lower()  # npr. eu
    _r2_endpoint_override = _env('R2_ENDPOINT_URL', '').strip().rstrip('/')
    if _r2_endpoint_override:
        _r2_endpoint = _r2_endpoint_override
    elif _r2_jurisdiction:
        _r2_endpoint = f'https://{R2_ACCOUNT_ID}.{_r2_jurisdiction}.r2.cloudflarestorage.com'
    else:
        _r2_endpoint = f'https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com'

    _r2_domain = _normalize_media_host(R2_CUSTOM_DOMAIN)
    if _r2_domain:
        MEDIA_URL = f'https://{_r2_domain}/'
        if R2_LOCATION:
            MEDIA_URL = f'{MEDIA_URL}{R2_LOCATION}/'
    elif R2_PUBLIC_BASE_URL:
        MEDIA_URL = R2_PUBLIC_BASE_URL + '/'
        if R2_LOCATION and not MEDIA_URL.rstrip('/').endswith('/' + R2_LOCATION):
            MEDIA_URL = R2_PUBLIC_BASE_URL.rstrip('/') + '/' + R2_LOCATION + '/'
    else:
        # Fallback (često treba public access / custom domain za browsere)
        MEDIA_URL = f'{_r2_endpoint}/{R2_BUCKET_NAME}/'
        if R2_LOCATION:
            MEDIA_URL = f'{MEDIA_URL}{R2_LOCATION}/'

    # django-storages / boto3 (global AWS_* koje storages često čita)
    # R2 NE podržava ACL — AWS_DEFAULT_ACL mora biti None (bez public-read)
    AWS_ACCESS_KEY_ID = R2_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = R2_SECRET_ACCESS_KEY
    AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME
    AWS_S3_ENDPOINT_URL = _r2_endpoint
    AWS_S3_REGION_NAME = _env('R2_REGION', 'auto')
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_ADDRESSING_STYLE = 'path'
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = True  # bez exists() prije svakog uploada
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': f'public, max-age={MEDIA_CACHE_MAX_AGE}, immutable',
    }
    if _r2_domain:
        AWS_S3_CUSTOM_DOMAIN = _r2_domain

    _r2_options = {
        'bucket_name': R2_BUCKET_NAME,
        'endpoint_url': _r2_endpoint,
        'access_key': R2_ACCESS_KEY_ID,
        'secret_key': R2_SECRET_ACCESS_KEY,
        'region_name': AWS_S3_REGION_NAME,
        'default_acl': None,
        'querystring_auth': False,
        'file_overwrite': True,
        'addressing_style': 'path',
        'signature_version': 's3v4',
        'object_parameters': {
            'CacheControl': f'public, max-age={MEDIA_CACHE_MAX_AGE}, immutable',
        },
    }
    if _r2_domain:
        _r2_options['custom_domain'] = _r2_domain
    if R2_LOCATION:
        _r2_options['location'] = R2_LOCATION

    STORAGES = {
        'default': {
            'BACKEND': 'EcommerceApp.storage_backends.CloudflareR2Storage',
            'OPTIONS': _r2_options,
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
    DEFAULT_FILE_STORAGE = 'EcommerceApp.storage_backends.CloudflareR2Storage'
else:
    # Lokalni /media/ path
    if not MEDIA_URL.startswith('/'):
        MEDIA_URL = '/' + MEDIA_URL.lstrip('/')
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
            'OPTIONS': {
                'location': str(MEDIA_ROOT),
                'base_url': MEDIA_URL,
            },
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# Ensure local media dirs exist only when not on R2 (or for sync/fallback)
if not USE_R2_MEDIA:
    try:
        MEDIA_ROOT.mkdir(parents=True, exist_ok=True)
        for sub in ['products', 'products/variations', 'site', 'banners', 'popups', 'upsell', 'brands']:
            (MEDIA_ROOT / sub).mkdir(parents=True, exist_ok=True)
    except (PermissionError, OSError):
        if render_disk_path and not os.path.exists(render_disk_path):
            print(
                f'WARNING: RENDER_DISK_PATH={render_disk_path} is set but the directory does not exist yet. '
                'Attach the disk in Render and redeploy.',
            )
        pass
else:
    # MEDIA_ROOT ostaje za management komande (sync sa diska → R2)
    try:
        MEDIA_ROOT.mkdir(parents=True, exist_ok=True)
    except (PermissionError, OSError):
        pass

# Email — ProtonMail SMTP (EMAIL_APP_PASSWORD ili EMAIL_HOST_PASSWORD = SMTP token)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = _env('EMAIL_HOST', 'smtp.protonmail.ch')
EMAIL_PORT = int(_env('EMAIL_PORT', '587'))
EMAIL_USE_TLS = _env('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_USE_SSL = _env('EMAIL_USE_SSL', 'false').lower() == 'true'
EMAIL_HOST_USER = _env('EMAIL_HOST_USER', 'narudzbe@opremazaribolov.ba')
EMAIL_HOST_PASSWORD = (
    _env('EMAIL_APP_PASSWORD') or _env('EMAIL_HOST_PASSWORD')
).replace(' ', '')
DEFAULT_FROM_EMAIL = _env('DEFAULT_FROM_EMAIL', 'narudzbe@opremazaribolov.ba')
SERVER_EMAIL = DEFAULT_FROM_EMAIL
ORDER_NOTIFICATION_EMAIL = _env(
    'ORDER_NOTIFICATION_EMAIL',
    'narudzbe@opremazaribolov.ba',
).strip().lower()
EMAIL_TIMEOUT = int(_env('EMAIL_TIMEOUT', '30'))
SITE_URL = _env('SITE_URL', 'https://www.opremazaribolov.ba').rstrip('/')
STORE_PHONE = _env('STORE_PHONE', '')
# Viber broj s kojeg se šalju loyalty kodovi za provjeru kupca (BA format 00… ili +…)
LOYALTY_VIBER_FROM_PHONE = _env('LOYALTY_VIBER_FROM_PHONE', '0038765152072')
MESSENGER_PAGE = _env('MESSENGER_PAGE', 'opremazaribolov.ba')
STORE_EMAIL = _env('STORE_EMAIL', 'narudzbe@opremazaribolov.ba')

# Meta (Facebook / Instagram) Pixel + Conversions API
META_PIXEL_ID = _env('META_PIXEL_ID', '27729172960012475')
META_ACCESS_TOKEN = _env('META_ACCESS_TOKEN', '')

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'account'
LOGOUT_REDIRECT_URL = 'home'

# Sync prema Loyalty Programu na Renderu (loyaltyprogram-jsg5.onrender.com)
SYNC_REMOTE_URL = _env('SYNC_REMOTE_URL', '').rstrip('/')
SYNC_API_KEY = _env('SYNC_API_KEY', '')
SYNC_TIMEOUT = int(_env('SYNC_TIMEOUT', '15'))
# Sync je omogućen ako su URL i KEY postavljeni.
# Render automatski postavlja neke varijable (npr. RENDER_EXTERNAL_HOSTNAME).
# Ako želiš, možeš postaviti RENDER=true u environment za custom logiku.
SYNC_ENABLED = bool(SYNC_REMOTE_URL and SYNC_API_KEY)

# Catalog Sync API — daj partneru ovaj ključ da vuče artikle/kategorije/brendove (read-only)
# Header: X-Api-Key: ...  ili  Authorization: Bearer ...
CATALOG_SYNC_API_KEY = _env('CATALOG_SYNC_API_KEY', '') or SYNC_API_KEY

# OLX.ba / Pik (isti API — profil CarpologijaBH)
OLX_API_TOKEN = _env('OLX_API_TOKEN', '')
OLX_CITY_ID = int(_env('OLX_CITY_ID', '77'))
OLX_COUNTRY_ID = int(_env('OLX_COUNTRY_ID', '49'))
OLX_DEFAULT_CATEGORY_ID = int(_env('OLX_DEFAULT_CATEGORY_ID', '1260'))

# Odoo import (XML-RPC, API ključ kao lozinka)
ODOO_URL = _env('ODOO_URL', '').rstrip('/')
ODOO_DB = _env('ODOO_DB', '')
ODOO_USERNAME = _env('ODOO_USERNAME', '')
ODOO_API_KEY = _env('ODOO_API_KEY', '')

# Cloudflare Turnstile (https://developers.cloudflare.com/turnstile/)
TURNSTILE_SITE_KEY = _env('TURNSTILE_SITE_KEY', '')
TURNSTILE_SECRET_KEY = _env('TURNSTILE_SECRET_KEY', '')

# IP adrese koje se NE broje u live analytics / pregled sajta (vlasnik, ured, …).
# Zarezom odvojeno, npr. LIVE_VISITOR_EXCLUDE_IPS=1.2.3.4,5.6.7.8
# Kad se staff/superuser uloguje, njegov IP se automatski pamti (cache) i isključuje.
_exclude_ips_raw = _env('LIVE_VISITOR_EXCLUDE_IPS', '127.0.0.1,::1')
LIVE_VISITOR_EXCLUDE_IPS = tuple(
    ip.strip() for ip in _exclude_ips_raw.split(',') if ip.strip()
)

# Zaštita sajta dok je u pripremi (SITE_PREP_ENABLED=false kad završiš lansiranje)
SITE_PREP_PASSWORD = _env('SITE_PREP_PASSWORD', 'OpremaZaribolov2026')
_site_prep_env = _env('SITE_PREP_ENABLED', '').lower()
if _site_prep_env in ('false', '0', 'no'):
    SITE_PREP_ENABLED = False
elif _site_prep_env in ('true', '1', 'yes'):
    SITE_PREP_ENABLED = True
else:
    SITE_PREP_ENABLED = bool(SITE_PREP_PASSWORD)
SITE_PREP_SESSION_KEY = 'site_prep_unlocked'

# Lokalni runserver (DEBUG=True, npr. http://127.0.0.1:8000):
# bez site-prep lozinke i bez Cloudflare Turnstile — produkcija (DEBUG=False) ostaje zaštićena.
if DEBUG:
    SITE_PREP_ENABLED = False
    TURNSTILE_SITE_KEY = ''
    TURNSTILE_SECRET_KEY = ''