"""
Django settings for EcommerceProject project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file():
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        return {}
    values = {}
    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        values[key] = value
        os.environ[key] = value
    return values


_ENV_VALUES = _load_env_file()


def _env(key, default=''):
    value = _ENV_VALUES.get(key)
    if value is None:
        value = os.environ.get(key, default)
    return value or default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _env('SECRET_KEY', 'django-insecure-_73#1@hjsxhlmfx4+&85s10a(cyb9i*q7-28$_zpjz5vm&+0ek')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [
    h.strip() for h in _env('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if h.strip()
]

# Render specific: add the service hostname if provided
RENDER_EXTERNAL_HOSTNAME = _env('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Production security settings
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'EcommerceApp',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise for static files (must be right after SecurityMiddleware)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EcommerceProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'EcommerceApp' / 'template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'EcommerceApp.context_processors.nav_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'EcommerceProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use PostgreSQL on Render (via DATABASE_URL), fallback to SQLite for local dev
database_url = _env('DATABASE_URL')
if database_url:
    DATABASES = {
        'default': dj_database_url.config(
            default=database_url,
            conn_max_age=600,
            ssl_require=True,  # Render Postgres requires SSL
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 60,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'EcommerceApp' / 'static',
]

# WhiteNoise for efficient static file serving in production
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
# Local dev: ./media/
# On Render: use attached Disk (set RENDER_DISK_PATH in environment variables)
MEDIA_URL = 'media/'
render_disk_path = _env('RENDER_DISK_PATH', '')
if render_disk_path:
    MEDIA_ROOT = Path(render_disk_path) / 'media'
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# Ensure media directory exists (important for disk on Render)
try:
    MEDIA_ROOT.mkdir(parents=True, exist_ok=True)
except (PermissionError, OSError):
    # On Render the disk is mounted and writable.
    # Locally or in restricted envs we ignore.
    pass

# Email — unesite Gmail App Password u .env datoteku (EMAIL_APP_PASSWORD)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = _env('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(_env('EMAIL_PORT', '587'))
EMAIL_USE_TLS = _env('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_HOST_USER = _env('EMAIL_HOST_USER', 'sasabera1990@gmail.com')
EMAIL_HOST_PASSWORD = _env('EMAIL_APP_PASSWORD').replace(' ', '')
DEFAULT_FROM_EMAIL = _env('DEFAULT_FROM_EMAIL', 'sasabera1990@gmail.com')
ORDER_NOTIFICATION_EMAIL = _env('ORDER_NOTIFICATION_EMAIL', 'sasabera1990@gmail.com')
EMAIL_TIMEOUT = int(_env('EMAIL_TIMEOUT', '30'))
SITE_URL = _env('SITE_URL', 'https://opremazaribolov.ba').rstrip('/')
STORE_PHONE = _env('STORE_PHONE', '')
STORE_EMAIL = _env('STORE_EMAIL', 'sasabera1990@gmail.com')

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'account'
LOGOUT_REDIRECT_URL = 'home'

# Sync prema Loyalty Programu na Renderu (loyaltyprogram-jsg5.onrender.com)
SYNC_REMOTE_URL = _env('SYNC_REMOTE_URL', '').rstrip('/')
SYNC_API_KEY = _env('SYNC_API_KEY', '')
SYNC_TIMEOUT = int(_env('SYNC_TIMEOUT', '15'))
# Sync je omogućen ako su URL i KEY postavljeni.
# Na Renderu možeš koristiti RENDER=1 da promijeniš ponašanje ako treba.
SYNC_ENABLED = bool(SYNC_REMOTE_URL and SYNC_API_KEY)

# Odoo import (XML-RPC, API ključ kao lozinka)
ODOO_URL = _env('ODOO_URL', '').rstrip('/')
ODOO_DB = _env('ODOO_DB', '')
ODOO_USERNAME = _env('ODOO_USERNAME', '')
ODOO_API_KEY = _env('ODOO_API_KEY', '')

# Cloudflare Turnstile (https://developers.cloudflare.com/turnstile/)
TURNSTILE_SITE_KEY = _env('TURNSTILE_SITE_KEY', '')
TURNSTILE_SECRET_KEY = _env('TURNSTILE_SECRET_KEY', '')