from django.urls import path

from . import views
from . import views_catalog_api
from . import views_chat
from . import views_feed
from . import views_magacin
from . import views_site_prep
from . import views_sync

urlpatterns = [
    path('api/sync/korisnik/', views_sync.sync_korisnik_api, name='sync_korisnik_api'),
    path('api/sync/narudzba/', views_sync.sync_narudzba_api, name='sync_narudzba_api'),
    path('api/pretraga/', views.search_suggest, name='search_suggest'),

    # Live chat (kupac ↔ podrška)
    path('api/chat/config/', views_chat.chat_config, name='chat_config'),
    path('api/chat/', views_chat.chat_state, name='chat_state'),
    path('api/chat/guest/', views_chat.chat_guest_info, name='chat_guest_info'),
    path('api/chat/send/', views_chat.chat_send, name='chat_send'),
    path('api/chat/badge/', views_chat.chat_badge, name='chat_badge'),
    path('api/chat/poll/', views_chat.chat_poll, name='chat_poll'),
    path('api/chat/leave/', views_chat.chat_leave, name='chat_leave'),
    path('api/chat/add-product/', views_chat.chat_add_product, name='chat_add_product'),
    path('api/chat/staff/ping/', views_chat.chat_staff_ping, name='chat_staff_ping'),
    path('api/chat/staff/inbox/', views_chat.chat_staff_inbox, name='chat_staff_inbox'),
    path(
        'api/chat/staff/products/',
        views_chat.chat_staff_product_search,
        name='chat_staff_product_search',
    ),
    path(
        'api/chat/staff/<int:pk>/',
        views_chat.chat_staff_conversation,
        name='chat_staff_conversation',
    ),
    path(
        'api/chat/staff/<int:pk>/send/',
        views_chat.chat_staff_send,
        name='chat_staff_send',
    ),
    path(
        'api/chat/staff/<int:pk>/send-product/',
        views_chat.chat_staff_send_product,
        name='chat_staff_send_product',
    ),
    path(
        'api/chat/staff/<int:pk>/read/',
        views_chat.chat_staff_read,
        name='chat_staff_read',
    ),
    path(
        'api/chat/staff/<int:pk>/close/',
        views_chat.chat_staff_close,
        name='chat_staff_close',
    ),

    # Catalog Sync API — partner vuče katalog (read-only, API key)
    path('api/v1/ping/', views_catalog_api.catalog_api_ping, name='catalog_api_ping'),
    path('api/v1/products/', views_catalog_api.catalog_api_products, name='catalog_api_products'),
    path(
        'api/v1/products/<slug:slug>/',
        views_catalog_api.catalog_api_product_detail,
        name='catalog_api_product_detail',
    ),
    path('api/v1/categories/', views_catalog_api.catalog_api_categories, name='catalog_api_categories'),
    path('api/v1/brands/', views_catalog_api.catalog_api_brands, name='catalog_api_brands'),

    path('facebook-feed.xml', views_feed.facebook_feed, name='facebook_feed'),

    path('priprema-pristup/', views_site_prep.site_prep_unlock, name='site_prep_unlock'),
    path('', views.home, name='home'),
    path('api/newsletter/', views.newsletter_subscribe, name='newsletter_subscribe'),
    path('o-nama/', views.about_us, name='about_us'),
    path('nacin-placanja/', views.payment_methods, name='payment_methods'),
    path('vlog/', views.vlog_list, name='vlog_list'),
    path('vlog/<slug:slug>/', views.vlog_detail, name='vlog_detail'),
    path('kategorija/<slug:slug>/', views.category_detail, name='category'),
    path('artikal/<slug:slug>/', views.product_detail, name='product_detail'),
    path('artikal/<slug:slug>/brza-izmjena/', views.staff_product_quick_edit, name='staff_product_quick_edit'),
    path('artikal/<slug:slug>/olx-objavi/', views.staff_post_product_olx, name='staff_post_product_olx'),
    path('artikal/<slug:slug>/dodaj/', views.add_to_cart, name='add_to_cart'),
    path('upsell/<int:offer_id>/<int:product_id>/dodaj/', views.add_upsell_to_cart, name='add_upsell_to_cart'),
    path('upsell/odbaci/', views.dismiss_upsell_popup, name='dismiss_upsell_popup'),
    path('korpa/', views.cart_view, name='cart'),
    path('korpa/azuriraj/', views.update_cart, name='update_cart'),
    path('korpa/kupon/', views.apply_coupon, name='apply_coupon'),
    path('korpa/kupon/ukloni/', views.remove_coupon, name='remove_coupon'),
    path('korpa/ukloni/<str:key>/', views.remove_from_cart, name='remove_from_cart'),
    path('korpa/podsjetnik/primijeni/', views.cart_recovery_apply, name='cart_recovery_apply'),
    path('korpa/podsjetnik/zatvori/', views.cart_recovery_dismiss, name='cart_recovery_dismiss'),
    path('korpa/exit/zatvori/', views.cart_exit_dismiss, name='cart_exit_dismiss'),
    path('korpa/podsjetnik-exit/zatvori/', views.cart_abandon_exit_dismiss, name='cart_abandon_exit_dismiss'),
    path('ponuda/dodaj/', views.live_visitor_offer_add, name='live_visitor_offer_add'),
    path('ponuda/aktiviraj/', views.live_visitor_offer_activate, name='live_visitor_offer_activate'),
    path('ponuda/zatvori/', views.live_visitor_offer_dismiss, name='live_visitor_offer_dismiss'),
    path('ponuda/status/', views.live_visitor_offer_poll, name='live_visitor_offer_poll'),
    path('preporuka/dodaj/', views.browse_interest_offer_add, name='browse_interest_offer_add'),
    path('preporuka/zatvori/', views.browse_interest_offer_dismiss, name='browse_interest_offer_dismiss'),
    path('ai-dwell/aktiviraj/', views.ai_dwell_activate, name='ai_dwell_activate'),
    path('savjetnik/', views.fishing_advisor_step, name='fishing_advisor'),
    path('savjetnik/kupi-set/', views.fishing_advisor_buy_set, name='fishing_advisor_buy_set'),
    path('drustveni-dokaz/', views.social_proof_poll, name='social_proof_poll'),
    path('online-nagrada/otkrij/', views.online_gift_reveal, name='online_gift_reveal'),
    path('online-nagrada/zatvori/', views.online_gift_dismiss, name='online_gift_dismiss'),
    path('online-nagrada/status/', views.online_gift_poll, name='online_gift_poll'),
    path('uzivo/prisutan/', views.live_visitor_heartbeat, name='live_visitor_heartbeat'),
    path('uzivo/odlazak/', views.live_visitor_leave, name='live_visitor_leave'),
    path('uzivo/javno/', views.public_online_visitors, name='public_online_visitors'),
    path('uzivo/skoro-korpa/', views.almost_cart_track, name='almost_cart_track'),
    path('narudzba/', views.checkout, name='checkout'),
    path('narudzba/uspjeh/<str:broj>/', views.order_success, name='order_success'),
    path('prijava/', views.login_view, name='login'),
    path('registracija/', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('odjava/', views.logout_view, name='logout'),
    path('nalog/', views.account, name='account'),
    path('nalog/narudzba/<str:broj>/', views.account_order_detail, name='account_order_detail'),
    path('nalog/provjera-narudzbi/', views.staff_order_lookup, name='staff_order_lookup'),
    path('nalog/provjera-narudzbi/<str:broj>/', views.staff_order_detail, name='staff_order_detail'),
    path('nalog/provjera-narudzbi/<str:broj>/stampaj/', views.staff_order_print, name='staff_order_print'),
    path(
        'nalog/provjera-narudzbi/<str:broj>/odstampano/',
        views.staff_order_mark_printed,
        name='staff_order_mark_printed',
    ),
    path('nalog/provjera-narudzbi/<str:broj>/pakovanje/', views.staff_order_packing, name='staff_order_packing'),
    path(
        'nalog/provjera-narudzbi/<str:broj>/brza-posta/',
        views.staff_order_brza_posta,
        name='staff_order_brza_posta',
    ),


    path('nalog/admin/', views.staff_admin_panel, name='staff_admin_panel'),
    path('nalog/pregled-sajta/', views.staff_site_overview, name='staff_site_overview'),
    path('nalog/edit-mode/', views.staff_toggle_edit_mode, name='staff_toggle_edit_mode'),
    path('nalog/site-edit/', views.staff_site_edit_save, name='staff_site_edit_save'),
    path('nalog/aktiviraj-korisnika/', views.staff_activate_user, name='staff_activate_user'),
    path('nalog/aktivne-korpe/', views.staff_active_carts, name='staff_active_carts'),
    path('nalog/magacin/', views_magacin.magacin_home, name='staff_magacin'),
    path('nalog/magacin/pregled/', views_magacin.magacin_pregled, name='staff_magacin_pregled'),
    path('nalog/magacin/artikli/', views_magacin.magacin_artikli, name='staff_magacin_artikli'),
    path('nalog/magacin/artikli/brzi-unos/', views_magacin.magacin_brzi_unos, name='staff_magacin_brzi_unos'),
    path(
        'nalog/magacin/artikli/brzi-unos/<int:product_id>/',
        views_magacin.magacin_brzi_unos_aktivacija,
        name='staff_magacin_brzi_unos_aktivacija',
    ),
    path('nalog/magacin/artikli/lookup/', views_magacin.magacin_artikli_lookup, name='staff_magacin_artikli_lookup'),
    path('nalog/magacin/stampa-cijena/', views_magacin.magacin_stampa_cijena, name='staff_magacin_stampa_cijena'),
    path('nalog/magacin/stampa-cijena/ista/', views_magacin.magacin_stampa_cijena_ista, name='staff_magacin_stampa_cijena_ista'),
    path(
        'nalog/magacin/stampa-cijena/razlicite/',
        views_magacin.magacin_stampa_cijena_razlicite,
        name='staff_magacin_stampa_cijena_razlicite',
    ),
    path(
        'nalog/magacin/stampa-cijena/print/',
        views_magacin.magacin_stampa_cijena_print,
        name='staff_magacin_stampa_cijena_print',
    ),
    path('nalog/magacin/artikli/<int:pk>/', views_magacin.magacin_artikal, name='staff_magacin_artikal'),
    path(
        'nalog/magacin/artikli/<int:pk>/stampa/',
        views_magacin.magacin_artikal_stampa,
        name='staff_magacin_artikal_stampa',
    ),
    path('nalog/magacin/artikli/<int:pk>/izmjena/', views_magacin.magacin_artikal_izmjena, name='staff_magacin_artikal_izmjena'),
    path('nalog/magacin/artikli/<int:pk>/istorija/', views_magacin.magacin_istorija, name='staff_magacin_istorija'),
    path('nalog/magacin/lokacije/lookup/', views_magacin.magacin_lokacije_lookup, name='staff_magacin_lokacije_lookup'),
    path('nalog/magacin/lokacije/', views_magacin.magacin_lokacije, name='staff_magacin_lokacije'),
    path('nalog/magacin/zalihe/', views_magacin.magacin_zalihe, name='staff_magacin_zalihe'),
    path('nalog/magacin/transferi/', views_magacin.magacin_transferi, name='staff_magacin_transferi'),
    path('nalog/magacin/popis/', views_magacin.magacin_popis, name='staff_magacin_popis'),
    path('nalog/magacin/popis/<int:pk>/', views_magacin.magacin_popis, name='staff_magacin_popis_detail'),
    path('nalog/magacin/popis/stampa/', views_magacin.magacin_popis_stampa, name='staff_magacin_popis_stampa'),
    path('nalog/magacin/narudzbe/', views_magacin.magacin_narudzbe, name='staff_magacin_narudzbe'),
    path('nalog/magacin/narudzbe/nova/', views_magacin.magacin_narudzba_nova, name='staff_magacin_narudzba_nova'),
    path('nalog/magacin/narudzbe/vp/', views_magacin.magacin_vp_narudzba, name='staff_magacin_vp_narudzba'),
    path('nalog/magacin/kupci/', views_magacin.magacin_kupci, name='staff_magacin_kupci'),
    path('nalog/magacin/kupci/lookup/', views_magacin.magacin_kupci_lookup, name='staff_magacin_kupci_lookup'),
    path('nalog/magacin/kupci/sacuvaj/', views_magacin.magacin_kupci_save, name='staff_magacin_kupci_save'),
    path('nalog/magacin/narudzbe/stampa/', views_magacin.magacin_narudzbe_stampa, name='staff_magacin_narudzbe_stampa'),
    path('nalog/magacin/narudzbe/packing/', views_magacin.magacin_narudzbe_packing, name='staff_magacin_narudzbe_packing'),
    path('nalog/magacin/narudzbe/validiraj/', views_magacin.magacin_narudzbe_validiraj, name='staff_magacin_narudzbe_validiraj'),
    path(
        'nalog/magacin/narudzbe/odstampano/',
        views_magacin.magacin_narudzbe_mark_printed,
        name='staff_magacin_narudzbe_mark_printed',
    ),
    path('nalog/magacin/pakovanje/', views_magacin.magacin_pakovanje, name='staff_magacin_pakovanje'),
    path('nalog/magacin/pakuj/', views_magacin.magacin_pakuj, name='staff_magacin_pakuj'),
    path('nalog/magacin/pakuj/provjera/', views_magacin.magacin_pakuj_provjera, name='staff_magacin_pakuj_provjera'),
    path('nalog/magacin/pakuj/sken/', views_magacin.magacin_pakuj_sken, name='staff_magacin_pakuj_sken'),
    path(
        'nalog/magacin/pakuj/<str:broj>/oslobodi/',
        views_magacin.magacin_pakuj_oslobodi,
        name='staff_magacin_pakuj_oslobodi',
    ),
    path(
        'nalog/magacin/pakuj/<str:broj>/stampaj-zapakovano/',
        views_magacin.magacin_pakuj_stampaj_zapakovano,
        name='staff_magacin_pakuj_stampaj_zapakovano',
    ),
    path(
        'nalog/magacin/narudzbe/<str:broj>/barkod.png',
        views_magacin.magacin_narudzba_barkod,
        name='staff_magacin_narudzba_barkod',
    ),
    path('nalog/magacin/pakuj/<str:broj>/', views_magacin.magacin_pakuj_detail, name='staff_magacin_pakuj_detail'),
    path('nalog/magacin/uvoz/', views_magacin.magacin_uvoz, name='staff_magacin_uvoz'),
    path('nalog/magacin/uvoz/novi/', views_magacin.magacin_uvoz_novi, name='staff_magacin_uvoz_novi'),
    path('nalog/magacin/uvoz/<int:pk>/', views_magacin.magacin_uvoz_detail, name='staff_magacin_uvoz_detail'),
    path('nalog/magacin/nivelacije/', views_magacin.magacin_nivelacije, name='staff_magacin_nivelacije'),
    path('nalog/magacin/dobavljaci/', views_magacin.magacin_dobavljaci, name='staff_magacin_dobavljaci'),
    path('nalog/magacin/izvjestaji/', views_magacin.magacin_izvjestaji, name='staff_magacin_izvjestaji'),
    path('nalog/magacin/podesavanja/', views_magacin.magacin_podesavanja, name='staff_magacin_podesavanja'),
    path('nalog/magacin/sync/', views_magacin.magacin_sync, name='staff_magacin_sync'),
    path('nalog/magacin/sync/istorija/', views_magacin.magacin_sync_istorija, name='staff_magacin_sync_istorija'),
    path('nalog/uzivo-analitika/', views.staff_live_analytics, name='staff_live_analytics'),
    path('nalog/uzivo-analitika/podaci/', views.staff_live_analytics_data, name='staff_live_analytics_data'),
    path('nalog/uzivo-obavijesti/', views.staff_site_events_poll, name='staff_site_events_poll'),
    path('nalog/uzivo-analitika/ponuda/', views.staff_send_live_offer, name='staff_send_live_offer'),
    path(
        'nalog/uzivo-analitika/registracija/',
        views.staff_send_registration_invite,
        name='staff_send_registration_invite',
    ),
    path(
        'nalog/uzivo-analitika/nagrada/',
        views.staff_push_online_gift,
        name='staff_push_online_gift',
    ),
    path(
        'nalog/uzivo-analitika/nagrada-auto/',
        views.staff_set_online_gift_automatic,
        name='staff_set_online_gift_automatic',
    ),
    path('nalog/pretraga-artikala/', views.staff_product_search, name='staff_product_search'),

    path('nalog/loyalty/', views.staff_loyalty_system, name='staff_loyalty_system'),
    path('nalog/loyalty/clan/<str:kod>/', views.staff_loyalty_member, name='staff_loyalty_member'),
    path(
        'nalog/loyalty/kartica/<int:card_id>/slika.png',
        views.staff_loyalty_card_image,
        name='staff_loyalty_card_image',
    ),
    # Javni PNG (token) — kupac otvara sliku kartice iz WhatsApp/Viber poruke
    path(
        'loyalty/kartica/<int:card_id>/<str:token>.png',
        views.public_loyalty_card_image,
        name='public_loyalty_card_image',
    ),
    path(
        'nalog/loyalty/kartica/<int:card_id>/qr.png',
        views.staff_loyalty_card_qr,
        name='staff_loyalty_card_qr',
    ),
    path(
        'nalog/loyalty/kartica/<int:card_id>/barkod.png',
        views.staff_loyalty_card_barcode,
        name='staff_loyalty_card_barcode',
    ),
    path('nalog/online-narudzbe/', views.staff_online_orders, name='staff_online_orders'),
    path('nalog/poklon-vaucer/', views.staff_gift_voucher, name='staff_gift_voucher'),
    path('nalog/poklon-vaucer/stampa/', views.staff_gift_voucher_print, name='staff_gift_voucher_print'),
    path('nalog/uvoz/', views.staff_uvoz, name='staff_uvoz'),
    path('nalog/uvoz/<int:pk>/', views.staff_uvoz_detail, name='staff_uvoz_detail'),
    path('nalog/olx-poruke/', views.staff_olx_messages, name='staff_olx_messages'),
    path('nalog/pretraga-kategorija/', views.staff_category_search, name='staff_category_search'),
    path('nalog/pretraga-brendova/', views.staff_brand_search, name='staff_brand_search'),
    path('nalog/pretraga-tagova/', views.staff_tag_search, name='staff_tag_search'),
]