# Generated by Django 6.0.6 on 2026-06-27 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=200)),
                ('podnaslov', models.CharField(blank=True, max_length=300)),
                ('slika', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True)),
                ('tekst_dugmeta', models.CharField(default='Shop', max_length=50)),
                ('sekundarno_dugme', models.CharField(blank=True, max_length=50)),
                ('sekundarni_link', models.URLField(blank=True)),
                ('tip', models.CharField(choices=[('hero', 'Hero Carousel'), ('featured', 'Featured Kartica'), ('spotlight', 'Spotlight')], default='hero', max_length=20)),
                ('siroka_kartica', models.BooleanField(default=False, help_text='Samo za Featured tip')),
                ('redoslijed', models.PositiveIntegerField(default=0)),
                ('aktivan', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banneri',
                'ordering': ['redoslijed', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Brend',
                'verbose_name_plural': 'Brendovi',
                'ordering': ['naziv'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Kategorija',
                'verbose_name_plural': 'Kategorije',
                'ordering': ['naziv'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sifra', models.CharField(max_length=50, unique=True, verbose_name='Šifra')),
                ('barkod', models.CharField(blank=True, max_length=50, verbose_name='Barkod')),
                ('slika', models.ImageField(upload_to='products/')),
                ('stanje', models.PositiveIntegerField(default=0, verbose_name='Stanje')),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('akcijska_cijena', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Akcijska cijena')),
                ('prikazi_na_pocetnoj', models.BooleanField(default=True, verbose_name='Prikaži na početnoj')),
                ('aktivan', models.BooleanField(default=True)),
                ('kreiran', models.DateTimeField(auto_now_add=True)),
                ('azuriran', models.DateTimeField(auto_now=True)),
                ('brend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikli', to='EcommerceApp.brand')),
                ('kategorija', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikli', to='EcommerceApp.category')),
            ],
            options={
                'verbose_name': 'Artikal',
                'verbose_name_plural': 'Artikli',
                'ordering': ['-kreiran'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('slika', models.ImageField(upload_to='products/variations/')),
                ('cijena', models.DecimalField(blank=True, decimal_places=2, help_text='Ostavite prazno za cijenu artikla', max_digits=10, null=True)),
                ('redoslijed', models.PositiveIntegerField(default=0)),
                ('artikal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varijacije', to='EcommerceApp.product')),
            ],
            options={
                'verbose_name': 'Varijacija',
                'verbose_name_plural': 'Varijacije',
                'ordering': ['redoslijed', 'id'],
            },
        ),
    ]
