# Generated by Django 6.0.6 on 2026-06-27 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0002_productvariation_sifra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['redoslijed', 'naziv'], 'verbose_name': 'Kategorija', 'verbose_name_plural': 'Kategorije'},
        ),
        migrations.AddField(
            model_name='category',
            name='aktivan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='prikazi_u_meniju',
            field=models.BooleanField(default=True, verbose_name='Prikaži u meniju'),
        ),
        migrations.AddField(
            model_name='category',
            name='redoslijed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='roditelj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podkategorije', to='EcommerceApp.category', verbose_name='Roditeljska kategorija'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='tip',
            field=models.CharField(choices=[('hero', 'Hero Carousel'), ('grid', 'Grid Kartica (2x2 ispod Hero)'), ('featured', 'Featured Kartica'), ('spotlight', 'Spotlight')], default='hero', max_length=20),
        ),
    ]
