# Generated by Django 6.0.6 on 2026-06-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0003_alter_category_options_category_aktivan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slika',
            field=models.ImageField(blank=True, help_text='Prikazuje se umjesto naziva. Automatski se skalira na 200×48px.', null=True, upload_to='brands/', verbose_name='Logo slika'),
        ),
        migrations.AddField(
            model_name='product',
            name='opis',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
    ]
