# Generated by Django 6.0.6 on 2026-06-27 15:12

from django.db import migrations, models


def sync_na_stanju_from_stanje(apps, schema_editor):
    Product = apps.get_model('EcommerceApp', 'Product')
    for product in Product.objects.all():
        product.na_stanju = product.stanje > 0
        product.save(update_fields=['na_stanju'])


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0004_brand_slika_product_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='na_stanju',
            field=models.BooleanField(default=True, verbose_name='Na stanju'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='na_stanju',
            field=models.BooleanField(default=True, verbose_name='Na stanju'),
        ),
        migrations.RunPython(sync_na_stanju_from_stanje, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='sifra',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Šifra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stanje',
            field=models.PositiveIntegerField(default=0, verbose_name='Količina'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='sifra',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Šifra'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='products/variations/'),
        ),
    ]
