# Generated by Django 6.0.6 on 2026-06-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0005_product_optional_fields_na_stanju'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Prikazuje se u headeru umjesto teksta. Automatski se skalira na max 200×36px.', null=True, upload_to='site/', verbose_name='Logo sajta')),
            ],
            options={
                'verbose_name': 'Postavke sajta',
                'verbose_name_plural': 'Postavke sajta',
            },
        ),
    ]
