# Generated by Django 6.0.6 on 2026-06-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0006_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='akcijska_cijena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcionalno — samo za ovu varijaciju. Inače vrijedi akcija artikla.', max_digits=10, null=True, verbose_name='Akcijska cijena'),
        ),
    ]
