# Generated by Django 6.0.6 on 2026-06-27 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0007_variation_akcijska_cijena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj', models.CharField(editable=False, max_length=20, unique=True)),
                ('ime_prezime', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=30)),
                ('adresa', models.CharField(max_length=300)),
                ('grad', models.CharField(max_length=100)),
                ('postanski_broj', models.CharField(blank=True, max_length=20)),
                ('napomena', models.TextField(blank=True)),
                ('ukupno', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('nova', 'Nova'), ('potvrdjena', 'Potvrđena'), ('poslana', 'Poslana'), ('zavrsena', 'Završena'), ('otkazana', 'Otkazana')], default='nova', max_length=20)),
                ('kreirana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Narudžba',
                'verbose_name_plural': 'Narudžbe',
                'ordering': ['-kreirana'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Prikazuje se u headeru umjesto teksta. Pozadina se uklanja, čuva se kao transparentni PNG (max 640×128px).', null=True, upload_to='site/', verbose_name='Logo sajta'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('sifra', models.CharField(blank=True, max_length=50)),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kolicina', models.PositiveIntegerField(default=1)),
                ('artikal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EcommerceApp.product')),
                ('narudzba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='EcommerceApp.order')),
                ('varijacija', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EcommerceApp.productvariation')),
            ],
            options={
                'verbose_name': 'Stavka narudžbe',
                'verbose_name_plural': 'Stavke narudžbe',
            },
        ),
    ]
