# Generated by Django 6.0.6 on 2026-06-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0008_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_naziv',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='varijacija_naziv',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
