# Generated by Django 6.0.6 on 2026-06-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0019_popup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popup',
            name='naslov',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='popust_km',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='popust_postotak',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='tekst',
        ),
        migrations.AddField(
            model_name='popup',
            name='slika',
            field=models.ImageField(default=1, help_text='Glavna slika pop-upa. Dugme će biti ispod slike.', upload_to='popups/', verbose_name='Slika'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='popup',
            name='link_dugmeta',
            field=models.CharField(blank=True, help_text='Npr. /registracija/ ili puni URL. Prazno = /registracija/.', max_length=300, verbose_name='Link dugmeta'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='tekst_dugmeta',
            field=models.CharField(default='Saznaj više', help_text='Tekst koji se prikazuje na dugmetu ispod slike.', max_length=50, verbose_name='Naziv dugmeta'),
        ),
    ]
