# Generated by Django 6.0.6 on 2026-06-28 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0020_remove_popup_naslov_remove_popup_popust_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpsellOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(help_text='Samo za prepoznavanje u adminu.', max_length=100, verbose_name='Interni naziv')),
                ('popust_postotak', models.DecimalField(blank=True, decimal_places=2, help_text='Opcionalno - popust na cijenu ponuđenih artikala.', max_digits=5, null=True, verbose_name='Popust (%)')),
                ('popust_km', models.DecimalField(blank=True, decimal_places=2, help_text='Opcionalno - fiksni popust u KM na ponuđene artikle.', max_digits=10, null=True, verbose_name='Popust (KM)')),
                ('aktivan', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('redoslijed', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('ponuda_artikli', models.ManyToManyField(help_text='Odaberite jedan ili više artikala koji će se ponuditi.', to='EcommerceApp.product', verbose_name='Artikli u ponudi (upsell)')),
                ('trigger_artikal', models.ForeignKey(blank=True, help_text='Ako se ovaj artikal doda u korpu, pokreni ponudu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upsell_triggeri', to='EcommerceApp.product', verbose_name='Trigger artikal')),
                ('trigger_kategorija', models.ForeignKey(blank=True, help_text='Ako se artikal iz ove kategorije doda u korpu, pokreni ponudu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upsell_triggeri', to='EcommerceApp.category', verbose_name='Trigger kategorija')),
            ],
            options={
                'verbose_name': 'Upsell ponuda',
                'verbose_name_plural': 'Upsell ponude',
                'ordering': ['redoslijed', '-id'],
            },
        ),
    ]
