# Generated by Django 6.0.6 on 2026-06-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0021_upselloffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='upselloffer',
            name='naslov_ponude',
            field=models.CharField(default='Specijalna ponuda za vas!', help_text='Možeš izmijeniti tekst "Specijalna ponuda za vas!"', max_length=100, verbose_name='Naslov u popupu'),
        ),
        migrations.AddField(
            model_name='upselloffer',
            name='opis_ponude',
            field=models.CharField(default='Dodajte u korpu sa dodatnim popustom', help_text='Možeš izmijeniti tekst "Dodajte u korpu sa dodatnim popustom"', max_length=200, verbose_name='Opis u popupu'),
        ),
    ]
