# Generated by Django 6.0.6 on 2026-06-28 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0022_add_upsell_popup_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kategorija',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikli', to='EcommerceApp.category'),
        ),
    ]
