# Generated by Django 6.0.6 on 2026-06-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0023_product_kategorija_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='upselloffer',
            name='baner_slika',
            field=models.ImageField(blank=True, help_text='Za prikaz u korpi — preporučeno široko i nisko (npr. 1200×200 px).', null=True, upload_to='upsell/', verbose_name='Baner slika'),
        ),
        migrations.AddField(
            model_name='upselloffer',
            name='prikaz',
            field=models.CharField(choices=[('popup', 'Popup'), ('banner_iznad', 'Baner iznad artikala u korpi'), ('banner_ispod', 'Baner ispod "Nastavi na narudžbu"')], default='popup', max_length=20, verbose_name='Način prikaza'),
        ),
        migrations.AddField(
            model_name='upselloffer',
            name='tekst_dugmeta',
            field=models.CharField(default='Dodaj u korpu', max_length=50, verbose_name='Tekst dugmeta'),
        ),
    ]
