# Generated by Django 6.0.6 on 2026-06-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0024_upsell_banner_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upselloffer',
            name='baner_slika',
            field=models.ImageField(blank=True, help_text='Opcionalno — preporučeno široko i nisko (npr. 1200×200 px).', null=True, upload_to='upsell/', verbose_name='Baner slika'),
        ),
        migrations.AlterField(
            model_name='upselloffer',
            name='naziv',
            field=models.CharField(blank=True, default='', help_text='Opcionalno — samo za prepoznavanje u adminu.', max_length=100, verbose_name='Interni naziv'),
        ),
        migrations.AlterField(
            model_name='upselloffer',
            name='ponuda_artikli',
            field=models.ManyToManyField(blank=True, help_text='Opcionalno — artikli koji se nude u popupu ili na baneru u korpi.', to='EcommerceApp.product', verbose_name='Artikli za prikaz'),
        ),
    ]
