# Generated by Django 6.0.6 on 2026-06-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0025_upsell_optional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upselloffer',
            name='prikaz',
            field=models.CharField(choices=[('popup', 'Popup'), ('banner_iznad', 'Baner iznad artikala u korpi'), ('banner_ispod', 'Baner ispod "Nastavi na narudžbu"'), ('checkout', 'Checkout — poslednja šansa')], default='banner_iznad', max_length=20, verbose_name='Gdje prikazati'),
        ),
    ]
