# Generated by Django 6.0.6 on 2026-06-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0026_upsell_checkout_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='akcija_do',
            field=models.DateField(blank=True, help_text='Opcionalno. Prazno = akcija bez roka. Nakon ovog datuma artikal više nije na akciji.', null=True, verbose_name='Akcija važi do'),
        ),
    ]
