# Generated by Django 6.0.6 on 2026-06-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0027_product_akcija_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Opcionalno. Kratak opis za Google i društvene mreže.', max_length=160, verbose_name='Meta opis'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Opcionalno. Ako ostaviš prazno koristi se naziv kategorije.', max_length=70, verbose_name='SEO naslov'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Opcionalno. Opis koji se prikazuje u pretragama i kad se dijeli link.', max_length=160, verbose_name='Meta opis'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Opcionalno. Ako ostaviš prazno koristi se naziv artikla.', max_length=70, verbose_name='SEO naslov'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Preporučeno do 155-160 znakova. Prikazuje se u Google rezultatima.', max_length=160, verbose_name='Meta opis (početna)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Preporučeno 1200×630px ili veća. Prikazuje se kad se link dijeli na Facebooku, WhatsAppu itd.', null=True, upload_to='site/', verbose_name='Social share slika (OG image)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Preporučeno 50-60 znakova. Ostavi prazno za default.', max_length=70, verbose_name='SEO naslov (početna)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slika',
            field=models.ImageField(blank=True, help_text='Prikazuje se umjesto naziva. Automatski se skalira na 200×48px (logo popunjava 80% prostora).', null=True, upload_to='brands/', verbose_name='Logo slika'),
        ),
    ]
