# Generated by Django 6.0.6 on 2026-06-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0028_add_seo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Opcionalno — ostavi prazno za automatski opis koji počinje nazivom artikla.', max_length=160, verbose_name='Meta opis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Opcionalno — ostavi prazno za automatski (naziv artikla).', max_length=70, verbose_name='SEO naslov'),
        ),
    ]
