# Generated by Django 6.0.6 on 2026-06-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0029_alter_product_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redoslijed', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('aktivan', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('artikal', models.ForeignKey(
                    limit_choices_to={'aktivan': True},
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='istaknuti_na_pocetnoj',
                    to='EcommerceApp.product',
                    verbose_name='Artikal',
                )),
            ],
            options={
                'verbose_name': 'Istaknuti artikal (početna)',
                'verbose_name_plural': 'Istaknuti artikli (početna)',
                'ordering': ['redoslijed', 'id'],
            },
        ),
    ]