# Generated by Django 6.0.6 on 2026-06-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0030_homefeaturedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='homefeaturedproduct',
            name='postavke',
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='istaknuti_artikli',
                to='EcommerceApp.sitesettings',
            ),
        ),
        migrations.AlterField(
            model_name='homefeaturedproduct',
            name='artikal',
            field=models.ForeignKey(
                limit_choices_to={'aktivan': True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name='istaknuti_na_pocetnoj',
                to='EcommerceApp.product',
                verbose_name='Postojeći artikal',
            ),
        ),
    ]