# Generated by Django 6.0.6 on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0031_homefeaturedproduct_postavke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.CharField(
                blank=True,
                help_text='Npr. /kategorija/ ili https://... Klik na banner vodi na ovaj link.',
                max_length=300,
                verbose_name='Link',
            ),
        ),
        migrations.AlterField(
            model_name='banner',
            name='naslov',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sekundarni_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='banner',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='tekst_dugmeta',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]