# Generated by Django 6.0.6 on 2026-06-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0032_banner_optional_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(help_text='Prikazuje se ispod slike na početnoj.', max_length=200, verbose_name='Naslov')),
                ('slika', models.ImageField(help_text='Thumbnail na početnoj. Preporučeno 4:3 ili kvadrat.', upload_to='vlogs/', verbose_name='Slika')),
                ('sadrzaj', models.TextField(help_text='Tekst vloga u HTML-u. Za link: <a href="/putanja/">tekst</a> ili puni URL.', verbose_name='Sadržaj')),
                ('redoslijed', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('aktivan', models.BooleanField(default=True, verbose_name='Aktivan')),
            ],
            options={
                'verbose_name': 'Vlog (početna)',
                'verbose_name_plural': 'Vlogovi (početna)',
                'ordering': ['redoslijed', '-id'],
            },
        ),
    ]
