# Generated by Django 6.0.6 on 2026-06-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0034_homevlog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homevlog',
            options={'ordering': ['redoslijed', '-id'], 'verbose_name': 'Vlog', 'verbose_name_plural': 'Vlogovi'},
        ),
        migrations.AlterField(
            model_name='homevlog',
            name='naslov',
            field=models.CharField(help_text='Prikazuje se ispod slike na početnoj.', max_length=200, verbose_name='Naziv'),
        ),
        migrations.AlterField(
            model_name='homevlog',
            name='sadrzaj',
            field=models.TextField(help_text='Puni tekst koji se prikazuje kad korisnik otvori vlog. Može HTML: <p>, <a href="/...">link</a>.', verbose_name='Opis vloga'),
        ),
        migrations.AlterField(
            model_name='homevlog',
            name='slika',
            field=models.ImageField(help_text='Prikazuje se na početnoj (3 u redu). Preporučeno široka slika, npr. 1200×480 px.', upload_to='vlogs/', verbose_name='Slika'),
        ),
    ]
