# Generated by Django 6.0.6 on 2026-06-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0036_productkarakteristika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='opis',
            field=models.TextField(blank=True, help_text='Prikazuje se na stranici artikla lijevo od karakteristika.', verbose_name='Opis'),
        ),
    ]
