# Generated by Django 6.0.6 on 2026-06-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0038_remove_productkarakteristika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='tip',
            field=models.CharField(choices=[('hero', 'Hero Carousel'), ('grid', 'Grid Kartica (3 u redu ispod Hero)'), ('featured', 'Featured Kartica'), ('spotlight', 'Spotlight')], default='hero', max_length=20),
        ),
    ]
