# Generated by Django 6.0.6 on 2026-07-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0049_alter_banner_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='tip',
            field=models.CharField(choices=[('hero', 'Hero Carousel'), ('grid', 'Grid Kartica (4×2 ispod Hero, 8 desktop / 6 mobilni)'), ('featured', 'Featured Kartica'), ('spotlight', 'Spotlight')], default='hero', max_length=20),
        ),
    ]
