# Generated by Django 6.0.6 on 2026-07-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0051_alter_product_slug_barkod'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='akcija_postotak',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcionalno — automatski umanjuje redovnu cijenu za ovaj postotak.', max_digits=5, null=True, verbose_name='Popust (%)'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='akcija_postotak',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcionalno — umanjuje cijenu ove varijacije za ovaj postotak.', max_digits=5, null=True, verbose_name='Popust (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='akcijska_cijena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ručni iznos. Ili ostavite prazno i unesite popust (%) ispod.', max_digits=10, null=True, verbose_name='Akcijska cijena'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='akcijska_cijena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ručni iznos za varijaciju. Ili unesite popust (%) ispod.', max_digits=10, null=True, verbose_name='Akcijska cijena'),
        ),
    ]
