# Generated by Django 6.0.6 on 2026-07-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0052_product_akcija_postotak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homevlog',
            name='slika',
            field=models.ImageField(help_text='Upload: AVIF max 18KB + responsive 180/280/360w. Prikaz na početnoj (3 u redu) i stranici vloga.', upload_to='vlogs/', verbose_name='Slika'),
        ),
    ]
