# Generated by Django 6.0.6 on 2026-07-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0054_banner_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Prikazuje se u tabu preglednika i kao prečica na mobilnom. Automatski se skalira na 32×32px PNG.', null=True, upload_to='site/', verbose_name='Ikona sajta (favicon)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='naslov_povezani',
            field=models.CharField(blank=True, default='Povezani artikli', help_text='Na stranici artikla. Ostavite prazno da se naslov ne prikazuje.', max_length=120, verbose_name='Povezani artikli — naslov'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='podnaslov_povezani',
            field=models.CharField(blank=True, default='Iz kategorije {kategorija}', help_text='Koristite {kategorija} za naziv kategorije. Ostavite prazno da se podnaslov ne prikazuje.', max_length=200, verbose_name='Povezani artikli — podnaslov'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='naslov_izdvojeno',
            field=models.CharField(blank=True, default='Izdvojeno', help_text='Ostavite prazno da se naslov ne prikazuje.', max_length=120, verbose_name='Izdvojeno — naslov'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='naslov_novo',
            field=models.CharField(blank=True, default='Novo', help_text='Ostavite prazno da se naslov ne prikazuje.', max_length=120, verbose_name='Novo — naslov'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='podnaslov_izdvojeno',
            field=models.CharField(blank=True, default='Odabrani artikli za vas', help_text='Ostavite prazno da se podnaslov ne prikazuje.', max_length=200, verbose_name='Izdvojeno — podnaslov'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='podnaslov_novo',
            field=models.CharField(blank=True, default='Najnoviji artikli na sajtu', help_text='Ostavite prazno da se podnaslov ne prikazuje.', max_length=200, verbose_name='Novo — podnaslov'),
        ),
    ]
