# Generated by Django 6.0.6 on 2026-07-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0055_sitesettings_titles_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='badge_product_detail',
            field=models.ImageField(blank=True, help_text='Prikazuje se u gornjem lijevom uglu slike na stranici artikla (npr. garancija). PNG s transparentnom pozadinom.', null=True, upload_to='site/', verbose_name='Badge na slici artikla'),
        ),
    ]
