# Generated by Django 6.0.6 on 2026-07-02 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0056_sitesettings_product_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='akcija_artikal',
            field=models.ForeignKey(blank=True, help_text='Prikazuje se ispod tajmera u akcijskom pop-upu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='akcija_popupi', to='EcommerceApp.product', verbose_name='Artikal u akciji'),
        ),
        migrations.AddField(
            model_name='popup',
            name='akcija_pocetak',
            field=models.DateTimeField(blank=True, help_text='Od kada se računa odbrojavanje (početak + sati = kraj akcije).', null=True, verbose_name='Početak akcije'),
        ),
        migrations.AddField(
            model_name='popup',
            name='akcija_sati',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Koliko sati traje odbrojavanje od početka akcije.', null=True, verbose_name='Trajanje akcije (sati)'),
        ),
        migrations.AddField(
            model_name='popup',
            name='tip',
            field=models.CharField(choices=[('slika', 'Slika + dugme'), ('akcija', 'Akcijski pop-up (tajmer + artikal)')], default='slika', max_length=10, verbose_name='Tip pop-upa'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='slika',
            field=models.ImageField(blank=True, help_text='Glavna slika pop-upa. Dugme će biti ispod slike. Obavezno za tip „Slika + dugme”.', null=True, upload_to='popups/', verbose_name='Slika'),
        ),
    ]
