# Generated by Django 6.0.6 on 2026-07-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0057_popup_akcija_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='filter_cijena_do',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcionalno. Npr. 50 prikazuje samo artikle ≤ 50 KM (uz kategoriju iz linka).', max_digits=10, null=True, verbose_name='Filter: maks. cijena (KM)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='filter_cijena_od',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcionalno. Npr. 10 prikazuje samo artikle ≥ 10 KM.', max_digits=10, null=True, verbose_name='Filter: min. cijena (KM)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, help_text='Npr. /kategorija/masinice/ ili /?kategorija=masinice. Klik na banner vodi na ovaj link.', max_length=300, verbose_name='Link'),
        ),
    ]
