# Generated by Django 6.0.6 on 2026-07-02 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0058_banner_price_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='kategorija',
            field=models.ForeignKey(blank=True, help_text='Opcionalno. Ako nema linka, klik vodi na ovu kategoriju (uz filter cijene).', limit_choices_to={'aktivan': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banneri', to='EcommerceApp.category', verbose_name='Kategorija'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='filter_cijena_do',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcionalno. Npr. 50 = samo artikli ≤ 50 KM iz odabrane kategorije.', max_digits=10, null=True, verbose_name='Filter: do cijene (KM)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='filter_cijena_od',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcionalno. Npr. 50 = samo artikli ≥ 50 KM iz odabrane kategorije.', max_digits=10, null=True, verbose_name='Filter: od cijene (KM)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, help_text='Opcionalno. Puni URL ili putanja. Ako je prazno, koristi se kategorija iznad.', max_length=300, verbose_name='Link'),
        ),
    ]
