# Generated by Django 6.0.6 on 2026-07-02 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0062_sitesettings_kontakt_messenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(upload_to='products/', verbose_name='Dodatna slika')),
                ('redoslijed', models.PositiveIntegerField(default=0, verbose_name='Redoslijed (manji broj = prije)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodatne_slike', to='EcommerceApp.product', verbose_name='Artikal')),
            ],
            options={
                'verbose_name': 'Dodatna slika artikla',
                'verbose_name_plural': 'Dodatne slike artikla',
                'ordering': ['redoslijed', 'id'],
            },
        ),
    ]
