# Generated by Django 6.0.6 on 2026-07-02 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0063_add_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['roditelj__naziv', 'naziv'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tagovi'},
        ),
        migrations.AddField(
            model_name='tag',
            name='roditelj',
            field=models.ForeignKey(blank=True, help_text='Ako je izabran, ovaj tag je podtag glavnog taga (npr. "Masinice" kao glavni, a "Shimano", "Daiwa" pod njim).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podtagovi', to='EcommerceApp.tag', verbose_name='Glavni tag (roditelj)'),
        ),
    ]
