# Generated by Django 6.0.6 on 2026-07-02 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0064_tag_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='upselloffer',
            name='deal_artikal',
            field=models.ForeignKey(blank=True, help_text='Artikal na koji se odnosi 1+1 / 2+1 / 3+1 ponuda.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantity_deals', to='EcommerceApp.product', verbose_name='Artikal za X+1 deal'),
        ),
        migrations.AddField(
            model_name='upselloffer',
            name='deal_popust',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='npr. 50 = 50% popusta na 3. artikal. 100 = GRATIS.', max_digits=5, null=True, verbose_name='Popust % na +1 artikal'),
        ),
        migrations.AddField(
            model_name='upselloffer',
            name='deal_vrsta',
            field=models.CharField(blank=True, choices=[('1+1', '1+1 (kupi 1, drugi snižen)'), ('2+1', '2+1 (kupi 2, treći snižen)'), ('3+1', '3+1 (kupi 3, četvrti snižen)')], max_length=10, null=True, verbose_name='Vrsta prodaje'),
        ),
    ]
