# Generated by Django 6.0.6 on 2026-07-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0065_upsell_quantity_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='boja_akcija_istice',
            field=models.CharField(default='#5BB805', help_text='Hex boja za labelu "Akcija ističe za" i slične elemente u akcijskom pop-upu.', max_length=7, verbose_name='Boja "Akcija ističe za"'),
        ),
        migrations.AddField(
            model_name='popup',
            name='boja_dugmeta',
            field=models.CharField(default='#5BB805', help_text='Hex boja za pozadinu dugmeta u pop-upu (npr. #5BB805).', max_length=7, verbose_name='Boja dugmeta'),
        ),
    ]
