# Generated by Django 6.0.6 on 2026-07-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0066_popup_boja_akcija_istice_popup_boja_dugmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='akcija_popust_postotak',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Popust koji se primjenjuje na artikal ako je ukupno u korpi preko praga (samo za tip AKCIJA).', max_digits=5, null=True, verbose_name='% popusta na artikal'),
        ),
        migrations.AddField(
            model_name='popup',
            name='akcija_prag_iznos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimalni iznos u korpi da bi se popust na artikal primijenio. Npr. 50. (samo za tip AKCIJA)', max_digits=10, null=True, verbose_name='Prag ukupne kupovine (KM)'),
        ),
    ]
