# Generated by Django 6.0.6 on 2026-07-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0067_popup_akcija_popust_postotak_popup_akcija_prag_iznos'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popup_delay_seconds',
            field=models.PositiveSmallIntegerField(default=5, help_text='Koliko sekundi nakon učitavanja stranice da se prikaže pop-up (0 = odmah).', verbose_name='Prikaži pop-up nakon (sekundi)'),
        ),
    ]
