# Generated by Django 6.0.6 on 2026-07-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0068_popup_popup_delay_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='kategorija',
        ),
        migrations.AddField(
            model_name='banner',
            name='kategorije',
            field=models.ManyToManyField(blank=True, help_text='Opcionalno. Ako nema linka, klik vodi na filtrirane kategorije (uz filter cijene). Možete odabrati više kategorija.', limit_choices_to={'aktivan': True}, related_name='banneri', to='EcommerceApp.category', verbose_name='Kategorije'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, help_text='Opcionalno. Puni URL ili putanja. Ako je prazno, koristi se kategorija(e) iznad.', max_length=300, verbose_name='Link'),
        ),
    ]
