# Generated by Django 6.0.6 on 2026-07-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0069_remove_banner_kategorija_banner_kategorije_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='filter_cijena_do',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcionalno. Npr. 50 = samo artikli ≤ 50 KM iz odabranih kategorija.', max_digits=10, null=True, verbose_name='Filter: do cijene (KM)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='filter_cijena_od',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcionalno. Npr. 50 = samo artikli ≥ 50 KM iz odabranih kategorija.', max_digits=10, null=True, verbose_name='Filter: od cijene (KM)'),
        ),
    ]
