# Generated by Django 6.0.6 on 2026-07-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0072_akcija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akcija',
            name='prag_korpe_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prag u KM — u iznos se računa cijela korpa minus tačno 1 komad ovog artikla.', max_digits=10, null=True, verbose_name='Uslov: iznos u korpi (KM)'),
        ),
    ]
