# Generated by Django 6.0.6 on 2026-07-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0073_alter_akcija_prag_korpe_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akcija',
            name='tip',
            field=models.CharField(choices=[('slika', 'Pop-up + slika'), ('timer', 'Akcija + tajmer'), ('x_plus_1', 'X+1 prodaja (samo korpa)'), ('uslov', 'Uslov prodaja')], default='slika', max_length=12, verbose_name='Tip akcije'),
        ),
    ]
