# Generated by Django 6.0.6 on 2026-07-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0074_alter_akcija_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='akcija',
            name='kategorija',
            field=models.ForeignKey(
                blank=True,
                help_text='Za korpa nudjenje: artikli iz ove kategorije (i podkategorija) vide ponudu.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='akcije_korpa_nudjenje',
                to='EcommerceApp.category',
                verbose_name='Kategorija (trigger)',
            ),
        ),
        migrations.AlterField(
            model_name='akcija',
            name='tip',
            field=models.CharField(
                choices=[
                    ('slika', 'Pop-up + slika'),
                    ('timer', 'Akcija + tajmer'),
                    ('x_plus_1', 'X+1 prodaja (samo korpa)'),
                    ('uslov', 'Uslov prodaja'),
                    ('korpa_nudjenje', 'Korpa nudjenje'),
                ],
                default='slika',
                max_length=16,
                verbose_name='Tip akcije',
            ),
        ),
    ]