# Generated by Django 6.0.6 on 2026-07-05

from django.db import migrations, models


def enable_prijavljene_for_solo_guest_popups(apps, schema_editor):
    Akcija = apps.get_model('EcommerceApp', 'Akcija')
    Akcija.objects.filter(
        za_prijavljene=False,
        za_neprijavljene=True,
    ).update(za_prijavljene=True)


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0076_alter_akcija_artikal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akcija',
            name='za_prijavljene',
            field=models.BooleanField(
                default=True,
                verbose_name='Prikaži prijavljenim korisnicima',
            ),
        ),
        migrations.RunPython(
            enable_prijavljene_for_solo_guest_popups,
            migrations.RunPython.noop,
        ),
    ]