# Generated by Django 6.0.6 on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0077_akcija_za_prijavljene_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akcija',
            name='ponovo_poslije_dana',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text='0 = ponovo u svakoj novoj posjeti (novi prozor). Npr. 7 = ne prikazuj 7 dana nakon zatvaranja.',
                verbose_name='Ponovo prikaži poslije (dana)',
            ),
        ),
    ]