# Generated by Django 6.0.6 on 2026-07-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0078_alter_akcija_ponovo_poslije_dana'),
    ]

    operations = [
        migrations.AddField(
            model_name='akcija',
            name='gratis_artikal',
            field=models.ForeignKey(
                blank=True,
                help_text='Za + Gratis: artikal koji se automatski dodaje u korpu sa 100% popusta.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='akcije_gratis',
                to='EcommerceApp.product',
                verbose_name='Gratis artikal',
            ),
        ),
        migrations.AlterField(
            model_name='akcija',
            name='tip',
            field=models.CharField(
                choices=[
                    ('slika', 'Pop-up + slika'),
                    ('timer', 'Akcija + tajmer'),
                    ('x_plus_1', 'X+1 prodaja (samo korpa)'),
                    ('uslov', 'Uslov prodaja'),
                    ('korpa_nudjenje', 'Korpa nudjenje'),
                    ('gratis', '+ Gratis'),
                ],
                default='slika',
                max_length=16,
                verbose_name='Tip akcije',
            ),
        ),
    ]