# Generated by Django 6.0.6 on 2026-07-05 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0079_akcija_gratis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akcija',
            name='artikal',
            field=models.ForeignKey(blank=True, help_text='Aktivan artikal sa sajta (tajmer, uslov, X+1, korpa nudjenje, + Gratis trigger).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='akcije', to='EcommerceApp.product', verbose_name='Artikal'),
        ),
    ]
