# Generated by Django 6.0.6 on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0080_alter_akcija_artikal'),
    ]

    operations = [
        migrations.AddField(
            model_name='akcija',
            name='gratis_popup',
            field=models.BooleanField(
                default=False,
                help_text='Uključeno = ponuda u pop-upu (oba artikla na klik). Isključeno = automatski u korpi pri dodavanju trigger artikla.',
                verbose_name='Prikaži kao pop-up',
            ),
        ),
        migrations.AlterField(
            model_name='akcija',
            name='gratis_artikal',
            field=models.ForeignKey(
                blank=True,
                help_text='Za + Gratis: drugi artikal koji dobija popust (%).',
                null=True,
                on_delete=models.SET_NULL,
                related_name='akcije_gratis',
                to='EcommerceApp.product',
                verbose_name='Gratis artikal',
            ),
        ),
    ]