# Generated by Django 6.0.6 on 2026-07-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0084_marketingsubscriber'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='marketingsubscriber',
            new_name='EcommerceAp_aktivan_8e6884_idx',
            old_name='EcommerceAp_aktivan_6f3e2a_idx',
        ),
    ]
