# Generated by Django 6.0.6 on 2026-07-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0088_marketingsubscribergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='azuriran',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kreiran',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dodano'),
        ),
    ]
