# Generated by Django 6.0.6 on 2026-07-07 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0089_alter_product_azuriran_alter_product_kreiran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Sesija')),
                ('line_key', models.CharField(max_length=64, verbose_name='Stavka')),
                ('naziv', models.CharField(max_length=200, verbose_name='Naziv')),
                ('varijacija_naziv', models.CharField(blank=True, max_length=100, verbose_name='Varijacija naziv')),
                ('kolicina', models.PositiveIntegerField(default=1, verbose_name='Količina')),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cijena')),
                ('ukupno', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ukupno')),
                ('dodano', models.DateTimeField(auto_now_add=True, verbose_name='Dodano u korpu')),
                ('azurirano', models.DateTimeField(auto_now=True, verbose_name='Zadnja izmjena')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktivne_korpe_stavke', to='EcommerceApp.product', verbose_name='Artikal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktivne_korpe_stavke', to=settings.AUTH_USER_MODEL, verbose_name='Korisnik')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktivne_korpe_stavke', to='EcommerceApp.productvariation', verbose_name='Varijacija')),
            ],
            options={
                'verbose_name': 'Stavka aktivne korpe',
                'verbose_name_plural': 'Stavke aktivnih korpi',
                'ordering': ['-azurirano'],
                'indexes': [models.Index(fields=['-azurirano'], name='EcommerceAp_azurira_9dfe3b_idx'), models.Index(fields=['user', '-azurirano'], name='EcommerceAp_user_id_9d5cb7_idx')],
                'constraints': [models.UniqueConstraint(fields=('session_key', 'line_key'), name='uniq_active_cart_session_line')],
            },
        ),
    ]
