# Generated by Django 6.0.6 on 2026-07-07 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0090_active_cart_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartRecoveryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Sesija')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Popust (%)')),
                ('show_popup', models.BooleanField(default=True, verbose_name='Prikaži popup')),
                ('discount_applied', models.BooleanField(default=False, verbose_name='Popust iskorišten')),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('azurirano', models.DateTimeField(auto_now=True)),
                ('poslao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_recovery_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Poslao')),
            ],
            options={
                'verbose_name': 'Podsjetnik korpe',
                'verbose_name_plural': 'Podsjetnici korpi',
                'ordering': ['-azurirano'],
            },
        ),
    ]
