# Generated by Django 6.0.6 on 2026-07-07 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0091_cart_recovery_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartrecoveryalert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_recovery_alerts_received', to=settings.AUTH_USER_MODEL, verbose_name='Kupac'),
        ),
        migrations.AlterField(
            model_name='cartrecoveryalert',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Sesija'),
        ),
    ]
