# Generated by Django 6.0.6 on 2026-07-07 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0092_cart_recovery_alert_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Sesija')),
                ('ime', models.CharField(blank=True, max_length=120, verbose_name='Ime')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Prva aktivnost')),
                ('last_seen', models.DateTimeField(db_index=True, verbose_name='Zadnja aktivnost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_visits', to=settings.AUTH_USER_MODEL, verbose_name='Korisnik')),
            ],
            options={
                'verbose_name': 'Posjetilac (uzivo)',
                'verbose_name_plural': 'Posjetioci (uzivo)',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['-last_seen'], name='EcommerceAp_last_se_550926_idx'), models.Index(fields=['email', '-last_seen'], name='EcommerceAp_email_4b2cf2_idx')],
            },
        ),
    ]
