# Generated by Django 6.0.6 on 2026-07-07 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0093_live_visitor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveVisitorOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Sesija')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Popust (%)')),
                ('show_popup', models.BooleanField(default=True, verbose_name='Prikaži popup')),
                ('added_to_cart', models.BooleanField(default=False, verbose_name='Dodano u korpu')),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('azurirano', models.DateTimeField(auto_now=True)),
                ('poslao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_visitor_offers_sent', to=settings.AUTH_USER_MODEL, verbose_name='Poslao')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_visitor_offers', to='EcommerceApp.product', verbose_name='Artikal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_visitor_offers_received', to=settings.AUTH_USER_MODEL, verbose_name='Posjetilac')),
            ],
            options={
                'verbose_name': 'Uzivo ponuda posjetiocu',
                'verbose_name_plural': 'Uzivo ponude posjetiocima',
                'ordering': ['-azurirano'],
            },
        ),
    ]
