# Generated by Django 6.0.6 on 2026-07-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0099_livevisitor_pregledane_kategorije'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='korpa_exit_popup_aktivan',
            field=models.BooleanField(default=False, help_text='Prikazuje popup na cijelom sajtu kad posjetilac pomjeri kursor prema zatvaranju taba.', verbose_name='Exit popup aktivan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='korpa_exit_popup_popust',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcionalno. Smanjuje cijenu odabranog artikla pri dodavanju iz popupa (max 50%).', max_digits=5, null=True, verbose_name='Exit popup popust (%)'),
        ),
    ]
