# Generated by Django 6.0.6 on 2026-07-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0102_livevisitoroffer_registracija'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityVisitTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grad', models.CharField(max_length=100, unique=True, verbose_name='Grad')),
                ('broj_posjeta', models.PositiveIntegerField(default=0, verbose_name='Broj posjeta')),
                ('azurirano', models.DateTimeField(auto_now=True, verbose_name='Zadnje ažuriranje')),
            ],
            options={
                'verbose_name': 'Posjete po gradu (ukupno)',
                'verbose_name_plural': 'Posjete po gradovima (ukupno)',
                'ordering': ['-broj_posjeta', 'grad'],
            },
        ),
    ]
