# Generated by Django 6.0.6 on 2026-07-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0103_cityvisittotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSiteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('online', 'Online na sajtu'), ('cart', 'Dodano u korpu'), ('register', 'Registracija'), ('purchase', 'Kupovina')], db_index=True, max_length=20)),
                ('naslov', models.CharField(max_length=120)),
                ('poruka', models.CharField(max_length=300)),
                ('ime', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('grad', models.CharField(blank=True, max_length=100)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('kreirano', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Staff live obavijest',
                'verbose_name_plural': 'Staff live obavijesti',
                'ordering': ['-kreirano'],
                'indexes': [models.Index(fields=['-kreirano', 'id'], name='EcommerceAp_kreiran_701464_idx')],
            },
        ),
    ]
