# Generated by Django 6.0.6 on 2026-07-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0105_livevisitor_realtime_engine'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='livevisitor',
            new_name='EcommerceAp_user_id_c577d3_idx',
            old_name='ecommerceap_user_id_live_idx',
        ),
    ]
