# Generated by Django 6.0.6 on 2026-07-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0108_prize_wheel'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='prizewheelspin',
            new_name='EcommerceAp_session_9dc144_idx',
            old_name='EcommerceAp_session_pw_idx',
        ),
        migrations.RenameIndex(
            model_name='prizewheelspin',
            new_name='EcommerceAp_user_id_982724_idx',
            old_name='EcommerceAp_user_pw_idx',
        ),
    ]
