# Generated by Django 6.0.6 on 2026-07-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0109_rename_ecommerceap_session_pw_idx_ecommerceap_session_9dc144_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizewheel',
            name='prize_type',
            field=models.CharField(choices=[('product', 'Gratis artikal (100%)'), ('percent', '% na kompletnu narudžbu'), ('fixed_km', 'KM iznos popusta'), ('free_shipping', 'Besplatna dostava')], default='percent', max_length=20, verbose_name='Tip nagrade'),
        ),
    ]
