# Generated by Django 6.0.6 on 2026-07-11 17:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0110_alter_prizewheel_prize_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prizewheel',
            options={'ordering': ['-aktivan', '-azurirano'], 'verbose_name': 'Greb-greb nagrada', 'verbose_name_plural': 'Greb-greb nagrade'},
        ),
        migrations.AlterModelOptions(
            name='prizewheelspin',
            options={'ordering': ['-kreirano'], 'verbose_name': 'Greb-greb igra', 'verbose_name_plural': 'Greb-greb igre'},
        ),
        migrations.AlterField(
            model_name='prizewheel',
            name='naslov',
            field=models.CharField(default='Greb-greb nagrada', max_length=120, verbose_name='Naslov popupa'),
        ),
        migrations.AlterField(
            model_name='prizewheel',
            name='once_per_visitor',
            field=models.BooleanField(default=True, help_text='Ako je uključeno, posjetilac može odigrati greb-greb samo jednom (sesija / nalog).', verbose_name='Jednom po posjetiocu'),
        ),
        migrations.AlterField(
            model_name='prizewheel',
            name='podnaslov',
            field=models.CharField(blank=True, default='Ogrebi 6 polja — 3 ista = nagrada!', max_length=200, verbose_name='Podnaslov'),
        ),
        migrations.AlterField(
            model_name='prizewheel',
            name='popup_delay_seconds',
            field=models.PositiveSmallIntegerField(default=2, help_text='0 = odmah.', verbose_name='Prikaži nakon (sekundi)'),
        ),
        migrations.AlterField(
            model_name='prizewheel',
            name='segments_count',
            field=models.PositiveSmallIntegerField(default=6, help_text='Uvijek se koristi 6 polja greb-greb (3 ista = pobjeda).', verbose_name='Broj polja (greb-greb)'),
        ),
        migrations.AlterField(
            model_name='prizewheel',
            name='win_chance_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Koliko % igara daje 3 ista nagradna simbola. Npr. 25 ≈ svaka 4. igra.', max_digits=5, verbose_name='Šansa za nagradu (%)'),
        ),
        migrations.AlterField(
            model_name='prizewheelspin',
            name='wheel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='EcommerceApp.prizewheel', verbose_name='Greb-greb'),
        ),
    ]
