# Generated by Django 6.0.6 on 2026-07-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0112_online_gift_replace_prize_wheel'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='onlinegiftclaim',
            new_name='EcommerceAp_session_8165db_idx',
            old_name='EcommerceAp_session_ogc_idx',
        ),
        migrations.RenameIndex(
            model_name='onlinegiftclaim',
            new_name='EcommerceAp_user_id_f77c46_idx',
            old_name='EcommerceAp_user_ogc_idx',
        ),
    ]
