# Generated by Django 6.0.6 on 2026-07-11 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0114_online_gift_automatic_push_order'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='onlinegiftclaim',
            new_name='EcommerceAp_won_e430a8_idx',
            old_name='ecommerceap_won_kre_idx',
        ),
        migrations.RenameIndex(
            model_name='onlinegiftpush',
            new_name='EcommerceAp_session_707f3c_idx',
            old_name='ecommerceap_session_ogp_idx',
        ),
    ]
