# Generated by Django 6.0.6 on 2026-07-11 20:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0115_rename_ecommerceap_won_kre_idx_ecommerceap_won_e430a8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='browse_interest_popup_aktivan',
            field=models.BooleanField(default=True, help_text='Automatski popup: 10% popusta na artikle na koje se kupac vratio 2+ puta i preporuke iz najgledanije kategorije.', verbose_name='Personalizovana ponuda (gledanje) aktivna'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='browse_interest_popust',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('10.00'), help_text='Popust na preporučene artikle (max 50%). Podrazumijevano 10%.', max_digits=5, null=True, verbose_name='Personalizovana ponuda — popust (%)'),
        ),
    ]
