# Generated by Django 6.0.6 on 2026-07-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0116_browse_interest_popup_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='livevisitor',
            name='skoro_korpa',
            field=models.JSONField(blank=True, default=list, help_text='Artikli gdje je kursor bio na „Dodaj u korpu” ali nije kliknuo. Lista {id, naziv, hovers, last_at} — najjači intent za #1 ponudu.', verbose_name='Skoro dodao u korpu'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='browse_interest_popup_aktivan',
            field=models.BooleanField(default=True, help_text='Automatski popup do 4 artikla 2×2 („Specijalna ponuda za vas”): prva nakon 1 min, druga nakon 3 min (popust ispod).', verbose_name='Personalizovana ponuda (gledanje) aktivna'),
        ),
    ]
