# Generated by Django 6.0.6 on 2026-07-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0117_livevisitor_skoro_korpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitorIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token')),
                ('visit_count', models.PositiveIntegerField(default=1, verbose_name='Broj posjeta')),
                ('last_session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Prva posjeta')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Zadnja posjeta')),
            ],
            options={
                'verbose_name': 'Identitet posjetioca',
                'verbose_name_plural': 'Identiteti posjetilaca',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddField(
            model_name='livevisitor',
            name='site_visit_count',
            field=models.PositiveIntegerField(default=1, help_text='>1 = vraćeni posjetilac (nije prvi put).', verbose_name='Broj dolazaka na sajt'),
        ),
        migrations.AddField(
            model_name='livevisitor',
            name='visitor_token',
            field=models.CharField(blank=True, db_index=True, help_text='Cookie ozb_vid — veza preko sesija.', max_length=64, verbose_name='Trajni token'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='browse_interest_popup_aktivan',
            field=models.BooleanField(default=True, help_text='Automatski popup do 4 artikla 2×2 („Specijalna ponuda za vas”): prva nakon 2 min, druga nakon 4 min (popust ispod).', verbose_name='Personalizovana ponuda (gledanje) aktivna'),
        ),
    ]
