# Generated by Django 6.0.6 on 2026-07-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0118_visitor_return_and_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinegiftcampaign',
            name='automatic',
            field=models.BooleanField(default=True, help_text='Uključeno: na stranicama iskače ponuda nagradne igre — kupac sam bira „Da, igraj” ili „Ne, hvala” (jednom po posjetiocu ako je uključeno ispod). Isključeno: nagrada se ne pojavljuje sama — staff je pušta ručno u Uživo analitici pored kupca.', verbose_name='Automatski svima online'),
        ),
    ]
