# Generated by Django 6.0.6 on 2026-07-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0119_alter_onlinegiftcampaign_automatic'),
    ]

    operations = [
        migrations.AddField(
            model_name='livevisitor',
            name='trenutna_putanja',
            field=models.CharField(blank=True, help_text='URL putanja na kojoj je kupac sada (za live analitiku).', max_length=300, verbose_name='Trenutna putanja'),
        ),
        migrations.AddField(
            model_name='livevisitor',
            name='trenutno_gleda',
            field=models.CharField(blank=True, help_text='Čitljiv opis: artikal, kategorija, korpa, početna…', max_length=200, verbose_name='Trenutno gleda'),
        ),
        migrations.AlterField(
            model_name='onlinegiftcampaign',
            name='automatic',
            field=models.BooleanField(default=True, help_text='Uključeno: registrovanom kupcu nakon ~10 s iskače nagradna igra (gostima ide poziv na registraciju + besplatna dostava). Isključeno: nagrada se ne pojavljuje sama — staff je pušta ručno u Uživo analitici.', verbose_name='Automatski registrovanima online'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='browse_interest_popup_aktivan',
            field=models.BooleanField(default=True, help_text='Automatski popup do 4 artikla 2×2 („Specijalna ponuda za vas”): nakon 3 min na sajtu, prema tome šta kupac gleda (jednom po posjeti).', verbose_name='Personalizovana ponuda (gledanje) aktivna'),
        ),
    ]
