# Generated by Django 6.0.6 on 2026-07-12 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0120_livevisitor_current_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akcija',
            name='artikal',
            field=models.ForeignKey(blank=True, help_text='Aktivan artikal sa sajta (tajmer, uslov, X+1, korpa nudjenje, + Gratis trigger, ili 1. artikal u Pop-up bundle).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='akcije', to='EcommerceApp.product', verbose_name='Artikal'),
        ),
        migrations.AlterField(
            model_name='akcija',
            name='gratis_artikal',
            field=models.ForeignKey(blank=True, help_text='Za + Gratis: drugi artikal s popustom. Za Pop-up bundle: drugi artikal u setu (oba s istim % popusta).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='akcije_gratis', to='EcommerceApp.product', verbose_name='Gratis / 2. artikal'),
        ),
        migrations.AlterField(
            model_name='akcija',
            name='tip',
            field=models.CharField(choices=[('slika', 'Pop-up + slika'), ('timer', 'Akcija + tajmer'), ('x_plus_1', 'X+1 prodaja (samo korpa)'), ('uslov', 'Uslov prodaja'), ('korpa_nudjenje', 'Korpa nudjenje'), ('gratis', '+ Gratis'), ('bundle', 'Pop-up bundle')], default='slika', max_length=16, verbose_name='Tip akcije'),
        ),
        migrations.AlterField(
            model_name='onlinegiftcampaign',
            name='automatic',
            field=models.BooleanField(default=True, help_text='Uključeno: nakon ~4 min na sajtu iskače nagradna igra (prije toga na 2 min ide personalizovana ponuda prema gledanju). Igranje je samo za registrovane (gost vidi „Registruj se i igraj”). Isključeno: nagrada se ne pojavljuje sama — staff je pušta ručno u Uživo analitici.', verbose_name='Automatski online (nakon 4 min)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='browse_interest_popup_aktivan',
            field=models.BooleanField(default=True, help_text='Automatski popup do 4 artikla 2×2 („Specijalna ponuda za vas”): nakon 2 min na sajtu, prema onome što kupac najviše gleda. Nagradna igra ide odvojeno nakon 4 min.', verbose_name='Personalizovana ponuda (gledanje) aktivna'),
        ),
    ]
