# Generated by Django 6.0.6 on 2026-07-12 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0121_akcija_popup_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='akcija',
            name='bundle_artikli',
            field=models.ManyToManyField(blank=True, help_text='Za Pop-up bundle: 2 ili više artikala. % popusta vrijedi za kompletan set.', related_name='akcije_bundle', to='EcommerceApp.product', verbose_name='Artikli u setu (bundle)'),
        ),
        migrations.AddField(
            model_name='akcija',
            name='bundle_trigger',
            field=models.CharField(blank=True, choices=[('delay', 'Nakon kašnjenja (bilo gdje na sajtu)'), ('bundle_product', 'Kad gleda artikal iz seta'), ('trigger_product', 'Kad gleda odabrani trigger artikal'), ('category', 'Kad gleda odabranu kategoriju')], default='delay', help_text='Kada se bundle prikaže. Samo tada iskače.', max_length=20, verbose_name='Šta trigeruje pop-up bundle'),
        ),
        migrations.AlterField(
            model_name='akcija',
            name='artikal',
            field=models.ForeignKey(blank=True, help_text='Aktivan artikal (tajmer, uslov, X+1, korpa nudjenje, + Gratis trigger). Za Pop-up bundle: samo ako je trigger „odabrani trigger artikal”.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='akcije', to='EcommerceApp.product', verbose_name='Artikal'),
        ),
        migrations.AlterField(
            model_name='akcija',
            name='gratis_artikal',
            field=models.ForeignKey(blank=True, help_text='Za + Gratis: drugi artikal s popustom (%).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='akcije_gratis', to='EcommerceApp.product', verbose_name='Gratis artikal'),
        ),
        migrations.AlterField(
            model_name='akcija',
            name='kategorija',
            field=models.ForeignKey(blank=True, help_text='Korpa nudjenje: artikli iz kategorije vide ponudu. Pop-up bundle: ako je trigger „kategorija”.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='akcije_korpa_nudjenje', to='EcommerceApp.category', verbose_name='Kategorija (trigger)'),
        ),
        migrations.AlterField(
            model_name='akcija',
            name='popust_postotak',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Za Pop-up bundle: % sniženja na kompletan set (svaki artikal u setu).', max_digits=5, null=True, verbose_name='Popust (%)'),
        ),
    ]
