# Generated by Django 6.0.6 on 2026-07-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0122_akcija_bundle_m2m_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='browse_interest_popup_aktivan',
            field=models.BooleanField(default=True, help_text='Automatski popup do 4 artikla 2×2 („Specijalna ponuda za vas”): nakon 2 min na sajtu, prema onome što kupac najviše gleda (jednom). Poslije toga se ne prikazuju druge automatske ponude.', verbose_name='Personalizovana ponuda (gledanje) aktivna'),
        ),
    ]
