# Generated by Django 6.0.6 on 2026-07-12 18:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0123_alter_sitesettings_browse_interest_popup_aktivan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_popup_aktivan',
            field=models.BooleanField(default=False, help_text='Uključeno: ako kupac gleda isti artikal duže od 1 minute, iskače popup s popustom na taj artikal (jednom po artiklu).', verbose_name='Popust na artikal (1 min gledanja) aktivan'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_popust',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('10.00'), help_text='Popust na artikal kad se gleda ≥ 1 min (max 50%). Podrazumijevano 10%.', max_digits=5, null=True, verbose_name='Popust na artikal (1 min) — %'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='browse_interest_popup_aktivan',
            field=models.BooleanField(default=True, help_text='Automatski popup do 4 artikla 2×2 („Specijalna ponuda za vas”): nakon 2 min na sajtu, prema onome što kupac najviše gleda (jednom).', verbose_name='Personalizovana ponuda (gledanje) aktivna'),
        ),
    ]
