# Generated by Django 6.0.6 on 2026-07-12 18:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0124_product_dwell_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='online_nagrada_bočni_aktivan',
            field=models.BooleanField(default=False, help_text='Uključeno: nagradna igra se nudi kao mali pulsirajući popup sa strane (ne preko cijelog ekrana). Igranje i dalje zahtijeva registraciju. Mora postojati aktivna kampanja Online nagrada u adminu.', verbose_name='Nagradna igra (bočni popup) aktivna'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='online_nagrada_delay_seconds',
            field=models.PositiveSmallIntegerField(default=15, help_text='Kašnjenje bočnog popupa nagradne igre (0 = odmah).', verbose_name='Nagradna igra — prikaži nakon (sekundi)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='welcome_reg_delay_seconds',
            field=models.PositiveSmallIntegerField(default=8, help_text='Koliko sekundi nakon ulaska na sajt (0 = odmah).', verbose_name='Registracija popup — prikaži nakon (sekundi)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='welcome_reg_popup_aktivan',
            field=models.BooleanField(default=False, help_text='Uključeno: gostu na početku (nakon nekoliko sekundi) iskače poziv „Registruj se” s popustom na prvu narudžbu.', verbose_name='Registracija + popust (odmah) aktivan'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='welcome_reg_popust',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('10.00'), help_text='Npr. 10 = 10% kupon nakon registracije (max 50%).', max_digits=5, null=True, verbose_name='Registracija — popust na prvu narudžbu (%)'),
        ),
    ]
