# Generated by Django 6.0.6 on 2026-07-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0125_welcome_reg_and_side_gift_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='welcome_reg_popup_aktivan',
            field=models.BooleanField(default=False, help_text='Uključeno: gostu na početku iskače poziv „Registruj se” s popustom na prvu narudžbu. Vrijeme prikaza postavi ispod (npr. 4 sekunde).', verbose_name='Registracija + popust aktivan'),
        ),
    ]
