# Generated by Django 6.0.6 on 2026-07-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0126_alter_sitesettings_welcome_reg_popup_aktivan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='welcome_reg_popup_aktivan',
            field=models.BooleanField(default=False, help_text='Uključeno: gostu na početku (nakon nekoliko sekundi) iskače poziv „Registruj se” s popustom na prvu narudžbu.', verbose_name='Registracija + popust (odmah) aktivan'),
        ),
    ]
