# Generated by Django 6.0.6 on 2026-07-12 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0127_alter_sitesettings_welcome_reg_popup_aktivan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkcijaBundleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, help_text='Npr. 2 = isti artikal dva puta (1+1).', verbose_name='Količina u setu')),
                ('redoslijed', models.PositiveSmallIntegerField(default=0, verbose_name='Redoslijed')),
                ('akcija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_lines', to='EcommerceApp.akcija', verbose_name='Akcija')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akcija_bundle_lines', to='EcommerceApp.product', verbose_name='Artikal')),
            ],
            options={
                'verbose_name': 'Bundle stavka',
                'verbose_name_plural': 'Bundle stavke',
                'ordering': ['redoslijed', 'id'],
            },
        ),
    ]
