# Generated by Django 6.0.6 on 2026-07-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0128_akcija_bundle_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='akcijabundleline',
            name='popust_postotak',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcionalno. Ako uneseš — važi samo za ovaj artikal. Prazno = koristi % kompletnog seta iz akcije.', max_digits=5, null=True, verbose_name='Popust % (samo ovaj artikal)'),
        ),
        migrations.AlterField(
            model_name='akcija',
            name='popust_postotak',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pop-up bundle: % na cijeli set (ako linija nema svoj %). Za % samo na jedan artikal — unesi „Popust % (samo ovaj artikal)” na bundle stavci.', max_digits=5, null=True, verbose_name='Popust (%)'),
        ),
        migrations.AlterField(
            model_name='akcijabundleline',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Npr. 2 = isti artikal ×2 (1+1). U popup-u: jedna slika + ×2.', verbose_name='Količina u setu'),
        ),
    ]
