# Generated by Django 6.0.6 on 2026-07-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0129_bundle_line_popust'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pakovanje_komada',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ako se prodaje u pakovanju (ne po komadu): unesi broj komada u pakovanju (npr. 9). Prazno = cijena je po komadu. Slika može biti jednog artikla — kupac vidi da je cijena za pakovanje od N komada.', null=True, verbose_name='Pakovanje (komada)'),
        ),
    ]
