# Generated by Django 6.0.6 on 2026-07-13 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0130_product_pakovanje_komada'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='pakovanje_komada',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ako ova varijacija ima drugačije pakovanje od artikla — unesi broj komada. Prazno = koristi pakovanje sa artikla (ako postoji).', null=True, verbose_name='Pakovanje (komada)'),
        ),
        migrations.AlterField(
            model_name='akcija',
            name='artikal',
            field=models.ForeignKey(blank=True, help_text='Aktivan artikal (tajmer, uslov, X+1, korpa nudjenje, + Gratis trigger). Za Pop-up bundle: samo ako je trigger „odabrani trigger artikal”. Za „Kupi više”: artikal na koji važi količinski popust.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='akcije', to='EcommerceApp.product', verbose_name='Artikal'),
        ),
        migrations.AlterField(
            model_name='akcija',
            name='popust_postotak',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pop-up bundle: % na cijeli set (ako linija nema svoj %). Za % samo na jedan artikal — unesi „Popust % (samo ovaj artikal)” na bundle stavci. Za „Kupi više”: opcionalno — % po količini unosi se na tier linijama (2, 3…).', max_digits=5, null=True, verbose_name='Popust (%)'),
        ),
        migrations.AlterField(
            model_name='akcija',
            name='tip',
            field=models.CharField(choices=[('slika', 'Pop-up + slika'), ('timer', 'Akcija + tajmer'), ('x_plus_1', 'X+1 prodaja (samo korpa)'), ('uslov', 'Uslov prodaja'), ('korpa_nudjenje', 'Korpa nudjenje'), ('gratis', '+ Gratis'), ('bundle', 'Pop-up bundle'), ('qty_deal', 'Kupi više (količinski %)')], default='slika', max_length=16, verbose_name='Tip akcije'),
        ),
        migrations.CreateModel(
            name='AkcijaQtyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(help_text='Minimalno 2. Npr. 2 = kupi 2 za taj %.', verbose_name='Kupi (komada)')),
                ('popust_postotak', models.DecimalField(decimal_places=2, help_text='Postotak popusta po komadu kad kupac uzme ovu količinu.', max_digits=5, verbose_name='Popust (%)')),
                ('redoslijed', models.PositiveSmallIntegerField(default=0, verbose_name='Redoslijed')),
                ('akcija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qty_tiers', to='EcommerceApp.akcija', verbose_name='Akcija')),
            ],
            options={
                'verbose_name': 'Količinski popust',
                'verbose_name_plural': 'Količinski popusti (2, 3…)',
                'ordering': ['quantity', 'redoslijed', 'id'],
                'unique_together': {('akcija', 'quantity')},
            },
        ),
    ]
