# Generated by Django 6.0.6 on 2026-07-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0131_qty_deal_and_variation_pakovanje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akcija',
            name='popup_delay_seconds',
            field=models.PositiveSmallIntegerField(default=5, help_text='0 = odmah. Ne vrijedi za X+1 (samo korpa). Ne vrijedi za „Kupi više” — taj se prikazuje samo na stranici odabranog artikla, bez kašnjenja.', verbose_name='Prikaži pop-up nakon (sekundi)'),
        ),
    ]
