# Generated by Django 6.0.6 on 2026-07-13 22:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0132_alter_akcija_popup_delay_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_artikli',
            field=models.ManyToManyField(blank=True, help_text='Odaberi jedan ili više artikala na kojima radi AI dwell. Ako ne odabereš nijedan — radi na SVIM artiklima.', related_name='dwell_flash_sitesettings', to='EcommerceApp.product', verbose_name='AI dwell — artikli (opcionalno)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='browse_interest_popup_aktivan',
            field=models.BooleanField(default=True, help_text='AI prati kupca (šta gleda, koliko dugo, skoro-korpa) i u pravom trenutku šalje popup s popustom na 1–2 artikla. Max 2 ponude po posjeti, s razmakom. Popust nikad preko 10%.', verbose_name='AI prodaja aktivna'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='browse_interest_popust',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('10.00'), help_text='Maksimalni popust na AI ponudu (preporučeno 10, hard cap 10%).', max_digits=5, null=True, verbose_name='AI prodaja — max popust (%)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_dwell_popup_aktivan',
            field=models.BooleanField(default=False, help_text='Ako kupac gleda isti artikal ≥ 30 s: NEMA popup-a. Na stranici se precrta stara cijena, pojavi se snizena i odbrojavanje 2 min. Kupac može izaći i vratiti se — snizenje traje dok ne istekne tajmer. Popust max 10%.', verbose_name='AI dwell (30 s na artiklu) aktivan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_dwell_popust',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('10.00'), help_text='Popust na cijenu artikla 2 min nakon 30 s gledanja (max 10%).', max_digits=5, null=True, verbose_name='AI dwell — popust (%)'),
        ),
        migrations.AlterField(
            model_name='staffsiteevent',
            name='tip',
            field=models.CharField(choices=[('online', 'Online na sajtu'), ('cart', 'Dodano u korpu'), ('register', 'Registracija'), ('purchase', 'Kupovina'), ('offer', 'Prihvaćena ponuda')], db_index=True, max_length=20),
        ),
    ]
