# Generated by Django 6.0.6 on 2026-07-14 18:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0134_akcije_only_bundle_qty_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='product_dwell_popup_aktivan',
            field=models.BooleanField(default=False, help_text='Čim kupac uđe na artikal: NEMA popup-a. Odmah se precrta stara cijena, pojavi se snizena i odbrojavanje 2 min. Kad istekne — u toj posjeti više nema ponude, samo regularna cijena. Dok traje može izaći i vratiti se. Popust max 10%.', verbose_name='AI dwell (odmah na artiklu) aktivan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_dwell_popust',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('10.00'), help_text='Flash popust odmah na ulasku na artikal, traje 2 min (max 10%).', max_digits=5, null=True, verbose_name='AI dwell — popust (%)'),
        ),
    ]
