# Generated by Django 6.0.6 on 2026-07-14 20:08

import django.db.models.deletion
from django.db import migrations, models


def seed_fish_types(apps, schema_editor):
    FishType = apps.get_model('EcommerceApp', 'AdvisorBeginnerFishType')
    defaults = [
        ('saran', 'Šaran', '🐟', 10),
        ('stuka', 'Štuka', '🦈', 20),
        ('som', 'Som', '🐋', 30),
        ('pastrmka', 'Pastrmka', '🐠', 40),
        ('bijela', 'Bijela riba', '⚪', 50),
    ]
    for code, naziv, emoji, red in defaults:
        FishType.objects.get_or_create(
            code=code,
            defaults={'naziv': naziv, 'emoji': emoji, 'redoslijed': red, 'aktivan': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0135_alter_sitesettings_product_dwell_popup_aktivan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorBeginnerFishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Interni kod, npr. saran, stuka, som, pastrmka, bijela.', max_length=40, unique=True, verbose_name='Kod')),
                ('naziv', models.CharField(max_length=100, verbose_name='Naziv')),
                ('emoji', models.CharField(blank=True, default='', max_length=8, verbose_name='Emoji')),
                ('redoslijed', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('aktivan', models.BooleanField(default=True, verbose_name='Aktivan')),
            ],
            options={
                'verbose_name': 'Početnik — vrsta ribolova',
                'verbose_name_plural': 'Početnik — vrste ribolova',
                'ordering': ['redoslijed', 'naziv'],
            },
        ),
        migrations.CreateModel(
            name='AdvisorBeginnerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(help_text='Npr. Osnovni komplet, Srednji, Napredni…', max_length=120, verbose_name='Naziv seta')),
                ('emoji', models.CharField(blank=True, default='', max_length=8, verbose_name='Emoji')),
                ('popis', models.TextField(blank=True, help_text='Samo za admin / internu napomenu. Na sajtu se ne mora prikazati.', verbose_name='Kratki opis (opcionalno)')),
                ('popust_postotak', models.DecimalField(blank=True, decimal_places=2, help_text='Opcionalno. Npr. 10 = −10% na cijeli set. Prazno = bez popusta.', max_digits=5, null=True, verbose_name='Popust na set (%)')),
                ('redoslijed', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('aktivan', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setovi', to='EcommerceApp.advisorbeginnerfishtype', verbose_name='Vrsta ribolova')),
            ],
            options={
                'verbose_name': 'Početnik — set',
                'verbose_name_plural': 'Početnik — setovi',
                'ordering': ['fish_type__redoslijed', 'redoslijed', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdvisorBeginnerSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.PositiveSmallIntegerField(default=1, verbose_name='Količina')),
                ('redoslijed', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_beginner_set_items', to='EcommerceApp.product', verbose_name='Artikal')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='EcommerceApp.advisorbeginnerset', verbose_name='Set')),
            ],
            options={
                'verbose_name': 'Stavka seta',
                'verbose_name_plural': 'Stavke seta',
                'ordering': ['redoslijed', 'id'],
                'unique_together': {('set', 'product')},
            },
        ),
        migrations.RunPython(seed_fish_types, migrations.RunPython.noop),
    ]
