# Generated by Django 6.0.6 on 2026-07-14 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0137_advisor_fish_types_smud_vise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorbeginnersetitem',
            name='product',
            field=models.ForeignKey(limit_choices_to={'aktivan': True, 'na_stanju': True}, on_delete=django.db.models.deletion.CASCADE, related_name='advisor_beginner_set_items', to='EcommerceApp.product', verbose_name='Artikal'),
        ),
    ]
