# Generated by Django 6.0.6 on 2026-07-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0138_beginner_set_item_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='livevisitor',
            name='savjetnik',
            field=models.JSONField(blank=True, default=dict, help_text='Live stanje savjetnika: answers, step, offer_shown, offer_accepted, set_names…', verbose_name='Ribolovački savjetnik'),
        ),
        migrations.AlterField(
            model_name='staffsiteevent',
            name='tip',
            field=models.CharField(choices=[('online', 'Online na sajtu'), ('cart', 'Dodano u korpu'), ('register', 'Registracija'), ('purchase', 'Kupovina'), ('offer', 'Prihvaćena ponuda'), ('advisor', 'Ribolovački savjetnik')], db_index=True, max_length=20),
        ),
    ]
