# Generated by Django 6.0.6 on 2026-07-16 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0140_advisor_set_types_rename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisorbeginnerfishtype',
            options={'ordering': ['redoslijed', 'naziv'], 'verbose_name': 'Savjetnik — tip seta', 'verbose_name_plural': 'Savjetnik — tipovi setova'},
        ),
        migrations.AlterField(
            model_name='advisorbeginnerfishtype',
            name='code',
            field=models.SlugField(help_text='Interni kod, npr. saranski, feeder, plovak. Za varaličarski: stuka, som, ul (grupišu se u chatu).', max_length=40, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='advisorbeginnerset',
            name='fish_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setovi', to='EcommerceApp.advisorbeginnerfishtype', verbose_name='Tip seta'),
        ),
    ]
