# Generated by Django 6.0.6 on 2026-07-16 06:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def copy_m2m_to_dwell_items(apps, schema_editor):
    SiteSettings = apps.get_model('EcommerceApp', 'SiteSettings')
    ProductDwellItem = apps.get_model('EcommerceApp', 'ProductDwellItem')
    for s in SiteSettings.objects.all():
        default_pct = s.product_dwell_popust or Decimal('10.00')
        for product in s.product_dwell_artikli.all():
            ProductDwellItem.objects.get_or_create(
                settings_id=s.pk,
                product_id=product.pk,
                defaults={'popust': default_pct},
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0141_alter_advisorbeginnerfishtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='product_dwell_artikli',
            field=models.ManyToManyField(blank=True, help_text='Zastarjelo: koristi tabelu „AI dwell artikli” ispod s popustom po artiklu. Ako je ta tabela prazna i ova lista prazna — radi na SVIM artiklima.', related_name='dwell_flash_sitesettings', to='EcommerceApp.product', verbose_name='AI dwell — artikli (stara lista)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_dwell_popup_aktivan',
            field=models.BooleanField(default=False, help_text='Čim kupac uđe na artikal: NEMA popup-a. Odmah se precrta stara cijena, pojavi se snizena i odbrojavanje 2 min. Kad istekne — u toj posjeti više nema ponude, samo regularna cijena. Dok traje može izaći i vratiti se. Popust po artiklu unosiš u tabeli ispod (ili default ispod).', verbose_name='AI dwell (odmah na artiklu) aktivan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_dwell_popust',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('10.00'), help_text='Default flash popust ako artikal nema svoj unos, ili kad lista artikala nije postavljena (svi artikli). Max 50%.', max_digits=5, null=True, verbose_name='AI dwell — default popust (%)'),
        ),
        migrations.CreateModel(
            name='ProductDwellItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popust', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Flash popust samo za ovaj artikal (0.01–50).', max_digits=5, verbose_name='Popust (%)')),
                ('product', models.ForeignKey(limit_choices_to={'aktivan': True}, on_delete=django.db.models.deletion.CASCADE, related_name='dwell_items', to='EcommerceApp.product', verbose_name='Artikal')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dwell_items', to='EcommerceApp.sitesettings', verbose_name='Postavke')),
            ],
            options={
                'verbose_name': 'AI dwell artikal',
                'verbose_name_plural': 'AI dwell artikli',
                'ordering': ['product__naziv'],
                'unique_together': {('settings', 'product')},
            },
        ),
        migrations.RunPython(copy_m2m_to_dwell_items, noop_reverse),
    ]
