# Generated by Django 6.0.6 on 2026-07-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0142_product_dwell_item_per_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='javno_online_posjetioci',
            field=models.BooleanField(default=False, help_text='Uključeno: svi posjetioci vide koliko ljudi je trenutno na sajtu (grad / gost ili kupac — bez emaila i punog imena). Isključeno: samo superuser vidi uživo analitiku u admin panelu.', verbose_name='Javno prikaži ko je na sajtu'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='savjetnik_aktivan',
            field=models.BooleanField(default=True, help_text='Uključeno: svi posjetioci vide „Savjeti pri kupovini” (chat). Isključeno: savjetnik se ne prikazuje na sajtu.', verbose_name='Ribolovački savjetnik aktivan'),
        ),
    ]
