# Generated by Django 6.0.6 on 2026-07-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0143_savjetnik_and_public_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='popust_detalji',
            field=models.JSONField(blank=True, default=list, help_text='Lista {opis, iznos} za kupon, recovery, nagradu…', verbose_name='Detalji popusta na narudžbi'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bazna_cijena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cijena prije sniženja na ovoj stavci (ako postoji popust).', max_digits=10, null=True, verbose_name='Regularna cijena (jed.)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='popust_iznos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ukupna ušteda na stavci (sve komade) u odnosu na regularnu cijenu.', max_digits=10, null=True, verbose_name='Ušteda ukupno (KM)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='popust_opis',
            field=models.CharField(blank=True, help_text='Npr. AI dwell −10%, Akcija Timer, Live ponuda, Bundle…', max_length=300, verbose_name='Izvor popusta'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='popust_postotak',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Popust (%)'),
        ),
    ]
