# Generated by Django 6.0.6 on 2026-07-17 13:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0144_order_discount_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdwellitem',
            name='product',
            field=models.ForeignKey(limit_choices_to={'aktivan': True, 'na_stanju': True}, on_delete=django.db.models.deletion.CASCADE, related_name='dwell_items', to='EcommerceApp.product', verbose_name='Artikal'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_dwell_artikli',
            field=models.ManyToManyField(blank=True, help_text='Više se ne koristi. Unosi se u tabeli ProductDwellItem (popust po artiklu).', related_name='dwell_flash_sitesettings', to='EcommerceApp.product', verbose_name='AI dwell — artikli (ugašeno)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_dwell_popup_aktivan',
            field=models.BooleanField(default=False, help_text='Čim kupac uđe na artikal: NEMA popup-a. Odmah se precrta stara cijena, pojavi se snizena i odbrojavanje 2 min. Kad istekne — u toj posjeti više nema ponude. Artikle i % popusta unosiš u tabeli „AI dwell artikli” (po artiklu).', verbose_name='AI dwell (odmah na artiklu) aktivan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_dwell_popust',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('10.00'), help_text='Fallback % ako unos u tabeli artikala nema popust. Flash radi samo na artiklima dodanim u tabelu „AI dwell artikli”. Max 50%.', max_digits=5, null=True, verbose_name='AI dwell — default popust (%)'),
        ),
    ]
