# Generated by Django 6.0.6 on 2026-07-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0145_product_dwell_only_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_accent',
            field=models.CharField(blank=True, default='#e11d48', max_length=7, verbose_name='AI dwell — accent linija / accent'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_badge_bg',
            field=models.CharField(blank=True, default='#be123c', max_length=7, verbose_name='AI dwell — boja % badge (pozadina)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_badge_tekst',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='AI dwell — boja % badge (tekst)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_border',
            field=models.CharField(blank=True, default='#e11d48', max_length=7, verbose_name='AI dwell — rub boxa'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_box',
            field=models.CharField(blank=True, default='#111827', help_text='Hex npr. #111827', max_length=7, verbose_name='AI dwell — pozadina boxa (detalj)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_box2',
            field=models.CharField(blank=True, default='#1f2937', help_text='Druga boja gradijenta. Prazno = ista kao prva.', max_length=7, verbose_name='AI dwell — pozadina boxa 2 (gradijent)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_kartica_badge_bg',
            field=models.CharField(blank=True, default='#be123c', max_length=7, verbose_name='AI dwell kartica — % badge pozadina'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_kartica_badge_tekst',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='AI dwell kartica — % badge tekst'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_kartica_bg',
            field=models.CharField(blank=True, default='#fff7f8', max_length=7, verbose_name='AI dwell kartica — pozadina'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_kartica_bg2',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='AI dwell kartica — pozadina 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_kartica_border',
            field=models.CharField(blank=True, default='#e11d48', max_length=7, verbose_name='AI dwell kartica — rub'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_kartica_label',
            field=models.CharField(blank=True, default='#be123c', max_length=7, verbose_name='AI dwell kartica — boja labele'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_kartica_nova',
            field=models.CharField(blank=True, default='#e11d48', max_length=7, verbose_name='AI dwell kartica — nova cijena'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_kartica_stara',
            field=models.CharField(blank=True, default='#64748b', max_length=7, verbose_name='AI dwell kartica — stara cijena'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_nova_cijena',
            field=models.CharField(blank=True, default='#e11d48', max_length=7, verbose_name='AI dwell — boja nove cijene (detalj)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_nova_cijena_pulse',
            field=models.CharField(blank=True, default='#ff1f4b', help_text='Boja na vrhuncu pulsiranja nove cijene.', max_length=7, verbose_name='AI dwell — boja pulse (vrh animacije)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_stara_cijena',
            field=models.CharField(blank=True, default='#94a3b8', max_length=7, verbose_name='AI dwell — boja stare cijene (detalj)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_tag_bg',
            field=models.CharField(blank=True, default='#e11d48', max_length=7, verbose_name='AI dwell — boja badge pozadine'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_tag_tekst',
            field=models.CharField(blank=True, default='#fecdd3', max_length=7, verbose_name='AI dwell — boja badge teksta'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_timer_bg',
            field=models.CharField(blank=True, default='#e11d48', max_length=7, verbose_name='AI dwell — boja tajmera (pozadina)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_timer_label',
            field=models.CharField(blank=True, default='#cbd5e1', max_length=7, verbose_name='AI dwell — boja labele tajmera'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_boja_timer_tekst',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='AI dwell — boja tajmera (broj)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_catalog_label',
            field=models.CharField(blank=True, default='', help_text='Opcionalno iznad cijene na listi (npr. „Akcija”). Prazno = bez labele.', max_length=40, verbose_name='AI dwell — labela na kartici (katalog)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_flash_seconds',
            field=models.PositiveIntegerField(default=120, help_text='Koliko traje snizena cijena na product page (npr. 120 = 2 min). Min 30, max 3600.', verbose_name='AI dwell — trajanje tajmera (sekundi)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_sale_pulse',
            field=models.BooleanField(default=True, help_text='Uključeno: nova (crvena) cijena blago pulira. Isključeno: mirna boja.', verbose_name='AI dwell — pulsirajuća nova cijena'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_tag_text',
            field=models.CharField(blank=True, default='Ograničena ponuda', help_text='Npr. „Ograničena ponuda”. Prazno = sakrij badge.', max_length=60, verbose_name='AI dwell — badge tekst (detalj)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_dwell_timer_label',
            field=models.CharField(blank=True, default='Ističe za', help_text='Tekst pored odbrojavanja na product page.', max_length=60, verbose_name='AI dwell — labela tajmera'),
        ),
    ]
