# Generated by Django 6.0.6 on 2026-07-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0146_product_dwell_ui_editable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiprodajasettings',
            options={'verbose_name': 'AI prodaja / AI dwell', 'verbose_name_plural': 'AI prodaja / AI dwell'},
        ),
        migrations.AlterField(
            model_name='akcija',
            name='tip',
            field=models.CharField(choices=[('bundle', 'Pop-up bundle'), ('qty_deal', 'Kupi više (količinski %)'), ('ai_prodaja', 'AI prodaja / AI dwell'), ('slika', 'Pop-up + slika (zastarjelo)'), ('timer', 'Akcija + tajmer (zastarjelo)'), ('x_plus_1', 'X+1 prodaja (zastarjelo)'), ('uslov', 'Uslov prodaja (zastarjelo)'), ('korpa_nudjenje', 'Korpa nudjenje (zastarjelo)'), ('gratis', '+ Gratis (zastarjelo)')], default='bundle', max_length=16, verbose_name='Tip akcije'),
        ),
    ]
