# Generated by Django 6.0.6 on 2026-07-21 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0148_akcija_tip_ponuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='boja_dugme_banner',
            field=models.CharField(blank=True, default='#ff9500', help_text='CTA na hero/grid/featured bannerima. Hex npr. #ff9500', max_length=7, verbose_name='Boja dugmadi na bannerima'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='boja_dugme_banner_hover',
            field=models.CharField(blank=True, default='#e68600', help_text='Hex npr. #e68600', max_length=7, verbose_name='Boja banner dugmadi hover'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='boja_dugme_korpa',
            field=models.CharField(blank=True, default='#5BB805', help_text='Zelena na karticama artikala. Hex npr. #5BB805', max_length=7, verbose_name='Boja „Dodaj u korpu” (kartice)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='boja_dugme_korpa_hover',
            field=models.CharField(blank=True, default='#4fa104', help_text='Boja na prelazak miša. Hex npr. #4fa104', max_length=7, verbose_name='Boja „Dodaj u korpu” hover'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kontakt_boja_messenger',
            field=models.CharField(blank=True, default='#0084ff', help_text='Hex npr. #0084ff', max_length=7, verbose_name='Boja Messenger dugmeta'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kontakt_boja_viber',
            field=models.CharField(blank=True, default='#665cac', help_text='Hex npr. #665cac', max_length=7, verbose_name='Boja Viber dugmeta'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kontakt_boja_whatsapp',
            field=models.CharField(blank=True, default='#25d366', help_text='Hex npr. #25d366', max_length=7, verbose_name='Boja WhatsApp dugmeta'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kontakt_prikazi_messenger',
            field=models.BooleanField(default=True, verbose_name='Prikaži Messenger dugme'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kontakt_prikazi_viber',
            field=models.BooleanField(default=True, verbose_name='Prikaži Viber dugme'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kontakt_prikazi_whatsapp',
            field=models.BooleanField(default=True, verbose_name='Prikaži WhatsApp dugme'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='noviteti_mod',
            field=models.CharField(choices=[('auto', 'Automatski — zadnjih 10 unesenih'), ('manual', 'Ručno — odaberi do 10 artikala')], default='auto', help_text='Automatski: zadnjih 10 unesenih artikala. Ručno: artikli koje unesete u tabeli „Noviteti na početnoj” ispod (do 10).', max_length=10, verbose_name='Noviteti — način prikaza'),
        ),
        migrations.CreateModel(
            name='HomeNovoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redoslijed', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('aktivan', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('artikal', models.ForeignKey(limit_choices_to={'aktivan': True}, on_delete=django.db.models.deletion.CASCADE, related_name='noviteti_na_pocetnoj', to='EcommerceApp.product', verbose_name='Postojeći artikal')),
                ('postavke', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='noviteti_artikli', to='EcommerceApp.sitesettings')),
            ],
            options={
                'verbose_name': 'Novitet (početna)',
                'verbose_name_plural': 'Noviteti na početnoj (ručno)',
                'ordering': ['redoslijed', 'id'],
            },
        ),
    ]
