# Generated by Django 6.0.6 on 2026-07-21 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0150_alter_akcija_artikal_alter_akcija_gratis_artikal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akcija',
            name='artikal',
            field=models.ForeignKey(blank=True, help_text='Za + Ponuda: trigger artikal — popup iskače samo kad se doda u korpu. Za Pop-up bundle: samo ako je trigger „odabrani trigger artikal”. Za „Kupi više”: artikal na koji važi količinski popust.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='akcije', to='EcommerceApp.product', verbose_name='Artikal'),
        ),
        migrations.AlterField(
            model_name='akcija',
            name='gratis_artikal',
            field=models.ForeignKey(blank=True, help_text='Za + Ponuda: artikal koji se nudi u popup-u (stil kao AI dwell) nakon dodavanja trigger artikla u korpu. Ako uneseš Popust (%), nudi se sa sniženjem; prazno = regularna cijena.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='akcije_gratis', to='EcommerceApp.product', verbose_name='Ponuda artikal'),
        ),
    ]
