# Generated by Django 6.0.6 on 2026-07-21 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0151_alter_akcija_artikal_alter_akcija_gratis_artikal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akcija',
            name='artikal',
            field=models.ForeignKey(blank=True, help_text='+ Ponuda: artikal koji kupac dodaje u korpu — tada iskače popup. Kupi više: artikal na koji važi količinski popust. Bundle: samo ako je trigger „odabrani trigger artikal”.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='akcije', to='EcommerceApp.product', verbose_name='1. Trigger artikal'),
        ),
        migrations.AlterField(
            model_name='akcija',
            name='gratis_artikal',
            field=models.ForeignKey(blank=True, help_text='+ Ponuda: artikal koji se nudi u popupu (AI dwell stil) nakon dodavanja triggera. Obavezno za + Ponuda.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='akcije_gratis', to='EcommerceApp.product', verbose_name='3. Ponuda artikal (popup)'),
        ),
        migrations.AlterField(
            model_name='akcija',
            name='popust_postotak',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='+ Ponuda: % snizenja na ponuđeni artikal; prazno = regularna cijena. Pop-up bundle: % na cijeli set (ako linija nema svoj %). Kupi više: % unosi se u polja „Kupi 2/3/… komada”, ne ovdje.', max_digits=5, null=True, verbose_name='2. Popust (%) — opcionalno'),
        ),
    ]
