# Generated by Django 6.0.6 on 2026-07-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0152_alter_akcija_artikal_alter_akcija_gratis_artikal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='je_novitet',
            field=models.BooleanField(default=False, help_text='Uključeno: zeleni pulsirajući natpis „NOVITETI” na artiklu i prikaz u karuselu Noviteti na početnoj.', verbose_name='Noviteti'),
        ),
    ]
