# Generated by Django 6.0.6 on 2026-07-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0153_product_je_novitet'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='je_hit',
            field=models.BooleanField(default=False, help_text='Uključeno: crveni pulsirajući natpis „HIT PONUDA” na artiklu i prikaz u karuselu Izdvojeni artikli na početnoj.', verbose_name='HIT ponuda / Izdvojeno'),
        ),
    ]
