# Generated by Django 6.0.6 on 2026-07-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0154_product_je_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='promo_bar_link_tekst',
            field=models.CharField(blank=True, default='Pridruži se sada', max_length=80, verbose_name='Promo traka — link tekst'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_bar_tekst',
            field=models.CharField(blank=True, default='Besplatna dostava za narudžbe iznad 250 KM', help_text='Tekst u gornjoj sivoj traci (iznad headera).', max_length=200, verbose_name='Promo traka — tekst'),
        ),
    ]
