# Generated by Django 6.0.6 on 2026-07-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0155_site_promo_bar_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tekst_dugme_korpa',
            field=models.CharField(blank=True, default='Dodaj u korpu', help_text='Tekst na dugmetu na karticama i detail stranici.', max_length=40, verbose_name='Tekst „Dodaj u korpu”'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tekst_dugme_rasprodato',
            field=models.CharField(blank=True, default='Rasprodato', max_length=40, verbose_name='Tekst „Rasprodato”'),
        ),
    ]
