# Generated by Django 6.0.6 on 2026-07-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0157_product_prioritet_lagera'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBrandShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(blank=True, help_text='Prazno = naziv brenda.', max_length=120, verbose_name='Naslov sekcije')),
                ('redoslijed', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('aktivan', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocetna_sekcije', to='EcommerceApp.brand', verbose_name='Brend')),
                ('postavke', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='brendovi_na_pocetnoj', to='EcommerceApp.sitesettings')),
            ],
            options={
                'verbose_name': 'Brend na početnoj (slide)',
                'verbose_name_plural': 'Brendovi na početnoj (slide karusel)',
                'ordering': ['redoslijed', 'id'],
                'unique_together': {('postavke', 'brend')},
            },
        ),
    ]
