# Generated by Django 6.0.6 on 2026-07-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0161_sitesettings_logo_glavni_sajt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telefon_verifikovan',
            field=models.BooleanField(default=False, help_text='Potvrđeno da broj pripada kupcu (kod poslan preko Vibera).', verbose_name='Telefon verifikovan (Viber)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefon_verifikovan_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Telefon verifikovan u'),
        ),
    ]
