# Generated by Django 6.0.6 on 2026-07-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0163_category_search_tagovi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='search_tagovi',
            field=models.TextField(blank=True, help_text='Samo za podkategorije (ne za glavne kategorije). Neograničen broj riječi za pretragu — odvoji zarezom ili novim redom (npr. masinica, masince, rola, role, feeder, štap). Vrijedi za artikle u ovoj podkategoriji i njenim podnivoima.', verbose_name='Search tagovi'),
        ),
    ]
