# Generated by Django 6.0.6 on 2026-07-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0164_alter_category_search_tagovi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='search_tagovi',
            field=models.TextField(blank=True, help_text='Samo za podkategorije. Neograničen broj tagova — odvoji zarezom ili novim redom. Duga rečenica je JEDAN tag (razmaci ostaju), npr. „stap za pecanje sarana”. Zarez tek dijeli sljedeći tag. Vrijedi za artikle u ovoj podkategoriji i podnivoima.', verbose_name='Search tagovi'),
        ),
    ]
