# Generated by Django 6.0.6 on 2026-07-31 07:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0165_alter_category_search_tagovi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdwellitem',
            name='popust',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('10.00'), help_text='0–50. Prazno = default iz AI dwell postavki. 0 = bez popusta (nema −% / precrtane cijene).', max_digits=5, null=True, verbose_name='Popust (%)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='browse_interest_popup_aktivan',
            field=models.BooleanField(default=True, help_text='AI prati kupca (šta gleda, koliko dugo, skoro-korpa) i u pravom trenutku šalje popup ponudu na 1–2 artikla. Max 2 ponude po posjeti, s razmakom. Popust % podesi ispod — 0 = ponuda bez popusta.', verbose_name='AI prodaja aktivna'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='browse_interest_popust',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('10.00'), help_text='Popust na automatsku ponudu (0–50). 0 = samo preporuka / ponuda, bez sniženja cijene. Npr. 5, 10, 15…', max_digits=5, null=True, verbose_name='AI prodaja — popust (%)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='korpa_exit_popup_popust',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcionalno (0–50). Prazno ili 0 = ponuda bez popusta (nema −% / „akcija” teksta). Unesi % samo ako želiš sniženje.', max_digits=5, null=True, verbose_name='Exit popup popust (%)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_dwell_popust',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('10.00'), help_text='Fallback % ako unos u tabeli artikala nema popust (0–50). Prazno ili 0 = bez popusta (nema −% / precrtane cijene). Flash samo na artiklima u tabeli „AI dwell artikli”.', max_digits=5, null=True, verbose_name='AI dwell — default popust (%)'),
        ),
    ]
