# Generated by Django 6.0.6 on 2026-07-31 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0166_productdwellitem_popust_allow_zero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='akcijabundleline',
            name='product',
            field=models.ForeignKey(limit_choices_to={'aktivan': True, 'na_stanju': True}, on_delete=django.db.models.deletion.CASCADE, related_name='akcija_bundle_lines', to='EcommerceApp.product', verbose_name='Artikal'),
        ),
        migrations.CreateModel(
            name='LoyaltyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Iznos (KM)')),
                ('napomena', models.CharField(blank=True, max_length=200, verbose_name='Napomena')),
                ('kreirano', models.DateTimeField(auto_now_add=True, verbose_name='Datum')),
                ('kartica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidentirane_kupovine', to='EcommerceApp.loyaltycard', verbose_name='Loyalty kartica')),
                ('kreirao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_evidentirane_kupovine', to=settings.AUTH_USER_MODEL, verbose_name='Evidentirao')),
            ],
            options={
                'verbose_name': 'Evidentirana loyalty kupovina',
                'verbose_name_plural': 'Evidentirane loyalty kupovine',
                'ordering': ['-kreirano'],
            },
        ),
    ]
