# Generated by Django 6.0.6 on 2026-07-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0167_loyalty_purchase_and_bundle_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltypurchase',
            name='verifikacija',
            field=models.CharField(choices=[('otp', 'Kod (Viber/WhatsApp)'), ('admin', 'Admin override (bez koda)')], default='otp', help_text='otp = 4-cifreni kod poslan kupcu; admin = bez koda (nema internet).', max_length=10, verbose_name='Način potvrde'),
        ),
    ]
