# Generated by Django 6.0.6 on 2026-08-01 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0168_loyalty_purchase_otp_verifikacija'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='EcommerceApp.product', verbose_name='Artikal (ponuda)'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='product_bazna_cijena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Regularna cijena (KM)'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='product_cijena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cijena ponude (KM)'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='product_popust_postotak',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcionalno. Prazno ili 0 = regularna cijena.', max_digits=5, null=True, verbose_name='Popust na artikal (%)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_delay_seconds',
            field=models.PositiveIntegerField(default=120, help_text='Koliko sekundi posjetilac mora biti na sajtu prije nego chat iskoči. Npr. 120 = 2 minute.', verbose_name='Chat — vrijeme do pojave (sekunde)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_pozdrav_poruka',
            field=models.TextField(blank=True, default='Zdravo! 👋 Dobrodošli na opremazaribolov.ba.\n\nTreba li vam pomoć ili preporuka pri kupovini?\nPišite nam — tu smo da pomognemo.', help_text='Poruka koju sistem šalje kad se chat otvori. Kupac odmah može odgovoriti (bez registracije).', verbose_name='Chat — automatska pozdrav poruka'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_sa_kupcem_aktivan',
            field=models.BooleanField(default=True, help_text='Uključeno: poslije određenog vremena na sajtu automatski se otvara chat, pozdravlja kupca i nudi pomoć. Chat se ne prikazuje dok ne istekne vrijeme. Isključeno: nema proaktivnog chata (staff i dalje može imati inbox).', verbose_name='Chat sa kupcem aktivan'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
