# Generated by Django 6.0.6 on 2026-08-01 09:53
# Made idempotent: production may already have some columns (e.g. search_document)
# without django_migrations recording 0170 as applied.

from django.db import migrations, models


def _pg_table(name: str) -> str:
    return f'"EcommerceApp_{name}"'


def add_search_columns_if_missing(apps, schema_editor):
    """Add search columns / index only if they do not already exist."""
    connection = schema_editor.connection
    vendor = connection.vendor

    product_cols = {
        'barkod_normalized': "varchar(80) DEFAULT '' NOT NULL",
        'naziv_normalized': "varchar(220) DEFAULT '' NOT NULL",
        'search_document': "text DEFAULT '' NOT NULL",
        'sifra_normalized': "varchar(80) DEFAULT '' NOT NULL",
    }
    variation_cols = {
        'naziv_normalized': "varchar(120) DEFAULT '' NOT NULL",
        'sifra_normalized': "varchar(80) DEFAULT '' NOT NULL",
    }

    with connection.cursor() as cursor:
        if vendor == 'postgresql':
            def existing_columns(table: str) -> set[str]:
                cursor.execute(
                    """
                    SELECT column_name
                    FROM information_schema.columns
                    WHERE table_name = %s
                    """,
                    [table],
                )
                return {row[0] for row in cursor.fetchall()}

            # Django default table names
            prod_table = 'EcommerceApp_product'
            var_table = 'EcommerceApp_productvariation'
            prod_existing = existing_columns(prod_table)
            var_existing = existing_columns(var_table)

            for col, ddl in product_cols.items():
                if col not in prod_existing:
                    cursor.execute(
                        f'ALTER TABLE {_pg_table("product")} '
                        f'ADD COLUMN "{col}" {ddl}'
                    )

            for col, ddl in variation_cols.items():
                if col not in var_existing:
                    cursor.execute(
                        f'ALTER TABLE {_pg_table("productvariation")} '
                        f'ADD COLUMN "{col}" {ddl}'
                    )

            # Indexes (IF NOT EXISTS)
            cursor.execute(
                'CREATE INDEX IF NOT EXISTS product_active_stock_idx '
                f'ON {_pg_table("product")} (aktivan, na_stanju)'
            )
            cursor.execute(
                f'CREATE INDEX IF NOT EXISTS "EcommerceApp_product_naziv_normalized_idx" '
                f'ON {_pg_table("product")} (naziv_normalized)'
            )
            cursor.execute(
                f'CREATE INDEX IF NOT EXISTS "EcommerceApp_product_sifra_normalized_idx" '
                f'ON {_pg_table("product")} (sifra_normalized)'
            )
            cursor.execute(
                f'CREATE INDEX IF NOT EXISTS "EcommerceApp_product_barkod_normalized_idx" '
                f'ON {_pg_table("product")} (barkod_normalized)'
            )
            cursor.execute(
                f'CREATE INDEX IF NOT EXISTS "EcommerceApp_productvariation_naziv_normalized_idx" '
                f'ON {_pg_table("productvariation")} (naziv_normalized)'
            )
            cursor.execute(
                f'CREATE INDEX IF NOT EXISTS "EcommerceApp_productvariation_sifra_normalized_idx" '
                f'ON {_pg_table("productvariation")} (sifra_normalized)'
            )
            return

        # SQLite / others
        def sqlite_columns(table: str) -> set[str]:
            cursor.execute(f'PRAGMA table_info("{table}")')
            return {row[1] for row in cursor.fetchall()}

        prod_table = 'EcommerceApp_product'
        var_table = 'EcommerceApp_productvariation'
        prod_existing = sqlite_columns(prod_table)
        var_existing = sqlite_columns(var_table)

        for col, ddl in product_cols.items():
            if col not in prod_existing:
                # SQLite: simpler types
                if 'text' in ddl:
                    cursor.execute(
                        f'ALTER TABLE "{prod_table}" ADD COLUMN "{col}" text DEFAULT \'\''
                    )
                else:
                    max_len = '220' if '220' in ddl else '80'
                    cursor.execute(
                        f'ALTER TABLE "{prod_table}" ADD COLUMN "{col}" '
                        f'varchar({max_len}) DEFAULT \'\''
                    )

        for col, ddl in variation_cols.items():
            if col not in var_existing:
                max_len = '120' if '120' in ddl else '80'
                cursor.execute(
                    f'ALTER TABLE "{var_table}" ADD COLUMN "{col}" '
                    f'varchar({max_len}) DEFAULT \'\''
                )


def noop_reverse(apps, schema_editor):
    # Do not drop columns on reverse — may be in use / partially present
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0169_chat_settings_and_product_offer'),
    ]

    operations = [
        # Database: idempotent ADD COLUMN IF missing
        migrations.RunPython(add_search_columns_if_missing, noop_reverse),
        # State: keep Django model state in sync (no-op on DB when already applied
        # via SeparateDatabaseAndState — but fields may already exist, so we only
        # update project state when this migration is first recorded).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='product',
                    name='barkod_normalized',
                    field=models.CharField(
                        blank=True, db_index=True, default='', editable=False, max_length=80,
                    ),
                ),
                migrations.AddField(
                    model_name='product',
                    name='naziv_normalized',
                    field=models.CharField(
                        blank=True, db_index=True, default='', editable=False, max_length=220,
                    ),
                ),
                migrations.AddField(
                    model_name='product',
                    name='search_document',
                    field=models.TextField(
                        blank=True,
                        default='',
                        editable=False,
                        help_text=(
                            'Normalizovani blob za pretragu '
                            '(naziv, šifra, barkod, brend, kategorija, tagovi, varijacije).'
                        ),
                    ),
                ),
                migrations.AddField(
                    model_name='product',
                    name='sifra_normalized',
                    field=models.CharField(
                        blank=True, db_index=True, default='', editable=False, max_length=80,
                    ),
                ),
                migrations.AddField(
                    model_name='productvariation',
                    name='naziv_normalized',
                    field=models.CharField(
                        blank=True, db_index=True, default='', editable=False, max_length=120,
                    ),
                ),
                migrations.AddField(
                    model_name='productvariation',
                    name='sifra_normalized',
                    field=models.CharField(
                        blank=True, db_index=True, default='', editable=False, max_length=80,
                    ),
                ),
                migrations.AddIndex(
                    model_name='product',
                    index=models.Index(
                        fields=['aktivan', 'na_stanju'],
                        name='product_active_stock_idx',
                    ),
                ),
            ],
            database_operations=[],  # already handled by RunPython above
        ),
    ]
