# Generated by Django 6.0.6 on 2026-08-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0169_chat_settings_and_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barkod_normalized',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='naziv_normalized',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=220),
        ),
        migrations.AddField(
            model_name='product',
            name='search_document',
            field=models.TextField(blank=True, default='', editable=False, help_text='Normalizovani blob za pretragu (naziv, šifra, barkod, brend, kategorija, tagovi, varijacije).'),
        ),
        migrations.AddField(
            model_name='product',
            name='sifra_normalized',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='naziv_normalized',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='sifra_normalized',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=80),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['aktivan', 'na_stanju'], name='product_active_stock_idx'),
        ),
    ]
