# Generated by Django 6.0.6 on 2026-08-01 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0170_product_search_normalized_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSynonymGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100, verbose_name='Naziv grupe')),
                ('aktivno', models.BooleanField(db_index=True, default=True, verbose_name='Aktivno')),
                ('prioritet', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Veći broj = važnija grupa pri rješavanju preklapanja. Ne digne sinonim iznad tačne šifre/naziva.', verbose_name='Prioritet')),
                ('azurirano', models.DateTimeField(auto_now=True, verbose_name='Datum izmjene')),
            ],
            options={
                'verbose_name': 'Search — grupa sinonima',
                'verbose_name_plural': 'Search — grupe sinonima',
                'ordering': ['-prioritet', 'naziv'],
            },
        ),
        migrations.CreateModel(
            name='SearchSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojam', models.CharField(max_length=80, verbose_name='Pojam')),
                ('normalizovani_pojam', models.CharField(blank=True, db_index=True, help_text='Automatski se puni (mala slova, bez dijakritika).', max_length=80, verbose_name='Normalizovani pojam')),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinonimi', to='EcommerceApp.searchsynonymgroup', verbose_name='Grupa')),
            ],
            options={
                'verbose_name': 'Search — sinonim',
                'verbose_name_plural': 'Search — sinonimi',
                'ordering': ['grupa__naziv', 'pojam'],
                'constraints': [models.UniqueConstraint(fields=('grupa', 'normalizovani_pojam'), name='uniq_search_synonym_group_norm')],
            },
        ),
    ]
