# Generated by Django 6.0.6 on 2026-08-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0171_product_search_keywords_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livevisitor',
            name='izvor_dolaska',
            field=models.CharField(blank=True, db_index=True, help_text='direct | google | google_ads | facebook | facebook_ads | instagram | instagram_ads | other', max_length=32, verbose_name='Izvor dolaska'),
        ),
    ]
