# Generated by Django 6.0.6 on 2026-08-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0172_search_synonym_seed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchsynonymgroup',
            name='naziv',
            field=models.CharField(max_length=100, unique=True, verbose_name='Naziv grupe'),
        ),
    ]
