# Generated by Django 6.0.6 on 2026-08-04 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0172_livevisitor_izvor_dolaska_expand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uvoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200, verbose_name='Naziv uvoza')),
                ('fajl_naziv', models.CharField(blank=True, max_length=255, verbose_name='Ime fajla')),
                ('napomena', models.TextField(blank=True, verbose_name='Napomena')),
                ('kreiran', models.DateTimeField(auto_now_add=True, verbose_name='Kreiran')),
                ('azuriran', models.DateTimeField(auto_now=True, verbose_name='Ažuriran')),
                ('broj_redova', models.PositiveIntegerField(default=0, verbose_name='Broj redova')),
                ('broj_azurirano', models.PositiveIntegerField(default=0, verbose_name='Ažurirano artikala')),
                ('broj_kreirano', models.PositiveIntegerField(default=0, verbose_name='Kreirano artikala')),
                ('broj_preskoceno', models.PositiveIntegerField(default=0, verbose_name='Preskočeno')),
                ('log_detalji', models.JSONField(blank=True, default=list, verbose_name='Log')),
                ('kreirao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uvozi', to=settings.AUTH_USER_MODEL, verbose_name='Uvezao')),
            ],
            options={
                'verbose_name': 'Uvoz',
                'verbose_name_plural': 'Uvozi',
                'ordering': ['-kreiran'],
            },
        ),
        migrations.CreateModel(
            name='UvozStavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikal_naziv', models.CharField(max_length=200, verbose_name='Artikal')),
                ('kolicina', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Količina')),
                ('fakturna', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Fakturna')),
                ('nabavna', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Nabavna')),
                ('vpc_netto', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Vpc netto')),
                ('mpc_brutto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Mpc brutto')),
                ('vpc_marza', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Vpc marža')),
                ('ukupno_fakturna', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Ukupno Fakturna')),
                ('status', models.CharField(choices=[('pending', 'Na čekanju'), ('created', 'Kreirano'), ('updated', 'Ažurirano'), ('skipped', 'Preskočeno'), ('error', 'Greška')], db_index=True, default='pending', max_length=12, verbose_name='Status')),
                ('poruka', models.CharField(blank=True, max_length=300, verbose_name='Poruka')),
                ('redoslijed', models.PositiveIntegerField(default=0, verbose_name='Red')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uvoz_stavke', to='EcommerceApp.product', verbose_name='Artikal na sajtu')),
                ('uvoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='EcommerceApp.uvoz', verbose_name='Uvoz')),
            ],
            options={
                'verbose_name': 'Stavka uvoza',
                'verbose_name_plural': 'Stavke uvoza',
                'ordering': ['redoslijed', 'id'],
            },
        ),
    ]
