# Generated by Django 6.0.6 on 2026-08-10 07:54

import django.db.models.deletion
from django.db import migrations, models


def seed_home_mockup(apps, schema_editor):
    SiteSettings = apps.get_model('EcommerceApp', 'SiteSettings')
    HomeTrustItem = apps.get_model('EcommerceApp', 'HomeTrustItem')
    HomePromoCard = apps.get_model('EcommerceApp', 'HomePromoCard')

    settings_obj, _ = SiteSettings.objects.get_or_create(pk=1)

    # Naslovi i boje kao na mockupu
    updates = {
        'naslov_izdvojeno': 'Izdvojeni',
        'podnaslov_izdvojeno': '',
        'naslov_novo': 'Noviteti',
        'podnaslov_novo': '',
        'naslov_akcija': 'Akcijska ponuda',
        'naslov_blog': 'Vlog / Blog',
        'naslov_brendovi': 'Naši brendovi',
        'tekst_pogledaj_sve': 'Pogledaj sve',
        'boja_dugme_banner': '#5BB805',
        'boja_dugme_banner_hover': '#4fa104',
        'boja_dugme_korpa': '#5BB805',
        'boja_dugme_korpa_hover': '#4fa104',
        'prikazi_newsletter': True,
        'prikazi_akcijsku_sekciju': True,
        'newsletter_naslov': 'Prijavi se na newsletter',
        'newsletter_podnaslov': (
            'Budi prvi koji će saznati za nove proizvode, akcije i savjete iz svijeta ribolova.'
        ),
        'newsletter_placeholder': 'Unesite e-mail adresu',
        'newsletter_dugme': 'Prijavi se',
        'newsletter_napomena': 'Nećemo spamovati. Odjavi se u bilo kom trenutku.',
    }
    for key, value in updates.items():
        setattr(settings_obj, key, value)
    settings_obj.save()

    if not HomeTrustItem.objects.filter(postavke_id=settings_obj.pk).exists():
        trust_defaults = [
            (0, 'truck', 'Brza dostava', '1–3 radna dana širom BiH'),
            (1, 'shield', 'Sigurna kupovina', '100% sigurno plaćanje'),
            (2, 'badge', 'Originalni proizvodi', 'Samo provjereni brendovi'),
            (3, 'support', 'Podrška 24/7', 'Tu smo za vas'),
        ]
        HomeTrustItem.objects.bulk_create([
            HomeTrustItem(
                postavke_id=settings_obj.pk,
                redoslijed=order,
                ikona=icon,
                naslov=title,
                podnaslov=sub,
                aktivan=True,
            )
            for order, icon, title, sub in trust_defaults
        ])

    if not HomePromoCard.objects.filter(postavke_id=settings_obj.pk).exists():
        promo_defaults = [
            (0, 'truck', 'Besplatna dostava', 'za narudžbe preko 150 KM', '', '/'),
            (1, 'percent', 'Vjernost se isplati', 'Sakupljaj bodove i ostvari dostatne popuste', 'DO 10%', ''),
            (2, 'gift', 'Poklon kartice', 'Savršen poklon za svakog ribolovca', '50 KM', ''),
            (3, 'tag', 'Akcije i popusti', 'Pogledaj najnovije ponude i uštedi više', 'POPUSTI', '/?akcija=1'),
        ]
        HomePromoCard.objects.bulk_create([
            HomePromoCard(
                postavke_id=settings_obj.pk,
                redoslijed=order,
                ikona=icon,
                naslov=title,
                podnaslov=sub,
                badge=badge,
                link=link,
                aktivan=True,
            )
            for order, icon, title, sub, badge, link in promo_defaults
        ])


def unseed_home_mockup(apps, schema_editor):
    # Ne brišemo sadržaj koji je korisnik možda uredio.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0173_uvoz_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homefeaturedproduct',
            options={'ordering': ['redoslijed', 'id'], 'verbose_name': 'Izdvojeni artikal (početna)', 'verbose_name_plural': 'Izdvojeni artikli (početna)'},
        ),
        migrations.AddField(
            model_name='homevlog',
            name='kratki_opis',
            field=models.CharField(blank=True, help_text='Jedna rečenica ispod naslova na početnoj. Prazno = prvih ~120 znakova iz sadržaja.', max_length=220, verbose_name='Kratki opis (početna)'),
        ),
        migrations.AddField(
            model_name='homevlog',
            name='kreirano',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='homevlog',
            name='objavljeno',
            field=models.DateField(blank=True, help_text='Prikazuje se na kartici vloga (npr. 05.08.2025). Prazno = datum kreiranja.', null=True, verbose_name='Datum objave'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='naslov_akcija',
            field=models.CharField(blank=True, default='Akcijska ponuda', help_text='Sekcija sniženih artikala na početnoj. Ostavite prazno da se naslov ne prikazuje.', max_length=120, verbose_name='Akcijska ponuda — naslov'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='naslov_brendovi',
            field=models.CharField(blank=True, default='Naši brendovi', help_text='Naslov trake brendova na dnu početne. Prazno = sakrij naslov.', max_length=120, verbose_name='Brendovi — naslov'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_dugme',
            field=models.CharField(blank=True, default='Prijavi se', max_length=40, verbose_name='Newsletter — tekst dugmeta'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_napomena',
            field=models.CharField(blank=True, default='Nećemo spamovati. Odjavi se u bilo kom trenutku.', max_length=160, verbose_name='Newsletter — napomena ispod forme'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_naslov',
            field=models.CharField(blank=True, default='Prijavi se na newsletter', max_length=120, verbose_name='Newsletter — naslov'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_placeholder',
            field=models.CharField(blank=True, default='Unesite e-mail adresu', max_length=80, verbose_name='Newsletter — placeholder u polju'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_podnaslov',
            field=models.CharField(blank=True, default='Budi prvi koji će saznati za nove proizvode, akcije i savjete iz svijeta ribolova.', max_length=240, verbose_name='Newsletter — podnaslov'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='podnaslov_akcija',
            field=models.CharField(blank=True, default='', help_text='Ostavite prazno da se podnaslov ne prikazuje.', max_length=200, verbose_name='Akcijska ponuda — podnaslov'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='prikazi_akcijsku_sekciju',
            field=models.BooleanField(default=True, help_text='Ako je uključeno, na početnoj se prikazuju artikli na akciji (kad ih ima).', verbose_name='Prikaži sekciju „Akcijska ponuda”'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='prikazi_newsletter',
            field=models.BooleanField(default=True, verbose_name='Prikaži newsletter box na početnoj'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tekst_pogledaj_sve',
            field=models.CharField(blank=True, default='Pogledaj sve', help_text='Link desno od naslova sekcija proizvoda na početnoj.', max_length=40, verbose_name='Tekst linka „Pogledaj sve”'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='boja_dugme_banner',
            field=models.CharField(blank=True, default='#5BB805', help_text='CTA na hero/grid/featured bannerima. Hex npr. #5BB805 (zelena kao na mockupu).', max_length=7, verbose_name='Boja dugmadi na bannerima'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='boja_dugme_banner_hover',
            field=models.CharField(blank=True, default='#4fa104', help_text='Hex npr. #4fa104', max_length=7, verbose_name='Boja banner dugmadi hover'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='naslov_blog',
            field=models.CharField(default='Vlog / Blog', max_length=200, verbose_name='Blog — naslov'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='naslov_izdvojeno',
            field=models.CharField(blank=True, default='Izdvojeni', help_text='Sekcija „Izdvojeni” na početnoj. Ostavite prazno da se naslov ne prikazuje.', max_length=120, verbose_name='Izdvojeni — naslov'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='naslov_novo',
            field=models.CharField(blank=True, default='Noviteti', help_text='Ostavite prazno da se naslov ne prikazuje.', max_length=120, verbose_name='Noviteti — naslov'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='podnaslov_izdvojeno',
            field=models.CharField(blank=True, default='', help_text='Ostavite prazno da se podnaslov ne prikazuje.', max_length=200, verbose_name='Izdvojeni — podnaslov'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='podnaslov_novo',
            field=models.CharField(blank=True, default='', help_text='Ostavite prazno da se podnaslov ne prikazuje.', max_length=200, verbose_name='Noviteti — podnaslov'),
        ),
        migrations.CreateModel(
            name='HomePromoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=80, verbose_name='Naslov')),
                ('podnaslov', models.CharField(blank=True, max_length=160, verbose_name='Podnaslov')),
                ('badge', models.CharField(blank=True, help_text='Npr. „DO 10%”, „50 KM”, „POPUSTI”. Prazno = bez badgea.', max_length=40, verbose_name='Badge / isticanje')),
                ('ikona', models.CharField(choices=[('truck', 'Dostava / kamion'), ('percent', 'Popust %'), ('gift', 'Poklon / kartice'), ('tag', 'Akcije / tag'), ('star', 'Zvijezda / vjernost'), ('shield', 'Štit'), ('support', 'Podrška')], default='star', max_length=20, verbose_name='Ikona')),
                ('link', models.CharField(blank=True, help_text='Npr. /?akcija=1 ili https://… Prazno = bez linka.', max_length=300, verbose_name='Link (URL ili putanja)')),
                ('redoslijed', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('aktivan', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('postavke', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='promo_kartice', to='EcommerceApp.sitesettings')),
            ],
            options={
                'verbose_name': 'Promo kartica (početna)',
                'verbose_name_plural': 'Promo kartice (početna)',
                'ordering': ['redoslijed', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeTrustItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=80, verbose_name='Naslov')),
                ('podnaslov', models.CharField(blank=True, max_length=120, verbose_name='Podnaslov')),
                ('ikona', models.CharField(choices=[('truck', 'Dostava / kamion'), ('shield', 'Štit / sigurnost'), ('badge', 'Značka / original'), ('support', 'Podrška / slušalice'), ('gift', 'Poklon'), ('star', 'Zvijezda'), ('check', 'Kvačica'), ('tag', 'Cjenovni tag')], default='check', max_length=20, verbose_name='Ikona')),
                ('redoslijed', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('aktivan', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('postavke', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='trust_stavke', to='EcommerceApp.sitesettings')),
            ],
            options={
                'verbose_name': 'Trust stavka (početna)',
                'verbose_name_plural': 'Trust traka (početna)',
                'ordering': ['redoslijed', 'id'],
            },
        ),
        migrations.RunPython(seed_home_mockup, unseed_home_mockup),
    ]
