# Generated by Django 6.0.6 on 2026-08-01 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0173_search_synonym_group_unique_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_type', models.CharField(choices=[('length', 'Dužina'), ('weight', 'Težina'), ('diameter', 'Promjer'), ('reel_size', 'Veličina mašinice'), ('casting_weight', 'Gramaža bacanja'), ('test_curve', 'Test curve'), ('bait_size', 'Veličina mamca'), ('capacity', 'Nosivost'), ('pieces', 'Broj komada'), ('diving_depth', 'Dubina ronjenja')], db_index=True, max_length=32, verbose_name='Tip karakteristike')),
                ('text_value', models.CharField(blank=True, help_text='Originalni izraz npr. „3,60m” ili „150g”.', max_length=80, verbose_name='Tekstualna vrijednost')),
                ('numeric_value', models.DecimalField(blank=True, db_index=True, decimal_places=4, help_text='Vrijednost u jedinici iz polja unit.', max_digits=12, null=True, verbose_name='Numerička vrijednost')),
                ('unit', models.CharField(blank=True, db_index=True, help_text='npr. m, cm, mm, g, lb, ft', max_length=16, verbose_name='Jedinica')),
                ('normalized_numeric_value', models.DecimalField(blank=True, db_index=True, decimal_places=6, help_text='Kanon: dužina m, težina/gramaža g, promjer/mamac mm, test curve lb.', max_digits=14, null=True, verbose_name='Normalizovana vrijednost')),
                ('aktivno', models.BooleanField(db_index=True, default=True, verbose_name='Aktivno')),
                ('izvor', models.CharField(blank=True, default='manual', help_text='manual | extract | import', max_length=20, verbose_name='Izvor')),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('azurirano', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributi', to='EcommerceApp.product', verbose_name='Artikal')),
            ],
            options={
                'verbose_name': 'Karakteristika artikla',
                'verbose_name_plural': 'Karakteristike artikala',
                'ordering': ['product_id', 'attribute_type', 'id'],
                'indexes': [models.Index(fields=['attribute_type', 'normalized_numeric_value'], name='prodattr_type_norm_idx'), models.Index(fields=['attribute_type', 'unit'], name='prodattr_type_unit_idx'), models.Index(fields=['numeric_value'], name='prodattr_numeric_idx'), models.Index(fields=['product', 'attribute_type', 'aktivno'], name='prodattr_prod_type_act_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'attribute_type', 'normalized_numeric_value', 'unit'), name='uniq_prodattr_prod_type_norm_unit')],
            },
        ),
    ]
