# Generated by Django 6.0.6 on 2026-08-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0174_home_mockup_trust_promo_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepromocard',
            name='slika',
            field=models.ImageField(blank=True, help_text='Tvoja slika umjesto ugrađene ikone. Preporučeno: 200×200 px (ili 240×160), PNG s transparentnom pozadinom, zelena grafika. Ako je prazno — koristi se SVG ikona (polje „Ikona”).', null=True, upload_to='promo/', verbose_name='Slika (desno na kartici)'),
        ),
        migrations.AlterField(
            model_name='homepromocard',
            name='badge',
            field=models.CharField(blank=True, help_text='Npr. „DO 10%”, „50 KM”, „150 KM”. Za dostavu (truck) prikazuje se kao veliki broj ispod teksta; za pečat/poklon ide u ikonu ako nema uploadane slike.', max_length=40, verbose_name='Badge / isticanje'),
        ),
        migrations.AlterField(
            model_name='homepromocard',
            name='ikona',
            field=models.CharField(choices=[('truck', 'Dostava / kamion'), ('percent', 'Popust %'), ('gift', 'Poklon / kartice'), ('tag', 'Akcije / tag'), ('star', 'Zvijezda / vjernost'), ('shield', 'Štit'), ('support', 'Podrška')], default='star', help_text='Koristi se samo ako nema uploadane slike.', max_length=20, verbose_name='Ikona (fallback)'),
        ),
        migrations.AlterField(
            model_name='homepromocard',
            name='naslov',
            field=models.CharField(help_text='Zeleni naslov. Za 2 reda stavi Enter (npr. BESPLATNA ↵ DOSTAVA).', max_length=80, verbose_name='Naslov'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Prikazuje se u headeru (crna pozadina). Originalna slika se ne ofarbava — samo max ~640×128. Preporuka: PNG, transparentna pozadina, bijela/zelena grafika.', null=True, upload_to='site/', verbose_name='Logo sajta'),
        ),
    ]
