# Generated by Django 6.0.6 on 2026-08-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0175_home_promo_card_slika'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepromocard',
            name='boja_isticanja',
            field=models.CharField(blank=True, default='#FFFFFF', help_text='Boja velikog broja ispod teksta (dostava). Hex npr. #FFFFFF.', max_length=7, verbose_name='Boja isticanja (npr. 150 KM)'),
        ),
        migrations.AddField(
            model_name='homepromocard',
            name='boja_naslova',
            field=models.CharField(blank=True, default='#5BB805', help_text='Hex npr. #5BB805 (zelena) ili #ffffff (bijela).', max_length=7, verbose_name='Boja naslova'),
        ),
        migrations.AddField(
            model_name='homepromocard',
            name='boja_podnaslova',
            field=models.CharField(blank=True, default='#FFFFFF', help_text='Hex npr. #FFFFFF ili #CCCCCC.', max_length=7, verbose_name='Boja podnaslova'),
        ),
    ]
