# Generated by Django 6.0.6 on 2026-08-01 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0175_pg_trgm_fuzzy_search'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_query', models.CharField(max_length=150, verbose_name='Originalni upit')),
                ('normalized_query', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Normalizovani upit')),
                ('result_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Broj rezultata')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Sesija')),
                ('source', models.CharField(blank=True, choices=[('full_page', 'Stranica rezultata'), ('form', 'Search forma'), ('autocomplete', 'Autocomplete klik')], default='full_page', max_length=20, verbose_name='Izvor')),
                ('selected_suggestion', models.CharField(blank=True, max_length=150, verbose_name='Odabrani prijedlog (Da li ste mislili / autocomplete)')),
                ('converted_to_cart', models.BooleanField(db_index=True, default=False, verbose_name='Konverzija u korpu')),
                ('converted_to_order', models.BooleanField(db_index=True, default=False, verbose_name='Konverzija u narudžbu')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vrijeme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_query_logs', to=settings.AUTH_USER_MODEL, verbose_name='Korisnik')),
            ],
            options={
                'verbose_name': 'Search — upit (log)',
                'verbose_name_plural': 'Search — upiti (log)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_position', models.PositiveSmallIntegerField(default=0, verbose_name='Pozicija u rezultatima (1-based)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vrijeme')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_clicks', to='EcommerceApp.product', verbose_name='Artikal')),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='EcommerceApp.searchquerylog', verbose_name='Search upit')),
            ],
            options={
                'verbose_name': 'Search — klik',
                'verbose_name_plural': 'Search — klikovi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['normalized_query', '-created_at'], name='sqlog_norm_created_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['result_count', '-created_at'], name='sqlog_count_created_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['session_key', '-created_at'], name='sqlog_session_created_idx'),
        ),
        migrations.AddIndex(
            model_name='searchclicklog',
            index=models.Index(fields=['product', '-created_at'], name='sclick_product_created_idx'),
        ),
        migrations.AddIndex(
            model_name='searchclicklog',
            index=models.Index(fields=['search_query', 'result_position'], name='sclick_query_pos_idx'),
        ),
    ]
