# Generated by Django 6.0.6 on 2026-08-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0176_home_promo_card_text_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='slika_mobilna',
            field=models.ImageField(blank=True, help_text='Opcionalno — prikazuje se SAMO na telefonu (≤768px). Preporučeno 1080×1350 px (4:5) ili 800×1000. Ako je prazno, na mobitelu se koristi desktop slika.', null=True, upload_to='banners/mobile/', verbose_name='Slika (mobilni)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='slika',
            field=models.ImageField(blank=True, help_text='Hero: 1920×640 px (3:1). Ostali tipovi po potrebi.', null=True, upload_to='banners/', verbose_name='Slika (desktop)'),
        ),
    ]
