# Generated by Django 6.0.6 on 2026-08-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0176_search_analytics_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIntentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=120, verbose_name='Naziv pravila')),
                ('trigger_phrases', models.TextField(help_text='Jedna fraza po redu (ili zarezom). Primjeri: som, početnički feeder set, štap za Savu. Match je case/diakritic-insensitive (normalizacija).', verbose_name='Okidač fraze')),
                ('prioritet', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Veći broj = prvo se prikazuje ako se više pravila poklopi.', verbose_name='Prioritet')),
                ('aktivno', models.BooleanField(db_index=True, default=True, verbose_name='Aktivno')),
                ('naslov_preporuke', models.CharField(blank=True, help_text='npr. „Za lov na soma preporučujemo”', max_length=160, verbose_name='Naslov preporuke')),
                ('objasnjenje', models.TextField(blank=True, help_text='Kratko objašnjenje za kupca (zašto ove preporuke).', verbose_name='Objašnjenje')),
                ('azurirano', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('povezane_kategorije', models.ManyToManyField(blank=True, related_name='search_intent_rules', to='EcommerceApp.category', verbose_name='Povezane kategorije')),
                ('povezani_brendovi', models.ManyToManyField(blank=True, related_name='search_intent_rules', to='EcommerceApp.brand', verbose_name='Povezani brendovi')),
                ('povezani_proizvodi', models.ManyToManyField(blank=True, help_text='Prikazuju se u sekciji „Možda će vam trebati i”, ne u glavnom rankingu.', related_name='search_intent_rules', to='EcommerceApp.product', verbose_name='Povezani proizvodi')),
                ('povezani_tagovi', models.ManyToManyField(blank=True, related_name='search_intent_rules', to='EcommerceApp.tag', verbose_name='Povezani tagovi')),
            ],
            options={
                'verbose_name': 'Search — intent pravilo',
                'verbose_name_plural': 'Search — intent pravila',
                'ordering': ['-prioritet', 'naziv'],
            },
        ),
    ]
