# Generated by Django 6.0.6 on 2026-08-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0177_banner_slika_mobilna'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='chat_avatar_slika',
            field=models.ImageField(blank=True, help_text='Slika koja se prikazuje na chat balonu i u headeru chata kad iskoči kupcu. Preporučeno: 256×256 px, PNG/JPG (kvadrat). Ako je prazno — default ikona.', null=True, upload_to='site/chat/', verbose_name='Chat — slika (avatar / balon)'),
        ),
    ]
