# Generated by Django 6.0.6 on 2026-08-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0181_sitesettings_politika_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='slika_mobilna',
            field=models.ImageField(blank=True, help_text='Opcionalno — SAMO na telefonu (≤768px). Preporuka: JPG 720×900 (4:5), max ~2 MB. Server automatski smanjuje; prevelike slike mogu srušiti free hosting. Ako je prazno — koristi se desktop slika.', null=True, upload_to='banners/mobile/', verbose_name='Slika (mobilni)'),
        ),
    ]
