# Generated by Django 6.0.6 on 2026-08-13 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0182_alter_banner_slika_mobilna'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra', models.CharField(max_length=20, unique=True, verbose_name='Šifra')),
                ('naziv', models.CharField(max_length=120, verbose_name='Naziv')),
                ('opis', models.CharField(blank=True, max_length=300, verbose_name='Opis')),
                ('aktivan', models.BooleanField(db_index=True, default=True)),
                ('redoslijed', models.PositiveIntegerField(default=0)),
                ('odoo_location_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Odoo location ID')),
                ('odoo_location_path', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Magacin lokacija',
                'verbose_name_plural': 'Magacin lokacije',
                'ordering': ['redoslijed', 'sifra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=160, unique=True)),
                ('aktivan', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dobavljač',
                'verbose_name_plural': 'Dobavljači',
                'ordering': ['naziv'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('prijem', 'Prijem'), ('prodaja', 'Prodaja'), ('transfer', 'Transfer'), ('korekcija', 'Korekcija'), ('rezervacija', 'Rezervacija'), ('sync', 'Sinhronizacija')], db_index=True, max_length=20)),
                ('kolicina', models.IntegerField(verbose_name='Količina')),
                ('napomena', models.CharField(blank=True, max_length=300)),
                ('kreiran', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('korisnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magacin_kretanja', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kretanja', to='EcommerceApp.warehouselocation', verbose_name='Lokacija')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magacin_kretanja', to='EcommerceApp.product')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kretanja_ulaz', to='EcommerceApp.warehouselocation', verbose_name='Odredište')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magacin_kretanja', to='EcommerceApp.productvariation')),
            ],
            options={
                'verbose_name': 'Kretanje zalihe',
                'verbose_name_plural': 'Kretanja zalihe',
                'ordering': ['-kreiran', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductWarehouseMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tezina', models.CharField(blank=True, max_length=40, verbose_name='Težina')),
                ('jedinica_mjere', models.CharField(default='kom', max_length=20, verbose_name='Jedinica mjere')),
                ('min_zaliha', models.PositiveIntegerField(default=0, verbose_name='Min. zaliha')),
                ('veleprodajna_cijena', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Veleprodajna cijena')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='magacin_meta', to='EcommerceApp.product')),
                ('dobavljac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikli', to='EcommerceApp.warehousesupplier', verbose_name='Dobavljač')),
            ],
            options={
                'verbose_name': 'Magacin meta artikla',
                'verbose_name_plural': 'Magacin meta artikala',
            },
        ),
        migrations.CreateModel(
            name='WarehouseSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('uspjeh', 'Uspješna'), ('greska', 'Neuspješna'), ('u_toku', 'U toku')], default='u_toku', max_length=20)),
                ('izvor', models.CharField(default='Lokalna baza (SQLite)', max_length=80)),
                ('poruka', models.CharField(blank=True, max_length=400)),
                ('artikala', models.PositiveIntegerField(default=0)),
                ('lokacija', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('trajanje_sekundi', models.PositiveIntegerField(default=0)),
                ('korisnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magacin_syncovi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Magacin sync',
                'verbose_name_plural': 'Magacin syncovi',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField(default=0, verbose_name='Na stanju')),
                ('rezervisano', models.IntegerField(default=0, verbose_name='Rezervisano')),
                ('azurirano', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zalihe', to='EcommerceApp.warehouselocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magacin_zalihe', to='EcommerceApp.product')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magacin_zalihe', to='EcommerceApp.productvariation')),
            ],
            options={
                'verbose_name': 'Zaliha po lokaciji',
                'verbose_name_plural': 'Zalihe po lokacijama',
                'indexes': [models.Index(fields=['product', 'location'], name='EcommerceAp_product_749ded_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'variation', 'location'), name='uniq_wh_stock_product_var_loc', nulls_distinct=False)],
            },
        ),
    ]
