# Generated by Django 6.0.6 on 2026-08-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0183_magacin'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='warehousestock',
            name='uniq_wh_stock_product_var_loc',
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='variation_key',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddConstraint(
            model_name='warehousestock',
            constraint=models.UniqueConstraint(fields=('product', 'variation_key', 'location'), name='uniq_wh_stock_product_varkey_loc'),
        ),
    ]
