# Generated by Django 6.0.6 on 2026-08-13 08:26

from django.db import migrations, models
from django.utils import timezone


def mark_existing_odoo_products(apps, schema_editor):
    Product = apps.get_model('EcommerceApp', 'Product')
    Product.objects.filter(
        odoo_template_id__isnull=False,
        magacin_sync_at__isnull=True,
    ).update(magacin_sync_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0184_magacin_variation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='magacin_sync_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Kad je artikal zadnji put povučen iz Odoa u Magacin.', null=True, verbose_name='Magacin sync'),
        ),
        migrations.RunPython(mark_existing_odoo_products, migrations.RunPython.noop),
    ]
