# Generated by Django 6.0.6 on 2026-08-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0189_order_zapakovana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousesynclog',
            name='status',
            field=models.CharField(choices=[('uspjeh', 'Uspješna'), ('greska', 'Neuspješna'), ('u_toku', 'U toku'), ('prekinut', 'Prekinuta')], default='u_toku', max_length=20),
        ),
    ]
