# Generated by Django 6.0.6 on 2026-08-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0190_alter_warehousesynclog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('nova', 'Nova'), ('potvrdjena', 'Potvrđena'), ('poslana', 'Poslana'), ('zavrsena', 'Validirana'), ('otkazana', 'Otkazana')], default='nova', max_length=20),
        ),
    ]
