# Generated by Django 6.0.6 on 2026-08-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0193_uvoz_izvor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='warehousecustomer',
            new_name='EcommerceAp_ime_pre_9a564e_idx',
            old_name='mg_customer_ime_idx',
        ),
        migrations.RenameIndex(
            model_name='warehousecustomer',
            new_name='EcommerceAp_telefon_73858b_idx',
            old_name='mg_customer_tel_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='lager_status',
            field=models.CharField(choices=[('nije', '—'), ('rezervisano', 'Rezervisano'), ('validirano', 'Validatovano'), ('otkazano', 'Otkazano')], db_index=True, default='nije', max_length=20, verbose_name='Magacin lager'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('nova', 'Nova'), ('potvrdjena', 'Potvrđena'), ('poslana', 'Poslana'), ('zavrsena', 'Validatovana'), ('otkazana', 'Otkazana')], default='nova', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstockhold',
            name='status',
            field=models.CharField(choices=[('rezervisano', 'Rezervisano'), ('validirano', 'Validatovano'), ('otkazano', 'Otkazano')], db_index=True, default='rezervisano', max_length=20),
        ),
    ]
