# Generated by Django 6.0.6 on 2026-08-26 12:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0212_warehousestock_variation_set_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagacinPonuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj', models.CharField(editable=False, max_length=20, unique=True)),
                ('token', models.CharField(db_index=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('nacrt', 'Nacrt'), ('objavljena', 'Objavljena')], db_index=True, default='nacrt', max_length=20)),
                ('ime_prezime', models.CharField(blank=True, max_length=200, verbose_name='Kupac')),
                ('telefon', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresa', models.CharField(blank=True, max_length=300)),
                ('grad', models.CharField(blank=True, max_length=100)),
                ('napomena', models.TextField(blank=True)),
                ('popust_postotak', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Popust (%)')),
                ('popust_iznos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Popust (KM)')),
                ('kreiran', models.DateTimeField(auto_now_add=True)),
                ('azuriran', models.DateTimeField(auto_now=True)),
                ('objavljena_at', models.DateTimeField(blank=True, null=True)),
                ('kreirao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magacin_ponude', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Magacin ponuda',
                'verbose_name_plural': 'Magacin ponude',
                'ordering': ['-kreiran'],
            },
        ),
        migrations.CreateModel(
            name='MagacinPonudaStavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('sifra', models.CharField(blank=True, max_length=200)),
                ('kolicina', models.PositiveIntegerField(default=1)),
                ('cijena', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cijena bez PDV')),
                ('manuelno', models.BooleanField(default=False)),
                ('redoslijed', models.PositiveIntegerField(default=0)),
                ('kreiran', models.DateTimeField(auto_now_add=True)),
                ('ponuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='EcommerceApp.magacinponuda')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ponuda_stavke', to='EcommerceApp.product')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ponuda_stavke', to='EcommerceApp.productvariation')),
            ],
            options={
                'verbose_name': 'Stavka ponude',
                'verbose_name_plural': 'Stavke ponude',
                'ordering': ['redoslijed', 'id'],
            },
        ),
    ]
