# Generated by Django 6.0.6 on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0213_magacin_ponuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='magacinponuda',
            name='prihvacena_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magacinponuda',
            name='order',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='magacin_ponuda',
                to='EcommerceApp.order',
            ),
        ),
        migrations.AlterField(
            model_name='magacinponuda',
            name='status',
            field=models.CharField(
                choices=[
                    ('nacrt', 'Nacrt'),
                    ('objavljena', 'Objavljena'),
                    ('prihvacena', 'Prihvaćena'),
                ],
                db_index=True,
                default='nacrt',
                max_length=20,
            ),
        ),
    ]
