# Generated by Django 6.0.6 on 2026-08-26 12:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0214_ponuda_prihvacena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magacinponudastavka',
            name='cijena',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cijena sa PDV'),
        ),
    ]
