# Generated by Django 6.0.6 on 2026-08-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0215_alter_magacinponudastavka_cijena'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagacinMpDnevnoSkidanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kreiran', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fajl', models.FileField(blank=True, upload_to='magacin/mp_dnevno/')),
                ('fajl_naziv', models.CharField(blank=True, max_length=200)),
                ('raw_text', models.TextField(blank=True)),
                ('skinuto_stavki', models.PositiveIntegerField(default=0)),
                ('skinuto_komada', models.PositiveIntegerField(default=0)),
                ('kreirao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_dnevna_skidanja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dnevno skidanje MP lagera',
                'verbose_name_plural': 'Dnevna skidanja MP lagera',
                'ordering': ['-kreiran', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MagacinMpDnevnoStavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra', models.CharField(max_length=200)),
                ('naziv', models.CharField(blank=True, max_length=200)),
                ('trazeno', models.PositiveIntegerField(default=0)),
                ('kolicina', models.PositiveIntegerField(default=0)),
                ('lokacija', models.CharField(blank=True, max_length=300)),
                ('kreiran', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_dnevno_stavke', to='EcommerceApp.product')),
                ('skidanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='EcommerceApp.magacinmpdnevnoskidanje')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_dnevno_stavke', to='EcommerceApp.productvariation')),
            ],
            options={
                'verbose_name': 'Stavka dnevnog MP skidanja',
                'verbose_name_plural': 'Stavke dnevnog MP skidanja',
                'ordering': ['id'],
            },
        ),
    ]
