# Generated by Django 6.0.6 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0216_mp_dnevno_skidanje'),
    ]

    operations = [
        migrations.AddField(
            model_name='magacinmpdnevnoskidanje',
            name='datum',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterModelOptions(
            name='magacinmpdnevnoskidanje',
            options={
                'ordering': ['-datum', '-kreiran', '-id'],
                'verbose_name': 'Dnevno skidanje MP lagera',
                'verbose_name_plural': 'Dnevna skidanja MP lagera',
            },
        ),
    ]
