# Generated by Django 6.0.6 on 2026-08-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0217_mp_dnevno_datum'),
    ]

    operations = [
        migrations.AddField(
            model_name='magacinpopis',
            name='location',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='popisi',
                to='EcommerceApp.warehouselocation',
            ),
        ),
        migrations.AddField(
            model_name='magacinpopisstavka',
            name='ocekivano',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
