# Generated by Django 6.0.6 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0218_popis_lokacija'),
    ]

    operations = [
        migrations.AddField(
            model_name='magacinpopisstavka',
            name='cekirano',
            field=models.BooleanField(default=False),
        ),
    ]
