# Generated by Django 6.0.6 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0219_popis_cekirano'),
    ]

    operations = [
        migrations.AddField(
            model_name='magacinpopis',
            name='odstampan',
            field=models.BooleanField(default=False),
        ),
    ]
