# Generated by Django 6.0.6 on 2026-08-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0225_akcija_akcijska_ponuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homevlog',
            name='slika',
            field=models.ImageField(help_text='Upload 800×500 px (omjer 8:5). Za oštrinu: 1600×1000. Prikaz na početnoj — 3 u nizu.', upload_to='vlogs/', verbose_name='Slika'),
        ),
    ]
