# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0226_vlog_image_800x500'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sakriven_do_stanja',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text=(
                    'Sakriven od kupaca. Kad artikal opet dođe na stanje '
                    '(ili se količina poveća), automatski se prikaže.'
                ),
                verbose_name='Sakriven sa sajta',
            ),
        ),
    ]
