# Generated by Django 6.0.6 on 2026-09-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0228_magacinvpnarudzba_placanje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='slika_mobilna',
            field=models.ImageField(blank=True, help_text='Opcionalno — SAMO na telefonu (≤768px). Preporuka: JPG 1080×1350 (4:5), max ~2 MB. Ako je prazno — koristi se desktop slika.', null=True, upload_to='banners/mobile/', verbose_name='Slika (mobilni)'),
        ),
    ]
