# Generated by Django 6.0.6 on 2026-09-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0232_uvoz_popis'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pick_short_events',
            field=models.JSONField(blank=True, default=list, verbose_name='Picking — manjak na lokacijama'),
        ),
    ]
