# Generated by Django 6.0.6 on 2026-09-06 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0236_superusers_default_basic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehousePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(db_index=True, max_length=200)),
                ('grad', models.CharField(blank=True, max_length=100)),
                ('adresa', models.CharField(blank=True, max_length=300)),
                ('telefon', models.CharField(blank=True, max_length=30)),
                ('pdv_broj', models.CharField(blank=True, max_length=30)),
                ('kontakt', models.CharField(blank=True, max_length=200)),
                ('napomena', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['naziv', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('debit', 'Duguje — partner nama'), ('credit', 'Potražuje — mi partneru'), ('receipt', 'Primljena uplata'), ('payment', 'Naša uplata partneru'), ('order', 'Narudžba'), ('return', 'Povrat robe')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('returned_qty', models.PositiveIntegerField(default=0)),
                ('token', models.UUIDField(unique=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entry', to='EcommerceApp.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLedgerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='EcommerceApp.warehouseledgerentry')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EcommerceApp.warehouselocation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EcommerceApp.product')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EcommerceApp.productvariation')),
            ],
        ),
        migrations.AddField(
            model_name='warehouseledgerentry',
            name='source_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='EcommerceApp.warehouseledgerline'),
        ),
        migrations.AddField(
            model_name='warehouseledgerentry',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='EcommerceApp.warehousepartner'),
        ),
        migrations.AddIndex(
            model_name='warehouseledgerentry',
            index=models.Index(fields=['partner', '-created_at'], name='EcommerceAp_partner_35ba17_idx'),
        ),
    ]
