# Generated by Django 6.0.6 on 2026-09-07 06:20

import django.db.models.deletion
from django.db import migrations, models


def link_customers(apps, schema_editor):
    Customer = apps.get_model('EcommerceApp', 'WarehouseCustomer')
    Partner = apps.get_model('EcommerceApp', 'WarehousePartner')
    db = schema_editor.connection.alias
    for partner in Partner.objects.using(db).filter(customer__isnull=True).iterator():
        # Never attach balances using a name alone or an ambiguous contact.
        matches = Customer.objects.using(db).filter(
            ime_prezime=partner.naziv, telefon=partner.telefon,
        ) if partner.telefon.strip() else Customer.objects.using(db).none()
        customer = matches.first() if matches.count() == 1 else None
        if customer and Partner.objects.using(db).filter(customer_id=customer.pk).exists():
            customer = None
        if customer is None:
            customer = Customer.objects.using(db).create(
                ime_prezime=partner.naziv, telefon=partner.telefon,
                adresa=partner.adresa, grad=partner.grad,
            )
        Partner.objects.using(db).filter(pk=partner.pk).update(
            customer_id=customer.pk, naziv=customer.ime_prezime,
            telefon=customer.telefon, adresa=customer.adresa, grad=customer.grad,
        )
    linked = Partner.objects.using(db).values_list('customer_id', flat=True)
    missing = Customer.objects.using(db).exclude(pk__in=linked)
    batch = []
    for customer in missing.iterator():
        batch.append(Partner(customer_id=customer.pk, naziv=customer.ime_prezime,
                             telefon=customer.telefon, adresa=customer.adresa, grad=customer.grad))
        if len(batch) == 500:
            Partner.objects.using(db).bulk_create(batch)
            batch = []
    if batch:
        Partner.objects.using(db).bulk_create(batch)


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0237_warehouse_partner_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousepartner',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_partner', to='EcommerceApp.warehousecustomer'),
        ),
        migrations.RunPython(link_customers, migrations.RunPython.noop),
    ]
