# Generated by Django 6.0.6 on 2026-09-07 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0238_ledger_customer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseledgerentry',
            name='source_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missing_ledger_entries', to='EcommerceApp.order'),
        ),
        migrations.AddField(
            model_name='warehouseledgerline',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missing_ledger_lines', to='EcommerceApp.orderitem'),
        ),
        migrations.AlterField(
            model_name='warehouseledgerentry',
            name='kind',
            field=models.CharField(choices=[('debit', 'Duguje — partner nama'), ('credit', 'Potražuje — mi partneru'), ('receipt', 'Primljena uplata'), ('payment', 'Naša uplata partneru'), ('order', 'Narudžba'), ('return', 'Povrat robe'), ('missing', 'Mi dugujemo — artikli koji fale')], max_length=12),
        ),
    ]
