# Generated by Django 6.0.6 on 2026-09-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0240_ledger_excess_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseledgerentry',
            name='kind',
            field=models.CharField(choices=[('debit', 'Duguje — partner nama'), ('credit', 'Potražuje — mi partneru'), ('receipt', 'Primljena uplata'), ('payment', 'Naša uplata partneru'), ('order', 'Narudžba'), ('return', 'Povrat robe'), ('missing', 'Mi dugujemo — artikli koji fale'), ('excess', 'Kupac duguje — više poslato'), ('damaged', 'Oštećen artikal — mi dugujemo kupcu')], max_length=12),
        ),
    ]
