# Generated by Django 6.0.6 on 2026-09-07 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0241_ledger_damaged_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseledgerline',
            name='replacement_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_replacement_line', to='EcommerceApp.order'),
        ),
    ]
