# Generated by Django 6.0.6 on 2026-09-07 08:38

from django.db import migrations, models
from uuid import uuid5, NAMESPACE_URL


def settle_existing(apps, schema_editor):
    Line = apps.get_model('EcommerceApp', 'WarehouseLedgerLine')
    Entry = apps.get_model('EcommerceApp', 'WarehouseLedgerEntry')
    db = schema_editor.connection.alias
    lines = Line.objects.using(db).filter(entry__kind='damaged', replacement_order__lager_status='validirano').exclude(replacement_order__status='otkazana').select_related('entry', 'replacement_order')
    for line in lines.iterator():
        order = line.replacement_order
        Entry.objects.using(db).get_or_create(
            token=uuid5(NAMESPACE_URL, f'warehouse-replacement-settled:{line.pk}:{order.pk}'),
            defaults={'partner_id':line.entry.partner_id, 'kind':'settled', 'amount':line.amount,
                      'source_line_id':line.pk, 'returned_qty':line.quantity, 'source_order_id':order.pk,
                      'description':f'Zamjena #{order.broj} validatovana — {line.name}'[:300]},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0242_damaged_replacement_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseledgerentry',
            name='kind',
            field=models.CharField(choices=[('debit', 'Duguje — partner nama'), ('credit', 'Potražuje — mi partneru'), ('receipt', 'Primljena uplata'), ('payment', 'Naša uplata partneru'), ('order', 'Narudžba'), ('return', 'Povrat robe'), ('missing', 'Mi dugujemo — artikli koji fale'), ('excess', 'Kupac duguje — više poslato'), ('damaged', 'Oštećen artikal — mi dugujemo kupcu'), ('settled', 'Izmireno — zamjena validatovana')], max_length=12),
        ),
        migrations.RunPython(settle_existing, migrations.RunPython.noop),
    ]
