# Generated by Django 6.0.6 on 2026-09-07 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0243_settle_validated_replacements'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseledgerline',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settled_lines', to='EcommerceApp.warehouseledgerentry'),
        ),
    ]
