# Generated by Django 6.0.6 on 2026-09-07 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0244_ledger_paid_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseledgerline',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_lines', to='EcommerceApp.warehouseledgerentry'),
        ),
        migrations.AlterField(
            model_name='warehouseledgerentry',
            name='kind',
            field=models.CharField(choices=[('debit', 'Duguje — partner nama'), ('credit', 'Potražuje — mi partneru'), ('receipt', 'Primljena uplata'), ('payment', 'Naša uplata partneru'), ('order', 'Narudžba'), ('return', 'Povrat robe'), ('missing', 'Mi dugujemo — artikli koji fale'), ('excess', 'Kupac duguje — više poslato'), ('damaged', 'Oštećen artikal — mi dugujemo kupcu'), ('settled', 'Izmireno — zamjena validatovana'), ('void', 'Poništen pogrešan unos')], max_length=12),
        ),
    ]
