# Generated by Django 6.0.6 on 2026-09-07 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0245_void_ledger_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ledger_excess_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_item', to='EcommerceApp.warehouseledgerline'),
        ),
    ]
