# Generated by Django 6.0.6 on 2026-09-07 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0246_invoice_only_excess'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ledger_missing_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_items', to='EcommerceApp.warehouseledgerline'),
        ),
    ]
