# Generated by Django 6.0.6 on 2026-09-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0247_picking_only_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousecustomer',
            name='odbio_posiljku',
            field=models.BooleanField(default=False, verbose_name='Odbio pošiljku'),
        ),
    ]
