# Generated by Django 6.0.6 on 2026-09-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0248_customer_refused_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='browse_interest_duration_seconds',
            field=models.PositiveIntegerField(default=180, verbose_name='Trajanje AI ponude (sekundi)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='browse_interest_gap_seconds',
            field=models.PositiveIntegerField(default=180, verbose_name='Razmak između ponuda (sekundi)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='browse_interest_max_offers',
            field=models.PositiveIntegerField(default=2, verbose_name='Najviše ponuda po posjeti'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='browse_interest_min_seconds',
            field=models.PositiveIntegerField(default=35, verbose_name='Najranije prikaži ponudu (sekundi)'),
        ),
    ]
