# Generated by Django 6.0.6 on 2026-09-08 07:55

from django.db import migrations, models


def retire_inline_flash(apps, schema_editor):
    Settings = apps.get_model('EcommerceApp', 'SiteSettings')
    for site in Settings.objects.using(schema_editor.connection.alias).all():
        if site.product_dwell_popup_aktivan:
            site.browse_interest_popup_aktivan = True
        site.product_dwell_popup_aktivan = False
        if site.browse_interest_popust == 0:
            site.browse_interest_mode = 'no_discount'
        site.save(update_fields=['browse_interest_popup_aktivan', 'product_dwell_popup_aktivan', 'browse_interest_mode'])


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0249_ai_offer_delivery_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='browse_interest_mode',
            field=models.CharField(choices=[('assertive', 'Nametljivo'), ('balanced', 'Uravnoteženo'), ('no_discount', 'Bez popusta')], default='balanced', max_length=20, verbose_name='Način prikazivanja'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='browse_interest_source',
            field=models.CharField(choices=[('category', 'Iz kategorije koju kupac gleda'), ('manual', 'Artikli koje ja odaberem')], default='category', max_length=20, verbose_name='Koje artikle prikazivati'),
        ),
        migrations.RunPython(retire_inline_flash, migrations.RunPython.noop),
    ]
