# Generated by Django 6.0.6 on 2026-09-08 08:15

import django.db.models.deletion
from django.db import migrations, models


def copy_selected_items(apps, schema_editor):
    old_items = apps.get_model('EcommerceApp', 'ProductDwellItem')
    popup_items = apps.get_model('EcommerceApp', 'AIPopupItem')
    alias = schema_editor.connection.alias
    for item in old_items.objects.using(alias).order_by('pk').iterator():
        popup_items.objects.using(alias).get_or_create(
            settings_id=item.settings_id, product_id=item.product_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0250_ai_popup_modes_and_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPopupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_popup_items', to='EcommerceApp.product', verbose_name='Artikal')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popup_items', to='EcommerceApp.sitesettings')),
            ],
            options={
                'verbose_name': 'Artikal za AI ponudu',
                'verbose_name_plural': 'Artikli za AI ponude',
                'ordering': ['pk'],
                'unique_together': {('settings', 'product')},
            },
        ),
        migrations.RunPython(copy_selected_items, migrations.RunPython.noop),
    ]
