# Generated by Django 6.0.6 on 2026-09-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0251_ai_popup_selected_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='boja_menija',
            field=models.CharField(choices=[('white', 'Bijela'), ('black', 'Crna')], default='white', help_text='Boja menija kategorija i trake pogodnosti ispod banera. Bijela zadržava sadašnji izgled; crna koristi svijetli tekst i narandžaste ikone.', max_length=5, verbose_name='Boja'),
        ),
    ]
