# Generated by Django 6.0.6 on 2026-09-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0252_menu_color_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='tip',
            field=models.CharField(choices=[('hero', 'Hero Carousel'), ('grid', 'Grid niže na početnoj (ispod akcijskih artikala)'), ('featured', 'Grid ispod banera (ispod Brza dostava / Sigurna kupovina)'), ('spotlight', 'Spotlight')], default='hero', max_length=20),
        ),
    ]
