# Generated by Django 6.0.6 on 2026-09-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0253_banner_grid_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_desno_kategorije',
            field=models.ImageField(blank=True, help_text='Upload loga na krajnjoj desnoj strani reda kategorija. Preporuka: 1000 × 200 px (5:1), JPG ili PNG. Ako je prazno, prikazuje se priloženi Carpologija BH logo.', null=True, upload_to='site/category-logos/', verbose_name='Desni logo uz Sve kategorije'),
        ),
    ]
