# Generated by Django 6.0.6 on 2026-09-09 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0254_category_row_custom_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='magacinponuda',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ponude', to='EcommerceApp.warehousecustomer'),
        ),
    ]
