# Generated by Django 6.0.6 on 2026-09-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0255_ponuda_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Korisničko ime')),
                ('company', models.CharField(max_length=200, verbose_name='Firma / kupac')),
                ('password', models.CharField(editable=False, max_length=128, verbose_name='Šifra (hash)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
            ],
            options={
                'verbose_name': 'B2B korisnik',
                'verbose_name_plural': 'B2B korisnici',
                'ordering': ['company', 'username'],
            },
        ),
    ]
