# Generated by Django 6.0.6 on 2026-09-09 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0256_b2b_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, help_text='Zamjenjuje dio „Oprema za vaš biznis“. Preporuka: 900 × 300 px, JPG, PNG ili WebP.', upload_to='b2b/banners/', verbose_name='Desni B2B banner')),
                ('banner_alt', models.CharField(blank=True, max_length=200, verbose_name='Opis bannera')),
            ],
            options={
                'verbose_name': 'B2B',
                'verbose_name_plural': 'B2B',
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='b2b_settings_singleton')],
            },
        ),
        migrations.CreateModel(
            name='B2BCategoryIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='PNG s prozirnom pozadinom, JPG ili WebP. Preporuka: 64 × 64 px.', upload_to='b2b/category-icons/', verbose_name='Ikonica')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EcommerceApp.category', verbose_name='Kategorija')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_icons', to='EcommerceApp.b2bsettings')),
            ],
            options={
                'verbose_name': 'Ikonica kategorije',
                'verbose_name_plural': 'Ikonice kategorija',
            },
        ),
    ]
