# Generated by Django 6.0.6 on 2026-09-09 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0257_b2b_banner_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(editable=False, unique=True)),
                ('payment', models.CharField(choices=[('ziralno', 'Žiralno'), ('gotovina', 'Gotovinski')], max_length=10, verbose_name='Plaćanje')),
                ('netto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ukupno netto pri slanju')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='EcommerceApp.b2baccount', verbose_name='B2B korisnik')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_submission', to='EcommerceApp.order', verbose_name='Narudžba')),
            ],
            options={
                'verbose_name': 'B2B narudžba',
                'verbose_name_plural': 'B2B narudžbe',
            },
        ),
    ]
