# Generated by Django 6.0.6 on 2026-09-09 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0258_b2b_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2bsettings',
            name='banner',
            field=models.ImageField(blank=True, help_text='Prikazuje se preko cijele širine kataloga. Preporuka: 1600 × 400 px, JPG, PNG ili WebP. Dodatne bannere dodajte ispod.', upload_to='b2b/banners/', verbose_name='Glavni banner (prvi slajd)'),
        ),
        migrations.CreateModel(
            name='B2BBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Preporuka: 1600 × 400 px. Koristite isti odnos stranica za sve bannere.', upload_to='b2b/banners/', verbose_name='Banner')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Opis slike')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='EcommerceApp.b2bsettings')),
            ],
            options={
                'verbose_name': 'B2B banner',
                'verbose_name_plural': 'Dodatni banneri za slider',
                'ordering': ['position', 'pk'],
            },
        ),
    ]
