# Generated by Django 6.0.6 on 2026-09-09 11:30

import EcommerceApp.b2b_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0259_b2b_banner_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bbanner',
            name='link',
            field=models.CharField(blank=True, help_text='Opcionalno. Lokalni link koji počinje sa / ili puna https:// adresa.', max_length=500, validators=[EcommerceApp.b2b_validators.validate_banner_link], verbose_name='Link bannera'),
        ),
        migrations.AddField(
            model_name='b2bsettings',
            name='banner_link',
            field=models.CharField(blank=True, help_text='Opcionalno. Npr. /veleprodaja?kategorija=stapovi ili https://primjer.ba/stranica.', max_length=500, validators=[EcommerceApp.b2b_validators.validate_banner_link], verbose_name='Link bannera'),
        ),
    ]
