# Generated by Django 6.0.6 on 2026-09-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0260_b2b_banner_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bsettings',
            name='akcijska_ponuda',
            field=models.ManyToManyField(blank=True, help_text='Pretražite i dodajte proizvoljan broj artikala u B2B akcijsku ponudu.', related_name='b2b_akcija_settings', to='EcommerceApp.product', verbose_name='Akcijska ponuda'),
        ),
        migrations.AddField(
            model_name='b2bsettings',
            name='noviteti',
            field=models.ManyToManyField(blank=True, help_text='Pretražite i dodajte proizvoljan broj artikala u B2B novitete.', related_name='b2b_noviteti_settings', to='EcommerceApp.product', verbose_name='Noviteti'),
        ),
    ]
