# Generated by Django 6.0.6 on 2026-09-09 13:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def copy_members(apps, schema_editor):
    Settings = apps.get_model('EcommerceApp', 'B2BSettings')
    Item = apps.get_model('EcommerceApp', 'B2BOfferItem')
    alias = schema_editor.connection.alias
    for settings in Settings.objects.using(alias).all():
        Item.objects.using(alias).bulk_create([
            Item(settings_id=settings.pk, product_id=pk, discount_percent=0)
            for pk in settings.akcijska_ponuda.using(alias).values_list('pk', flat=True)
        ])


def restore_members(apps, schema_editor):
    Settings = apps.get_model('EcommerceApp', 'B2BSettings')
    Item = apps.get_model('EcommerceApp', 'B2BOfferItem')
    alias = schema_editor.connection.alias
    for settings in Settings.objects.using(alias).all():
        settings.akcijska_ponuda.set(Item.objects.using(alias).filter(settings_id=settings.pk).values_list('product_id', flat=True))


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0261_b2b_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BOfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Popust na B2B VPC netto cijenu. 0 = bez dodatnog sniženja.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Sniženje (%)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_offer_items', to='EcommerceApp.product', verbose_name='Artikal')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_items', to='EcommerceApp.b2bsettings')),
            ],
            options={
                'verbose_name': 'Akcijski artikal',
                'verbose_name_plural': 'Akcijska ponuda — artikli i sniženje',
            },
        ),
        migrations.RunPython(copy_members, restore_members),
        migrations.RemoveField(model_name='b2bsettings', name='akcijska_ponuda'),
        migrations.AddField(
            model_name='b2bsettings',
            name='akcijska_ponuda',
            field=models.ManyToManyField(blank=True, help_text='Pretražite i dodajte proizvoljan broj artikala u B2B akcijsku ponudu.', related_name='b2b_akcija_settings', through='EcommerceApp.B2BOfferItem', to='EcommerceApp.product', verbose_name='Akcijska ponuda'),
        ),
        migrations.AddConstraint(
            model_name='b2bofferitem',
            constraint=models.UniqueConstraint(fields=('settings', 'product'), name='unique_b2b_offer_product'),
        ),
        migrations.AddConstraint(
            model_name='b2bofferitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='b2b_discount_range'),
        ),
    ]
