# Generated by Django 6.0.6 on 2026-09-09 14:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0262_b2b_offer_discounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BBrandPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisor', models.DecimalField(decimal_places=4, default=Decimal('1.38'), help_text='VPC netto = MPC sa sajta / ovaj broj / 1,17. Primjer: 1,38. PDV djelilac 1,17 je fiksan.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Djelilac MPC cijene')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcommerceApp.brand', verbose_name='Brend')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_prices', to='EcommerceApp.b2bsettings')),
            ],
            options={
                'verbose_name': 'VPC netto cijena po brendu',
                'verbose_name_plural': 'VPC netto cijene — po brendovima',
                'constraints': [models.UniqueConstraint(fields=('settings', 'brand'), name='unique_b2b_brand_pricing'), models.CheckConstraint(condition=models.Q(('divisor__gt', 0)), name='b2b_brand_divisor_positive')],
            },
        ),
    ]
