# Generated by Django 6.0.6 on 2026-09-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0263_b2b_brand_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='b2b_pricing_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
