# Generated by Django 6.0.6 on 2026-09-10 07:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def record_existing_duplicates(apps, schema_editor):
    from hashlib import sha256
    Product = apps.get_model('EcommerceApp', 'Product')
    Conflict = apps.get_model('EcommerceApp', 'BarcodeConflict')
    alias = schema_editor.connection.alias
    first = {}
    for product in Product.objects.using(alias).exclude(barkod='').order_by('pk').iterator():
        code = (product.barkod or '').strip().lower()
        if not code:
            continue
        if code not in first:
            first[code] = (product.pk, product.naziv, product.sifra or '')
            continue
        other_id, other_name, other_sku = first[code]
        key = sha256(f'{code}:{product.pk}:{other_id}'.encode()).hexdigest()
        Conflict.objects.using(alias).get_or_create(key=key, defaults={
            'barcode': product.barkod.strip(), 'product_id': product.pk,
            'other_product_id': other_id, 'product_name': product.naziv,
            'product_sku': product.sifra or '', 'other_name': other_name,
            'other_sku': other_sku, 'existing_duplicate': True,
        })


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0264_b2b_order_pricing_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeWriteLock',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BarcodeConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('barcode', models.CharField(db_index=True, max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('product_sku', models.CharField(blank=True, max_length=200)),
                ('other_name', models.CharField(max_length=200)),
                ('other_sku', models.CharField(blank=True, max_length=200)),
                ('existing_duplicate', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('other_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_matches', to='EcommerceApp.product')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_conflicts', to='EcommerceApp.product')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dupli barkod',
                'verbose_name_plural': 'Dupli barkodovi',
                'ordering': ['-last_seen', '-pk'],
            },
        ),
        migrations.RunPython(record_existing_duplicates, migrations.RunPython.noop),
    ]
