# Generated by Django 6.0.6 on 2026-09-10 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0265_duplicate_barcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousemovement',
            name='customer_name',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='warehousemovement',
            name='destination_label',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='warehousemovement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='EcommerceApp.order', verbose_name='Narudžba'),
        ),
        migrations.AddField(
            model_name='warehousemovement',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='warehousemovement',
            name='source_label',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
    ]
