# Generated by Django 6.0.6 on 2026-09-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0269_b2b_account_brand_rabat'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BLive',
            fields=[
            ],
            options={
                'verbose_name': 'B2B Live',
                'verbose_name_plural': 'B2B Live',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('EcommerceApp.b2baccount',),
        ),
    ]
