# Generated by Django 6.0.6 on 2026-09-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0272_stock_notify'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stocknotify',
            new_name='EcommerceAp_product_4e26d8_idx',
            old_name='stocknotify_prod_note_idx',
        ),
        migrations.RenameIndex(
            model_name='stocknotify',
            new_name='EcommerceAp_email_b45f46_idx',
            old_name='stocknotify_email_idx',
        ),
    ]
