# Generated by Django 6.0.6 on 2026-09-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0273_rename_stocknotify_prod_note_idx_ecommerceap_product_4e26d8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ikonica_pocetna',
            field=models.ImageField(blank=True, help_text='Preporuka: 256 × 256 px, PNG ili WebP s prozirnom pozadinom. Bez slike se koristi standardna ikonica.', upload_to='categories/icons/', verbose_name='Ikonica na početnoj'),
        ),
    ]
