# Generated by Django 6.0.6 on 2026-09-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0274_category_home_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='loyalty_banner_slika',
            field=models.ImageField(blank=True, help_text='1080 × 1080 px (1:1), JPG, PNG ili WebP. Zamjenjuje cijeli Loyalty banner na mobilnoj početnoj. Bez slike koristi se postojeći dizajn.', upload_to='site/loyalty/', verbose_name='Loyalty banner — mobilna slika'),
        ),
    ]
