# Generated by Django 6.0.6 on 2026-09-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0275_loyalty_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='akcija_banner_slika',
            field=models.ImageField(blank=True, help_text='1080 × 1080 px (1:1), JPG, PNG ili WebP. Prikazuje se ispod akcijske ponude na mobilnoj početnoj. Bez slike banner se ne prikazuje.', upload_to='site/akcija/', verbose_name='Banner ispod akcijske ponude — mobilna slika'),
        ),
    ]
