# Generated by Django 6.0.6 on 2026-09-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0276_sale_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='akcija_banner_slika_2',
            field=models.ImageField(blank=True, help_text='1080 × 1080 px (1:1), JPG, PNG ili WebP. Bez slike banner se ne prikazuje.', upload_to='site/akcija/', verbose_name='Banner 2 ispod akcijske ponude — mobilna slika'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='akcija_banner_slika_3',
            field=models.ImageField(blank=True, help_text='1080 × 1080 px (1:1), JPG, PNG ili WebP. Bez slike banner se ne prikazuje.', upload_to='site/akcija/', verbose_name='Banner 3 ispod akcijske ponude — mobilna slika'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='akcija_banner_slika_4',
            field=models.ImageField(blank=True, help_text='1080 × 1080 px (1:1), JPG, PNG ili WebP. Bez slike banner se ne prikazuje.', upload_to='site/akcija/', verbose_name='Banner 4 ispod akcijske ponude — mobilna slika'),
        ),
    ]
