# Generated by Django 6.0.6 on 2026-09-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0277_additional_sale_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='akcija_banner_desktop',
            field=models.ImageField(blank=True, help_text='1920 × 500 px, JPG, PNG ili WebP. Samo desktop (preko 1024 px). Bez slike ostaje postojeći banner.', upload_to='site/desktop/', verbose_name='Banner 1 ispod brendova — desktop slika'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='akcija_banner_desktop_2',
            field=models.ImageField(blank=True, help_text='1920 × 500 px, JPG, PNG ili WebP. Samo desktop (preko 1024 px). Bez slike ostaje postojeći banner.', upload_to='site/desktop/', verbose_name='Banner 2 ispod brendova — desktop slika'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='akcija_banner_desktop_3',
            field=models.ImageField(blank=True, help_text='1920 × 500 px, JPG, PNG ili WebP. Samo desktop (preko 1024 px). Bez slike ostaje postojeći banner.', upload_to='site/desktop/', verbose_name='Banner 3 ispod brendova — desktop slika'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='akcija_banner_desktop_4',
            field=models.ImageField(blank=True, help_text='1920 × 500 px, JPG, PNG ili WebP. Samo desktop (preko 1024 px). Bez slike ostaje postojeći banner.', upload_to='site/desktop/', verbose_name='Banner 4 ispod brendova — desktop slika'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loyalty_banner_desktop',
            field=models.ImageField(blank=True, help_text='1920 × 500 px, JPG, PNG ili WebP. Samo desktop (preko 1024 px). Bez slike ostaje postojeći banner.', upload_to='site/desktop/', verbose_name='Banner ispod Izdvojeno za vas — desktop slika'),
        ),
    ]
