# Generated by Django 6.0.6 on 2026-09-15 13:10

import EcommerceApp.b2b_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0278_sitesettings_akcija_banner_desktop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='akcija_banner_link',
            field=models.CharField(blank=True, help_text='Npr. /?akcija=1 ili https://… Prazno = bez linka.', max_length=500, validators=[EcommerceApp.b2b_validators.validate_banner_link], verbose_name='Banner 1 — link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='akcija_banner_link_2',
            field=models.CharField(blank=True, help_text='Npr. /?akcija=1 ili https://… Prazno = bez linka.', max_length=500, validators=[EcommerceApp.b2b_validators.validate_banner_link], verbose_name='Banner 2 — link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='akcija_banner_link_3',
            field=models.CharField(blank=True, help_text='Npr. /?akcija=1 ili https://… Prazno = bez linka.', max_length=500, validators=[EcommerceApp.b2b_validators.validate_banner_link], verbose_name='Banner 3 — link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='akcija_banner_link_4',
            field=models.CharField(blank=True, help_text='Npr. /?akcija=1 ili https://… Prazno = bez linka.', max_length=500, validators=[EcommerceApp.b2b_validators.validate_banner_link], verbose_name='Banner 4 — link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loyalty_banner_link',
            field=models.CharField(blank=True, help_text='Npr. /nalog/ ili https://… Prazno = registracija / nalog.', max_length=500, validators=[EcommerceApp.b2b_validators.validate_banner_link], verbose_name='Loyalty banner — link'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='slika',
            field=models.ImageField(blank=True, help_text='Hero: 2172×724 px. Ostali tipovi po potrebi.', null=True, upload_to='banners/', verbose_name='Slika (desktop)'),
        ),
    ]
