# Generated by Django 6.0.6 on 2026-09-15 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0279_sitesettings_banner_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousemovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='magacin_kretanja', to='EcommerceApp.product'),
        ),
    ]
