# Generated by Django 6.0.6 on 2026-09-16 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0280_preserve_warehouse_movement_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualOrderDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=80, unique=True)),
                ('order_number', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='active', max_length=20)),
                ('version', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ManualOrderDraftRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('event', models.CharField(default='save', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='EcommerceApp.manualorderdraft')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
