# Generated by Django 6.0.6 on 2026-09-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0283_install_permanent_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreservedMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('sha256', models.CharField(max_length=64)),
                ('content', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'sha256'), name='unique_preserved_media')],
            },
        ),
    ]
