# Generated by Django 6.0.6 on 2026-09-20 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0284_preserved_media_files'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCleaningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('item_id_snapshot', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=500)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('needed', models.PositiveIntegerField()),
                ('picked', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(blank=True, choices=[('clear', 'Očišćeno'), ('keep', 'Ostavljeno')], max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EcommerceApp.warehouselocation')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EcommerceApp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EcommerceApp.product')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EcommerceApp.productvariation')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('order', 'item_id_snapshot', 'location'), name='unique_pick_cleaning_request')],
            },
        ),
    ]
