# Generated by Django 6.0.6 on 2026-09-20 15:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0285_location_cleaning_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='iznos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='vrsta',
            field=models.CharField(choices=[('postotak', 'Postotak'), ('iznos', 'Iznos u KM'), ('dostava', 'Besplatna dostava')], default='postotak', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prva_prijava',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='postotak',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
