# Generated by Django 6.0.6 on 2026-09-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0287_order_marketing_attribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSearchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('query', models.CharField(db_index=True, max_length=160)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Pretraga sajta',
                'verbose_name_plural': 'Pretrage sajta',
                'indexes': [models.Index(fields=['-created_at', 'query'], name='EcommerceAp_created_cdaa69_idx')],
            },
        ),
    ]
