# Generated by Django 6.0.6 on 2026-09-22 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0288_site_search_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('event', models.CharField(choices=[('view', 'Pregled proizvoda'), ('cart', 'Dodano u korpu')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='EcommerceApp.product')),
            ],
            options={
                'verbose_name': 'Analitički događaj proizvoda',
                'verbose_name_plural': 'Analitički događaji proizvoda',
                'indexes': [models.Index(fields=['product', 'event', '-created_at'], name='EcommerceAp_product_2bc852_idx')],
            },
        ),
    ]
