# Generated by Django 6.0.6 on 2026-09-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0289_product_analytics_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2baccount',
            name='adresa',
            field=models.CharField(blank=True, max_length=300, verbose_name='Adresa'),
        ),
        migrations.AddField(
            model_name='b2baccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='b2baccount',
            name='grad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grad'),
        ),
        migrations.AddField(
            model_name='b2baccount',
            name='ime_prezime',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ime i prezime'),
        ),
        migrations.AddField(
            model_name='b2baccount',
            name='odbio_posiljku',
            field=models.BooleanField(default=False, verbose_name='Odbio pošiljku'),
        ),
        migrations.AddField(
            model_name='b2baccount',
            name='postanski_broj',
            field=models.CharField(blank=True, max_length=20, verbose_name='Poštanski broj'),
        ),
        migrations.AddField(
            model_name='b2baccount',
            name='telefon',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='b2baccount',
            name='vp_kupac',
            field=models.BooleanField(default=False, verbose_name='VP kupac'),
        ),
    ]
