# Generated by Django 6.0.6 on 2026-09-23 13:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0290_b2b_customer_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=1, default=Decimal('1.1'), max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
