# Generated by Django 6.0.6 on 2026-09-23 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0292_feeder_rods_search_aliases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinegiftcampaign',
            options={'ordering': ['-aktivan', '-azurirano'], 'verbose_name': 'Spin & Win', 'verbose_name_plural': 'Spin & Win'},
        ),
        migrations.AlterModelOptions(
            name='onlinegiftclaim',
            options={'ordering': ['-kreirano'], 'verbose_name': 'Spin & Win pokušaj', 'verbose_name_plural': 'Spin & Win pokušaji'},
        ),
    ]
