# Generated by Django 6.0.6 on 2026-09-23 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0293_spin_win_admin_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinegiftcampaign',
            options={'ordering': ['-aktivan', '-azurirano'], 'verbose_name': 'Online nagrada', 'verbose_name_plural': 'Online nagrade'},
        ),
        migrations.AlterModelOptions(
            name='onlinegiftclaim',
            options={'ordering': ['-kreirano'], 'verbose_name': 'Online nagrada (pokušaj)', 'verbose_name_plural': 'Online nagrade (pokušaji)'},
        ),
    ]
