# Generated by Django 6.0.6 on 2026-09-24 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0294_remove_spin_win_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinegiftclaim',
            name='scratch_eligibility_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='onlinegiftclaim',
            name='scratch_prize_code',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='onlinegiftclaim',
            name='scratch_week_start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='onlinegiftclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('scratch_week_start__isnull', False)), fields=('campaign', 'scratch_week_start', 'scratch_eligibility_key'), name='online_gift_one_scratch_claim_per_week'),
        ),
    ]
