# Generated by Django 6.0.6 on 2026-09-24 15:51

from django.db import migrations, models


def set_current_release(apps, schema_editor):
    DeploymentVersion = apps.get_model('EcommerceApp', 'DeploymentVersion')
    DeploymentVersion.objects.filter(pk=1).update(number='1.1.3')


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0295_sretni_greb_greb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentversion',
            name='number',
            field=models.CharField(default='1.1.3', max_length=32),
        ),
        migrations.RunPython(set_current_release, migrations.RunPython.noop),
    ]
