# Generated by Django 6.0.6 on 2026-09-24 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0296_semantic_deployment_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sretni_greb_greb_poklon',
            field=models.ForeignKey(blank=True, help_text='Artikal koji se automatski dodaje bez naplate kada kupac osvoji poklon i ispuni prag od 150 KM.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sretni_greb_greb_settings', to='EcommerceApp.product', verbose_name='Sretni Greb-Greb — poklon'),
        ),
    ]
