# Generated by Django 6.0.6 on 2026-09-24 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0297_scratch_gift_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='onlinegiftclaim',
            name='online_gift_one_scratch_claim_per_week',
        ),
        migrations.AddField(
            model_name='onlinegiftclaim',
            name='scratch_trigger_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scratch_reward_claims', to='EcommerceApp.order'),
        ),
        migrations.AddConstraint(
            model_name='onlinegiftclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('scratch_trigger_order__isnull', False)), fields=('campaign', 'scratch_trigger_order'), name='online_gift_one_scratch_claim_per_order'),
        ),
    ]
