# Generated by Django 6.0.6 on 2026-09-24 18:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_default_scratch_prizes(apps, schema_editor):
    Campaign = apps.get_model('EcommerceApp', 'OnlineGiftCampaign')
    ScratchPrize = apps.get_model('EcommerceApp', 'ScratchPrize')
    campaign, _ = Campaign.objects.get_or_create(
        naziv='SRETNI GREB-GREB',
        defaults={'aktivan': True, 'naslov': 'SRETNI GREB-GREB', 'automatic': False, 'poruka': 'Jedna prilika po narudžbi.'},
    )
    defaults = [
        ('percent_5', '5% popusta', 'percent', 35, '0.00', '5.00'),
        ('shipping', 'Besplatna dostava iznad 80 KM', 'shipping', 25, '80.00', '0.00'),
        ('gift', 'Poklon uz kupovinu iznad 150 KM', 'product', 15, '150.00', '0.00'),
        ('percent_10', '10% popusta iznad 100 KM', 'percent', 12, '100.00', '10.00'),
        ('percent_15', '15% popusta iznad 150 KM', 'percent', 5, '150.00', '15.00'),
        ('percent_20', '20% popusta iznad 200 KM', 'percent', 1, '200.00', '20.00'),
        ('none', 'Više sreće sljedeći put', 'none', 7, '0.00', '0.00'),
    ]
    for position, (code, label, kind, weight, minimum, percent) in enumerate(defaults):
        ScratchPrize.objects.get_or_create(
            campaign=campaign, code=code,
            defaults={'label': label, 'kind': kind, 'weight': weight, 'minimum': minimum,
                      'discount_percent': percent, 'sort_order': position},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0298_scratch_per_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScratchPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=24)),
                ('label', models.CharField(max_length=120, verbose_name='Tekst nagrade')),
                ('kind', models.CharField(choices=[('percent', 'Popust u procentima'), ('shipping', 'Besplatna dostava'), ('product', 'Besplatan artikal'), ('none', 'Bez nagrade')], max_length=12)),
                ('weight', models.PositiveSmallIntegerField(default=1, verbose_name='Šansa / težina')),
                ('minimum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Minimalna korpa (KM)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Popust (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivna')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scratch_prizes', to='EcommerceApp.onlinegiftcampaign')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scratch_prizes', to='EcommerceApp.product', verbose_name='Besplatan artikal')),
            ],
            options={
                'verbose_name': 'Sretni Greb-Greb nagrada',
                'verbose_name_plural': 'Sretni Greb-Greb nagrade',
                'ordering': ['sort_order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'code'), name='scratch_prize_unique_campaign_code')],
            },
        ),
        migrations.RunPython(seed_default_scratch_prizes, migrations.RunPython.noop),
    ]
