# Generated by Django 6.0.6 on 2026-09-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0299_scratch_prize_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scratchprize',
            name='kind',
            field=models.CharField(choices=[('percent', 'Popust u procentima'), ('shipping', 'Besplatna dostava'), ('product', 'Besplatan artikal'), ('product_discount', 'Artikal + popust'), ('none', 'Bez nagrade')], max_length=20),
        ),
    ]
