# Generated by Django 6.0.6 on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0300_scratch_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='livevisitor',
            name='uredjaj',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='mobile ili desktop — određeno iz user-agenta pri ulasku na sajt.',
                max_length=16,
                verbose_name='Uređaj',
            ),
        ),
    ]
