# Generated by Django 6.0.6 on 2026-09-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0301_livevisitor_uredjaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinegiftclaim',
            name='scratch_revealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinegiftclaim',
            name='scratch_reward_label',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='onlinegiftclaim',
            name='scratch_shown_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinegiftclaim',
            name='scratch_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
