# Generated by Django 6.0.6 on 2026-10-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0302_scratch_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseledgerentry',
            name='kind',
            field=models.CharField(choices=[('debit', 'Duguje — partner nama'), ('credit', 'Potražuje — mi partneru'), ('receipt', 'Primljena uplata'), ('payment', 'Naša uplata partneru'), ('order', 'Narudžba'), ('return', 'Povrat robe'), ('missing', 'Mi dugujemo — artikli koji fale'), ('excess', 'Kupac duguje — više poslato'), ('damaged', 'Oštećen artikal — mi dugujemo kupcu'), ('collection', 'Dug dodat na narudžbu'), ('settled', 'Izmireno — zamjena validatovana'), ('void', 'Poništen pogrešan unos')], max_length=12),
        ),
    ]
