# Generated by Django 6.0.6 on 2026-10-02 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0303_ledger_debt_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MungosProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mungos_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('sku_snapshot', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=32)),
                ('last_sync_error', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mungos_mapping', to='EcommerceApp.product')),
            ],
        ),
    ]
