# Generated by Django 6.0.6 on 2026-10-05 08:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0304_mungos_product_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='BAM', max_length=3)),
                ('environment', models.CharField(default='test', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Čeka uplatu'), ('paid', 'Plaćeno')], default='pending', max_length=16)),
                ('transaction_id', models.CharField(blank=True, max_length=64)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='card_payment', to='EcommerceApp.order')),
            ],
        ),
    ]
