# Generated by Django 6.0.6 on 2026-10-05 09:36

from django.db import migrations, models


def mark_pending_card_drafts(apps, schema_editor):
    Order = apps.get_model('EcommerceApp', 'Order')
    Order.objects.using(schema_editor.connection.alias).filter(
        status='nova', card_payment__status='pending',
    ).update(status='ceka_placanje')


def restore_pending_card_status(apps, schema_editor):
    Order = apps.get_model('EcommerceApp', 'Order')
    Order.objects.using(schema_editor.connection.alias).filter(
        status='ceka_placanje', card_payment__status='pending',
    ).update(status='nova')


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0305_card_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ceka_placanje', 'Čeka kartično plaćanje'), ('nova', 'Nova'), ('rezervacija', 'Rezervacija'), ('potvrdjena', 'Potvrđena'), ('poslana', 'Poslana'), ('zavrsena', 'Validatovana'), ('otkazana', 'Otkazana')], default='nova', max_length=20),
        ),
        migrations.RunPython(mark_pending_card_drafts, restore_pending_card_status),
    ]
