# Generated by Django 6.0.6 on 2026-10-05 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0306_card_order_pending_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpayment',
            name='checkout_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_payment', to='EcommerceApp.order'),
        ),
    ]
