# Generated by Django 6.0.6 on 2026-10-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0307_monri_checkout_before_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpayment',
            name='checkout_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='finalization_steps',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
