# Generated by Django 6.0.6 on 2026-10-06 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0308_monri_durable_finalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_set_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='set_component_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='set_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_children', to='EcommerceApp.orderitem'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_set',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Artikal je set'),
        ),
        migrations.CreateModel(
            name='ProductSetComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_sets', to='EcommerceApp.product')),
                ('set_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_components', to='EcommerceApp.product')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EcommerceApp.productvariation')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='set_component_positive_qty')],
            },
        ),
    ]
