# Generated by Django 6.0.6 on 2026-10-06 11:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def preserve_existing_rewards(apps, schema_editor):
    from secrets import token_hex
    Claim = apps.get_model('EcommerceApp', 'OnlineGiftClaim')
    Coupon = apps.get_model('EcommerceApp', 'Coupon')
    Prize = apps.get_model('EcommerceApp', 'ScratchPrize')
    db = schema_editor.connection.alias
    for claim in Claim.objects.using(db).filter(campaign__naziv='SRETNI GREB-GREB', won=True,
                                               reward_consumed=False, prize_type='percent').iterator():
        prize = Prize.objects.using(db).filter(campaign_id=claim.campaign_id, code=claim.scratch_prize_code).first()
        Coupon.objects.using(db).get_or_create(scratch_claim_id=claim.pk, defaults={
            'kod': 'GREB-' + token_hex(7).upper(), 'naziv': 'Sretni Greb-Greb',
            'postotak': claim.discount_percent, 'minimum': prize.minimum if prize else Decimal('0.00'),
            'vlasnik_id': claim.user_id,
        })


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0309_product_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='minimum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='scratch_claim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon', to='EcommerceApp.onlinegiftclaim'),
        ),
        migrations.AddField(
            model_name='onlinegiftclaim',
            name='coupon_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(preserve_existing_rewards, migrations.RunPython.noop),
    ]
