# Generated by Django 6.0.6 on 2026-10-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0310_scratch_reward_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours',
            field=models.TextField(blank=True, verbose_name='Radno vrijeme'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_address',
            field=models.CharField(blank=True, max_length=240, verbose_name='Adresa firme'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_bank_account',
            field=models.CharField(blank=True, max_length=120, verbose_name='Transakcijski račun'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Naziv firme'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_tax_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='ID / PDV broj'),
        ),
    ]
