# Generated by Django 6.0.6 on 2026-10-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0311_white_label_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_banner',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='Newsletter banner'),
        ),
    ]
