# Generated by Django 6.0.6 on 2026-10-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0312_configurable_newsletter_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prioritet_lagera',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Normalno'), (1, 'Favorizuj'), (2, 'Hit redukovanje lagera'), (3, 'Forsiraj u pretrazi')], db_index=True, default=0, help_text='Prioritet među relevantnim rezultatima (pretraga, kategorija, preporuke). Nikad ne gura nerelevantne artikle. Normalno = bez boosta; Favorizuj = blago; Hit redukovanje lagera = jak prioritet; Forsiraj = prvi među rezultatima pretrage.', verbose_name='Redukovanje lagera'),
        ),
    ]
