# Generated by Django 6.0.6 on 2026-10-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0313_forced_search_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pracenje_zaliha',
            field=models.BooleanField(default=True, help_text='Bez praćenja: dostupnost se uključuje i isključuje ručno, bez količina i lokacija.', verbose_name='Praćenje zaliha'),
        ),
    ]
