# Generated by Django 6.0.6 on 2026-10-08 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0314_product_stock_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBestsellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redoslijed', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('aktivan', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('artikal', models.ForeignKey(limit_choices_to={'aktivan': True}, on_delete=django.db.models.deletion.CASCADE, related_name='najprodavaniji_na_pocetnoj', to='EcommerceApp.product', verbose_name='Postojeći artikal')),
                ('postavke', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='najprodavaniji_artikli', to='EcommerceApp.sitesettings')),
            ],
            options={
                'verbose_name': 'Najprodavaniji proizvod (početna)',
                'verbose_name_plural': 'Najprodavaniji proizvodi',
                'ordering': ['redoslijed', 'id'],
            },
        ),
    ]
