# Generated by Django 6.0.6 on 2026-10-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0315_home_bestseller_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pracenje_lagera', models.BooleanField(default=True, help_text='Uključeno: dostupnost zavisi od količine. Isključeno: oznaka „Na stanju” mijenja se ručno.', verbose_name='Praćenje lagera')),
            ],
            options={
                'verbose_name': 'Moduli / Dozvole',
                'verbose_name_plural': 'Moduli / Dozvole',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='modul_sakriven',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
