# Generated by Django 6.0.6 on 2026-10-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0316_inventory_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermissions',
            name='pracenje_lagera',
            field=models.BooleanField(default=True, help_text='Uključeno: dostupnost zavisi od količine. Isključeno: oznaka „Na stanju” mijenja se ručno.', verbose_name='Praćenje lagera (Dostupnost kol. na sajtu, Magacin: Artikli, Narudžbe, Picking, Kupci)'),
        ),
    ]
