# Generated by Django 6.0.6 on 2026-10-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0317_inventory_module_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepermissions',
            name='artikli_u_setu',
            field=models.BooleanField(default=True, help_text='Uključeno: dozvoljava pristup alatu Artikli u setu. Isključeno: alat je zaključan.', verbose_name='Artikli u setu'),
        ),
    ]
