# Generated by Django 6.0.6 on 2026-10-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0318_product_sets_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepermissions',
            name='dnevno_skidanje',
            field=models.BooleanField(default=True, verbose_name='Dnevno skidanje MP lagera'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='duguje_potrazuje',
            field=models.BooleanField(default=True, verbose_name='Duguje / Potražuje'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='dupli_barkodovi',
            field=models.BooleanField(default=True, verbose_name='Dupli barkodovi'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='fali_u_mp',
            field=models.BooleanField(default=True, verbose_name='Fali u MP-u'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='izvjestaji',
            field=models.BooleanField(default=True, verbose_name='Izvještaji'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='kreiraj_ponudu',
            field=models.BooleanField(default=True, verbose_name='Kreiraj ponudu'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='nivelacije',
            field=models.BooleanField(default=True, verbose_name='Nivelacije'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='popis_robe',
            field=models.BooleanField(default=True, verbose_name='Popis robe'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='stampa_cijena',
            field=models.BooleanField(default=True, verbose_name='Štampaj cijene'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='stampa_deklaracije',
            field=models.BooleanField(default=True, verbose_name='Štampaj deklaracije'),
        ),
    ]
