# Generated by Django 6.0.6 on 2026-10-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0319_warehouse_tool_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepermissions',
            name='rezervni_dijelovi',
            field=models.BooleanField(default=True, verbose_name='Rezervni dijelovi'),
        ),
    ]
