# Generated by Django 6.0.6 on 2026-10-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0321_stock_check_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermissions',
            name='provjera_lagera',
            field=models.BooleanField(default=True, verbose_name='Provjera lagera (Lokacije, Zalihe, Transferi)'),
        ),
    ]
