# Generated by Django 6.0.6 on 2026-10-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0322_stock_check_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepermissions',
            name='uvoz',
            field=models.BooleanField(default=True, verbose_name='Uvoz'),
        ),
    ]
