# Generated by Django 6.0.6 on 2026-10-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0323_import_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepermissions',
            name='b2b',
            field=models.BooleanField(default=True, verbose_name='B2B'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='live_centar',
            field=models.BooleanField(default=True, verbose_name='Live centar'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='loyalty',
            field=models.BooleanField(default=True, verbose_name='Loyalty'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='poklon_vaucer',
            field=models.BooleanField(default=True, verbose_name='Poklon vaučer'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='posjetioci_uzivo',
            field=models.BooleanField(default=True, verbose_name='Posjetioci uživo'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='sretni_greb_greb',
            field=models.BooleanField(default=True, verbose_name='Sretni Greb-Greb'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='stavke_aktivnih_korpi',
            field=models.BooleanField(default=True, verbose_name='Stavke aktivnih korpi'),
        ),
    ]
