# Generated by Django 6.0.6 on 2026-10-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0324_panel_tool_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepermissions',
            name='banner_odrediste_filter',
            field=models.BooleanField(default=True, help_text='Zaključava odredište i filter bannera. Polje Link ostaje uvijek dostupno.', verbose_name='Banner — Odredište i filter'),
        ),
    ]
