# Generated by Django 6.0.6 on 2026-10-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0325_banner_destination_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepermissions',
            name='akcije',
            field=models.BooleanField(default=True, help_text='Omogućava pristup Akcijama u panelu.', verbose_name='Akcije'),
        ),
    ]
