# Generated by Django 6.0.6 on 2026-10-09 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0326_panel_actions_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='WMSLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=120, unique=True)),
                ('opis', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'ordering': ['naziv'],
            },
        ),
        migrations.CreateModel(
            name='WMSOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('vp', 'Veleprodaja'), ('online', 'Online slanje')], max_length=12)),
                ('kupac', models.CharField(max_length=240)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=60)),
                ('adresa', models.CharField(blank=True, max_length=300)),
                ('napomena', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('nova', 'Nova narudžba'), ('pakovanje', 'Pakovanje'), ('zapakovana', 'Zapakovana')], default='nova', max_length=12)),
                ('kreirana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-kreirana'],
            },
        ),
        migrations.CreateModel(
            name='WMSStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra', models.CharField(max_length=80)),
                ('naziv', models.CharField(max_length=240)),
                ('kolicina', models.PositiveIntegerField(default=0)),
                ('lokacija', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zalihe', to='EcommerceApp.wmslocation')),
            ],
            options={
                'ordering': ['naziv', 'sifra'],
                'constraints': [models.UniqueConstraint(fields=('sifra', 'lokacija'), name='wms_stock_sifra_location')],
            },
        ),
    ]
