# Generated by Django 6.0.6 on 2026-10-09 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0327_independent_wms'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wms_lokacija',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artikli', to='EcommerceApp.wmslocation', verbose_name='WMS lokacija'),
        ),
    ]
