# Generated by Django 6.0.6 on 2026-10-09 08:19

import django.db.models.deletion
from django.db import migrations, models


def seed_locations(apps, schema_editor):
    Product = apps.get_model('EcommerceApp', 'Product')
    Stock = apps.get_model('EcommerceApp', 'ProductWMSStock')
    for product in Product.objects.using(schema_editor.connection.alias).filter(wms_lokacija__isnull=False).iterator():
        Stock.objects.using(schema_editor.connection.alias).create(product_id=product.pk, lokacija_id=product.wms_lokacija_id, kolicina=product.stanje)


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0328_product_wms_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWMSStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.PositiveIntegerField(default=0)),
                ('lokacija', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stanje_artikala', to='EcommerceApp.wmslocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wms_zalihe', to='EcommerceApp.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'lokacija'), name='product_wms_unique_location')],
            },
        ),
        migrations.RunPython(seed_locations, migrations.RunPython.noop),
    ]
