# Generated by Django 6.0.6 on 2026-10-09 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0329_product_multiple_wms_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enabled_360',
            field=models.BooleanField(default=False, verbose_name='Omogući 360° prikaz'),
        ),
        migrations.CreateModel(
            name='Product360Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/360/')),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_360', to='EcommerceApp.product')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('product', 'position'), name='product360_unique_position')],
            },
        ),
    ]
