# Generated by Django 6.0.6 on 2026-10-09 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0330_product_360'),
    ]

    operations = [
        migrations.CreateModel(
            name='WMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='EcommerceApp.wmslocation', verbose_name='Lokacija za prenos iz Zaliha')),
            ],
        ),
    ]
