# Generated by Django 6.0.6 on 2026-10-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0331_wms_transfer_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepermissions',
            name='wms_lokacije',
            field=models.BooleanField(default=True, verbose_name='Lokacije'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='wms_narudzbe',
            field=models.BooleanField(default=True, verbose_name='Narudžbe'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='wms_pakovanje',
            field=models.BooleanField(default=True, verbose_name='Pakovanje'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='wms_prenosnice',
            field=models.BooleanField(default=True, verbose_name='Prenosnice'),
        ),
        migrations.AddField(
            model_name='modulepermissions',
            name='wms_zalihe',
            field=models.BooleanField(default=True, verbose_name='Zalihe'),
        ),
    ]
