# Generated by Django 6.0.6 on 2026-10-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0332_wms_section_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmssettings',
            name='show_storefront_availability',
            field=models.BooleanField(default=True, verbose_name='Prikaz dostupnosti artikala na sajtu'),
        ),
    ]
