# Generated by Django 6.0.6 on 2026-10-09 09:13

from django.db import migrations, models


def merge_permissions(apps, schema_editor):
    ModulePermissions = apps.get_model('EcommerceApp', 'ModulePermissions')
    ModulePermissions.objects.using(schema_editor.connection.alias).filter(wms_lokacije=False).update(wms_zalihe=False)


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0333_wms_storefront_availability'),
    ]

    operations = [
        migrations.RunPython(merge_permissions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='modulepermissions',
            name='wms_zalihe',
            field=models.BooleanField(default=True, verbose_name='Zalihe i Lokacije'),
        ),
    ]
