# Generated by Django 6.0.6 on 2026-10-09 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0336_visible_out_of_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='WMSTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='EcommerceApp.wmslocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_transfers', to='EcommerceApp.product')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='EcommerceApp.wmslocation')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='wms_transfer_positive_quantity')],
            },
        ),
    ]
