# Generated by Django 6.0.6 on 2026-10-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0337_wms_transfer_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmsorder',
            name='status',
            field=models.CharField(choices=[('nova', 'Nova narudžba'), ('pakovanje', 'Pakovanje'), ('zapakovana', 'Zapakovana'), ('otkazana', 'Otkazana')], default='nova', max_length=12),
        ),
    ]
