# Generated by Django 6.0.6 on 2026-10-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0338_wms_order_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsorder',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Razlog otkazivanja'),
        ),
    ]
