# Generated by Django 6.0.6 on 2026-10-09 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0339_wms_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsorder',
            name='source_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wms_order', to='EcommerceApp.order'),
        ),
    ]
