# Generated by Django 6.0.6 on 2026-10-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0340_wms_panel_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermissions',
            name='wms_pakovanje',
            field=models.BooleanField(default=True, verbose_name='Odvajanje robe'),
        ),
        migrations.AlterField(
            model_name='wmsorder',
            name='status',
            field=models.CharField(choices=[('nova', 'Nova narudžba'), ('pakovanje', 'Odvajanje robe'), ('zapakovana', 'Završena'), ('otkazana', 'Otkazana')], default='nova', max_length=12),
        ),
    ]
