# Generated by Django 6.0.6 on 2026-10-09 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0341_wms_odvajanje_robe'),
    ]

    operations = [
        migrations.CreateModel(
            name='WMSPickLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('confirmed_quantity', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(upload_to='wms/picking/%Y/%m/')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EcommerceApp.orderitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EcommerceApp.wmslocation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_lines', to='EcommerceApp.wmsorder')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('order', 'item', 'location'), name='wms_pick_item_location_unique')],
            },
        ),
    ]
