# Generated by Django 6.0.6 on 2026-10-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0342_wms_picking_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmspickline',
            name='photo',
            field=models.ImageField(blank=True, upload_to='wms/picking/%Y/%m/'),
        ),
    ]
