# Generated by Django 6.0.6 on 2026-10-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0343_wms_optional_picking_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmspickline',
            name='shortage_resolution',
            field=models.CharField(blank=True, choices=[('clear', 'Očišćeno'), ('keep', 'Ostavljeno')], max_length=10),
        ),
        migrations.AddField(
            model_name='wmspickline',
            name='shortage_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
