# Generated by Django 6.0.6 on 2026-10-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0344_wms_shortage_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
