# Generated by Django 6.0.6 on 2026-10-09 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0345_wms_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmspickline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EcommerceApp.orderitem'),
        ),
        migrations.CreateModel(
            name='WMSOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('sifra', models.CharField(blank=True, max_length=100)),
                ('kolicina', models.PositiveIntegerField()),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('artikal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EcommerceApp.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='EcommerceApp.wmsorder')),
            ],
        ),
        migrations.AddField(
            model_name='wmspickline',
            name='wms_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EcommerceApp.wmsorderitem'),
        ),
    ]
