# Generated by Django 6.0.6 on 2026-10-09 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0346_wms_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='WMSCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_prezime', models.CharField(max_length=240)),
                ('telefon', models.CharField(max_length=60)),
                ('adresa', models.CharField(max_length=300)),
                ('grad', models.CharField(max_length=100)),
                ('postanski_broj', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['ime_prezime', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='wmsorder',
            name='grad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wmsorder',
            name='postanski_broj',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='wmsorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EcommerceApp.wmscustomer'),
        ),
    ]
