# Generated by Django 6.0.6 on 2026-10-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0347_wms_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsorderitem',
            name='popust',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
