# Generated by Django 6.0.6 on 2026-10-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0348_wms_item_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmscustomer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
