# Generated by Django 6.0.6 on 2026-10-09 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0349_wms_customer_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmssettings',
            name='picking_last_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='EcommerceApp.wmslocation', verbose_name='Lokacija koja se posljednja nudi za odvajanje'),
        ),
    ]
