# Generated by Django 6.0.6 on 2026-10-09 14:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0350_wms_picking_last_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsorderitem',
            name='bazna_cijena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wmssettings',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('17.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='PDV (%)'),
        ),
    ]
