# Generated by Django 6.0.6 on 2026-10-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0351_wms_vat_regular_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='chat_pozdrav_poruka',
            field=models.TextField(blank=True, default='Zdravo! 👋 Dobrodošli u naš webshop.\n\nTreba li vam pomoć ili preporuka pri kupovini?\nPišite nam — tu smo da pomognemo.', help_text='Poruka koju sistem šalje kad se chat otvori. Kupac odmah može odgovoriti (bez registracije).', verbose_name='Chat — automatska pozdrav poruka'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='kontakt_messenger',
            field=models.CharField(blank=True, help_text='Korisničko ime Facebook stranice za Messenger, npr. shop.example', max_length=120, verbose_name='Facebook Messenger'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_desno_kategorije',
            field=models.ImageField(blank=True, help_text='Upload loga na krajnjoj desnoj strani reda kategorija. Preporuka: 1000 × 200 px (5:1), JPG ili PNG. Ako je prazno, prikazuje se priloženi Webshop logo.', null=True, upload_to='site/category-logos/', verbose_name='Desni logo uz Sve kategorije'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_glavni_sajt',
            field=models.ImageField(blank=True, help_text='Prikazuje se u headeru ispod glavnog loga uz tekst „by” (pod-sajt / Webshop). Automatski se skalira na ~200×48px PNG.', null=True, upload_to='site/', verbose_name='Logo glavnog sajta'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_email',
            field=models.EmailField(blank=True, default='', help_text='Za schema.org ContactPoint (customer service).', max_length=254, verbose_name='SEO / kontakt email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_facebook_url',
            field=models.URLField(blank=True, default='', help_text='Puni link na Facebook stranicu (schema sameAs).', verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_organizacija_naziv',
            field=models.CharField(blank=True, default='Webshop', help_text='Prikazuje se u Google Knowledge / Organization JSON-LD.', max_length=120, verbose_name='Naziv trgovine (schema.org)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_title_suffix',
            field=models.CharField(blank=True, default='Webshop', help_text='Dodaje se na kraju title-a kad nije već unesen (npr. „Naziv artikla | shop.example”). Prazno = bez sufiksa.', max_length=40, verbose_name='Sufiks u title tagu'),
        ),
    ]
